### ISSUE TITLE
LS should always perform ES license check

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-output-elasticsearch#1004]
Historically the output did not do a license check on OSS Logstash.
However with the recent ES licensing change (since 7.11) there's no OSS ES artifact anymore.
Thus the distinction makes no sense.

The license check is really simple basically assuring the returned JSON has [`license.status == 'active'`](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v10.8.4/lib/logstash/outputs/elasticsearch/license_checker.rb#L39)

A resolution should simply be removing a line to [skip the check under OSS](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v10.8.4/lib/logstash/outputs/elasticsearch/license_checker.rb#L14).

Potential hiccups: ES versions older than 7.11. 
The plugin would need to check the version first and skip the license check (under OSS) for ES < 7.11 for backwards compatibility.

**Comment by bensebborn** [comment]
It seems Elastic won't fix this issue to cause issues for AWS customers

**Comment by fatalglitch** [comment]
This is not fixed. If you run plugin updates on the OSS versions of Logstash, it pulls in the elasticsearch-output plugin which contains the _license check, thereby making it un-usable under OSS versions of Elasticsearch. Why is this acceptable?
