### ISSUE TITLE
Missing (ECS) schema for ES 8.0

### ISSUE THREAD

**Issue by kares** [logstash-plugins/logstash-output-elasticsearch#1022]
Logstash snapshot **8.0.0-SNAPSHOT** with ES snapshot **8.0.0-SNAPSHOT** fails to start.

Since https://github.com/elastic/logstash/pull/12830 LS enabled `ecs_compatibility => v1` default for 8.0 (SNAPSHOT).
When running against (unreleased) ES 8.0 loading the plugin fails due a missing schema file [for version 8](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/476097712b67e0452099769b2c8b0ef6e63e40eb/Rakefile#L12-L13), leading to a:

```
[logstash.outputs.elasticsearch][main] Failed to install template {:message=>"Failed to load default template for Elasticsearch v8 with ECS v1; caused by: #<ArgumentError: Template file '/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.0.2-java/lib/logstash/outputs/elasticsearch/templates/ecs-v1/elasticsearch-8x.json' could not be found>", :exception=>RuntimeError, :backtrace=>
```

**Comment by yaauie** [comment]
Assigning to myself.

ECS v1 doesn't include a generated template for Elasticsearch 8, so our vendor scripts will need to be modified. I've got a WIP that symlinks additional variants, and am making another pass at the specs to make sure that they _really_ make sense in terms of the default value changing recently in Logstash core.

**Comment by kares** [comment]
related issue (a request to update the templates for v1): https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1022

**Comment by roaksoax** [comment]
This issue has now been fixed as the templates are now available for the expected releases.
