### ISSUE TITLE
Auto-created indices follow the pattern `.ds-logs-generic-default-*` since v8.0.0

### ISSUE THREAD

**Issue by antoineco** [logstash-plugins/logstash-output-elasticsearch#1031]
**Logstash information**:

Please include the following information:

1. Logstash version: **8.0.0 (alpha1)**
2. Logstash installation source: **Docker image** (`docker.elastic.co/logstash/logstash:8.0.0-alpha1`)
3. How is Logstash being run: **Docker** (default image's entrypoint)
4. How was the Logstash Plugin installed: **Built-in version** `logstash-output-elasticsearch (11.0.2)`

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version: **OpenJDK 64-Bit Server VM 11.0.11+9** on 11.0.11+9 +indy +jit [linux-x86_64]"
2. JVM installation source: **Docker image's built-in version**
3. Value of the `JAVA_HOME` environment variable if set.

**OS version**: **Linux 4.19.128**

**Description of the problem including expected versus actual behavior**:

Using a fairly vanilla configuration, the Elasticsearch output creates indices which name follow the pattern `.ds-logs-generic-default-%{+yyyy.MM.dd}` instead of the [documented pattern](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index) `logstash-%{+yyyy.MM.dd}`.

As a result, the index template (auto-)created by the for the pattern `logstash-*` doesn't apply to documents sent by the output, on top of breaking the previous behaviour of Elastic v7.x.

**Steps to reproduce**:

Logstash pipeline config:

```
output {
	elasticsearch {
		hosts => "elasticsearch:9200"
		user => "elastic"
		password => "changeme"
	}
}
```

**Provide logs (if relevant)**:

**Comment by antoineco** [comment]
Based on [this discussion](https://discuss.elastic.co/t/where-is-the-object-mapping-for-host-defined/281541) in the Elastic forums, this might be related to a possible change in the default value of the [`data_stream`](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-data_stream) parameter. If that is the case, is it expected that the `logstash-*` index isn't used?

**Comment by looneym** [comment]
Why has this been labeled a `wontfix`? I just ran into this when setting up a brand new ELK stack on 8.9. The behavior of logstash and ES is completely different to what is documented. As someone new to most ES concepts I've burned a couple of days trying to understand how to effectively rotate logs until I googled the magic keyword `ds-logs-generic-default`.

At the very least the documentation should be updated.

**Comment by antoineco** [comment]
> The behavior of logstash and ES is completely different to what is documented.

Turns out that it is not. The bahaviour  _is_ documented. Possibly confusing for someone coming from v7, but documented.

Refs:
- https://www.elastic.co/guide/en/logstash/8.0/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-data_stream
- https://www.elastic.co/guide/en/elasticsearch/reference/8.0/data-streams.html
