### ISSUE TITLE
Add support for 'traces' data stream type

### ISSUE THREAD

**Issue by ultrr** [logstash-plugins/logstash-output-elasticsearch#1052]
Currently, the plugin supports only following data stream types: 'logs', 'metrics', 'synthetics'. Other applications, for example APM Server also supports output to 'traces' type.

In our use case, we will like to use APM Server to place traces into ElasticSearch data stream via Logstash and at the moment this way to do so isn't possible.

**Comment by kares** [comment]
Makes sense, the `type` naming already includes `'traces'` with [DS in Fleet Agent](https://www.elastic.co/guide/en/fleet/8.0/data-streams.html#data-streams-naming-scheme) as well ...
