### ISSUE TITLE
Tries to validate the remote certificate also if `ssl_certificate_verification` is `false`

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-output-elasticsearch#1058]
**Logstash information**:

Please include the following information:

1. Logstash version: any, tried with `7.15.2`
2. Logstash installation source: indifferent, tried from source
3. How is Logstash being run : via command line, but it's not related to this
4. How was the Logstash Plugin installed: shipped with Logstash distribution

**OS version** (`uname -a` if on a Unix-like system):
any

**Description of the problem including expected versus actual behavior**:
Running Logstash against a secured Elastisearch with:
```
bin/logstash -e 'output { elasticsearch {  hosts => ["https://<host>:<port>"]    ssl_certificate_verification => false    user => "elastic"    password => "<password>"    index => "logstash-ingest"   manage_template => false   }  }'
```
it returns:
```
[2021-12-02T11:55:29,434][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error {:url=>"https://elastic:xxxxxx@2228780f2e51410cafa304895da2a2c9.35.233.81.128.ip.es.io:9243/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@2228780f2e51410cafa304895da2a2c9.35.233.81.128.ip.es.io:9243/][Manticore::ClientProtocolException] PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}
```

Tracking down how the call is done by Manticore, the library used by Logstash, it's possibile to reproduce with the following script:
```ruby
require 'manticore'

options = {:socket_timeout=>60,
           :request_timeout=>60,
           :check_connection_timeout=>10000,
           :pool_max=>1000,
           :pool_max_per_route=>100,
           :ssl=>{:enabled=>true, :verify=>false},
           :headers=>{},
           :automatic_retries=>0,
           :cookies=>false}
manticore = ::Manticore::Client.new(options)

params = {:headers=>{"Content-Type"=>"application/json"}, :auth=>{:user=>"elastic", :password=>"<secret>", :eager=>true}}
resp = manticore.send("head", "https://<host>:<port>", params)
resp.call
```
it raises:
```
Manticore::ClientProtocolException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  initialize at /home/andrea/.rvm/gems/jruby-9.2.19.0/gems/manticore-0.7.1-java/lib/manticore/response.rb:36
        call at /home/andrea/.rvm/gems/jruby-9.2.19.0/gems/manticore-0.7.1-java/lib/manticore/response.rb:79
      <main> at manticore_test.rb:16
```

It's related to the way Manticore verifies certificates and relates to https://github.com/cheald/manticore/pull/100.

So once the new version of Mantire is out, update also the one used in this plugin,

**Comment by kares** [comment]
turns out we the way Manticore (HttpClient 4.5) works is that on the client side it does not provide a way of skipping the check of the trust store (even with https://github.com/cheald/manticore/pull/100 applied).

the `TrustManagerDelegate` used with the `org.apache.http.conn.ssl.TrustAllStrategy` does the following:

```java
        @Override
        public void checkClientTrusted(
                final X509Certificate[] chain, final String authType) throws CertificateException {
            this.trustManager.checkClientTrusted(chain, authType);
        }

        @Override
        public void checkServerTrusted(
                final X509Certificate[] chain, final String authType) throws CertificateException {
            if (!this.trustStrategy.isTrusted(chain, authType)) {
                this.trustManager.checkServerTrusted(chain, authType);
            }
        }
```

what https://github.com/cheald/manticore/pull/100 achieves is to be able to skip hostname verification, however a trust anchor still needs to happen e.g. one can not skip configuring the (trust-store) CA path for a client certificate, that still leads to a: `javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by andsel** [comment]
So, do we need to wait for a new Manticore version with your PR https://github.com/cheald/manticore/pull/102 and then updated the dependency on the plugin, right?

**Comment by kares** [comment]
Sorry for the noise (and wanted to provide an update before I forget what I'm hitting), was hitting some weirdness where the trust anchor building did still matter but I was testing smt slightly different on CI than I thought. There's a couple of "invalid" cert integration scenarios in #1063 and all seems to be working :factory_worker: 

> So, do we need to wait for a new Manticore version with your PR cheald/manticore#102 and then updated the dependency on the plugin, right?

This isn't related - basically restores the deprecated `verify: false` to behave as before while (the official) `verify: :disable` properly disables all verification, as expected.
