### ISSUE TITLE
undefined method `load_runtime_jars!' for LogStash::Environment:Module

### ISSUE THREAD

**Issue by DanielRedOak** [logstash-plugins/logstash-output-elasticsearch#106]
With the latest version I am seeing this error when trying to run with the logstash-output-elasticsearch plugin.

Couldn't find any output plugin named 'elasticsearch'. Are you sure this is correct? Trying to load the elasticsearch output plugin resulted in this error: undefined method `load_runtime_jars!' for LogStash::Environment:Module

**Comment by suyograo** [comment]
@DanielRedOak we recently changed the jar bundling strategy. https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/101 

did you try `bin/logstash update logstash-output-elasticsearch` ?

**Comment by DanielRedOak** [comment]
Yep, I'm on the current plugin version having these issues.  Also tried an uninstall, then reinstall

**Comment by talevy** [comment]
are you running off a local copy of the logstash repo? have you caught up with latest master?

**Comment by DanielRedOak** [comment]
I am not running master, RC2 is the current 'release' we run

**Comment by talevy** [comment]
try:

```
bin/plugin install --version=0.2.0 logstash-output-elasticsearch
```

The latest: `v0.2.1` has an update that is only compatible with `master`

**Comment by DanielRedOak** [comment]
Sure, I'll close this issue then and re-test with the next release of logstash
