### ISSUE TITLE
Should Logstash create a "message.raw" by default?

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#11]
The [template that ships with this plugin](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json) will add a raw field for each event field. However, in most cases, the not_analyzed version of "message" is of no use and only takes up disk space.

Could we not generate a message.raw? Is there a use for it?

**Comment by derEremit** [comment]
-1 on not having error.message.raw available in my kibana
that was one of the first things I wanted to build with my ELK setup
a list of error messages by number

**Comment by jordansissel** [comment]
> -1 on not having error.message.raw available in my kibana

@derEremit This ticket was specifically about the top-level field named `message`, not `error.message`, so unless I am not understanding, your `error.message` field will continue to behave the way you want :)

**Comment by derEremit** [comment]
okay, I thought this ticket applies to my problem, as I don't get .raw fields on anything ending with message, on my unmodified logstash, elastic 2.3 setup

should I re-check and open a separate issue for that?

**Comment by jordansissel** [comment]
Open a new issue

**Comment by clintongormley** [comment]
@jordansissel btw the way the template is defined at the moment will match any field whose name is `message` (which includes `foo.bar.message`).  To limit it to just the top-level `message` field, it should use `path_match` instead of `match`

**Comment by talevy** [comment]
I've opened a PR to do just what you describe @clintongormley 

https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/481
