### ISSUE TITLE
introduce Docker for integration testing

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#111]
this will include:

1. start-up elasticsearch container before test suite
2. allow plugin tests to reach ES url served in docker container for testing against
3. teardown container when done

**Comment by suyograo** [comment]
+1000

**Comment by untergeek** [comment]
:+1: times a billion

**Comment by untergeek** [comment]
what makes this extra cool is that the ES docker image built here can be used by, say, the couchdb_changes integration tests too.
