### ISSUE TITLE
adapt https ssl setup to match es-ruby/manticore API change

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#119]
With https://github.com/elastic/elasticsearch-ruby/pull/142 it's now cleaner to configure SSL on elasticsearch-ruby, and this plugin needs to reflect that API change

implementation details [here](https://github.com/elastic/elasticsearch-ruby/commit/cb8e799768b5c9932dad5f8bc8af5507a856eb12)

**Comment by guyboertje** [comment]
Fixed in #240
