### ISSUE TITLE
Remove deprecated SSL settings from Elasticsearch output

### ISSUE THREAD

**Issue by robbavey** [logstash-plugins/logstash-output-elasticsearch#1190]
- [x]  Create branch from most recent commit on main
- [x] All plugin changes that remove SSL settings should be in a new major release of the plugin
- [x] Mark old SSL settings as obsolete
- [x] Add breaking change entry to plugin changelog
- [x] Add details of change to the 9.0 breaking changes documentation in core.
- [x] Verify that any integration tests in core that rely on SSL settings still work. Fix any broken integration tests
- [x] Verify plugin documentation, remove any references to deprecated settings

**Comment by donoghuc** [comment]
See https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1118 for original standardization work.

**Comment by donoghuc** [comment]
Logstash docs PR https://github.com/elastic/logstash/pull/16787
