### ISSUE TITLE
Do not load dependency jars when using protocol=http

### ISSUE THREAD

**Issue by rtoma** [logstash-plugins/logstash-output-elasticsearch#122]
Only do `require 'logstash-output-elasticsearch_jars.rb'` when using protocol 'transport' or 'node'. For protocol 'http' these jars are not needed and a total waste of memory.

Following list of jars are loaded from path /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/vendor/jar-dependencies/runtime-jars:

```
antlr-runtime-3.5.jar
asm-4.1.jar
asm-commons-4.1.jar
elasticsearch-1.5.1.jar
lucene-analyzers-common-4.10.4.jar
lucene-core-4.10.4.jar
lucene-grouping-4.10.4.jar
lucene-highlighter-4.10.4.jar
lucene-join-4.10.4.jar
lucene-memory-4.10.4.jar
lucene-misc-4.10.4.jar
lucene-queries-4.10.4.jar
lucene-queryparser-4.10.4.jar
lucene-sandbox-4.10.4.jar
lucene-spatial-4.10.4.jar
lucene-suggest-4.10.4.jar
spatial4j-0.4.1.jar
```

**Comment by andrewvc** [comment]
Apologies for the delay, thanks for the report. We no longer support the transport / node protocols so this is no longer an issue.
