### ISSUE TITLE
NotSuchField exception when having two plugins that use Lucene

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-output-elasticsearch#126]
If you've the neo4j output plugins + the elasticsearch output plugin, the ES output plugin can not register complaining with an error like:

```
  1) outputs/elasticsearch registration should register
     Failure/Error: expect {output.register}.to_not raise_error
       expected no Exception, got java.lang.NoSuchFieldError: LUCENE_3_6 with backtrace:
         # org.elasticsearch.Version.<clinit>(org/elasticsearch/Version.java:43)
         # org.elasticsearch.client.transport.TransportClient.<init>(org/elasticsearch/client/transport/TransportClient.java:168)
         # org.elasticsearch.client.transport.TransportClient.<init>(org/elasticsearch/client/transport/TransportClient.java:123)
         # java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:526)
         # RUBY.(root)(./rakelib/test.rake:38)
     # ./rakelib/test.rake:38:in `(root)'
```

best guess is that both use Lucene underneath so there is a version conflic somwhere.

**Comment by jsvd** [comment]
this plugin doesn't raise this issue if loaded after logstash-output-elasticsearch?

**Comment by purbon** [comment]
Did not check, this is the outcome of the test suites. On the other hand it should not care when is loaded. The ES output should work with their jars and the neo4j one with his.

As far as I could debug this is because of different LUCENE versions being loaded.

**Comment by purbon** [comment]
It complain the other way around with neo4j in case one gets loaded before the other, i guess we should find a way to handle this dependency situations between plugins.

**Comment by purbon** [comment]
I close this issue in favor of a more general one in the logstash-core repo as this is an issue that will hapen whenerver jars with conflicting versions are loaded.

To reproduce this you can:

1.- Add the logstash-input-neo4j
2.- Add the logstash-output-elasticsearch

run the tests.

This happen in the context of neo4j/elasticsearch because of conflicting lucene versions being in use:

```
.//bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/vendor/jar-dependencies/runtime-jars/lucene-core-4.10.4.jar
.//bundle/jruby/1.9/gems/neo4j-community-2.0.1/lib/neo4j-community/jars/lucene-core-3.6.2.jar
 ```

it will happen for others jars dependencies too.
