### ISSUE TITLE
Failed to install template

### ISSUE THREAD

**Issue by blakeblackshear** [logstash-plugins/logstash-output-elasticsearch#127]
I am using logstash 1.5 rc2 and I am having an issue where the elasticsearch template is not being created. Here is the log output:
```
Automatic template management enabled {:manage_template=>"true", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"348", :method=>"register", "plugin"=>"input/courier", "port"=>5000}
Using mapping template {:template=>{"logstash"=>{"aliases"=>{}, "mappings"=>{"_default_"=>{"properties"=>{"@version"=>{"type"=>"string", "index"=>"not_analyzed"}, "geoip"=>{"properties"=>{"location"=>{"type"=>"geo_point"}}, "type"=>"object", "dynamic"=>true}}, "_all"=>{"enabled"=>true, "omit_norms"=>true}, "dynamic_templates"=>#<Java::JavaUtil::ArrayList:0x68f84d1b>}}, "settings"=>{"index.refresh_interval"=>"5s"}, "template"=>"logstash-*", "order"=>0}}, :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"396", :method=>"get_template", "plugin"=>"input/courier", "port"=>5000}
Failed to install template: waited for [30s] {:level=>:error, :file=>"logstash/outputs/elasticsearch.rb", :line=>"352", :method=>"register", "plugin"=>"input/courier", "port"=>5000}
New Elasticsearch output {:cluster=>nil, :host=>["elasticsearch.service.ngd"], :port=>"9300-9305", :embedded=>false, :protocol=>"node", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"357", :method=>"register", "plugin"=>"input/courier", "port"=>5000}
Pipeline started {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"86", :method=>"run", "plugin"=>"input/courier", "port"=>5000}
```

Here is the config:
```
output {
  elasticsearch {
    host => "elasticsearch.service.ngd"
    bind_host => "10.0.90.130"
    template_overwrite => true
    template => "/etc/logstash/elasticsearch-template.json"
  }
}
```

**Comment by untergeek** [comment]
The `Failed to install template: waited for [30s]` is indicative of something more going on.

It seems that your output block can't connect to elasticsearch at all.  You did not specify a `cluster => "..."` directive, so Logstash would use `elasticsearch` as the cluster name by default.

Why are you using `bind_host`?  Do you have multiple IPs on this box?  Whatever else may be going on, Logstash's local Elasticsearch node can't talk to `elasticsearch.service.ngd` properly, hence the timeout.

**Comment by blakeblackshear** [comment]
I do see the logstash nodes in the cluster, and log data is being indexed.
The only thing missing is the template. Otherwise things work as expected
without errors in the logs.

**Comment by untergeek** [comment]
You should check the Elasticsearch logs then.  Logstash is trying to send it, but is unable.  This may be on the Elasticsearch end, since that's where the 30s timeout is coming from.

**Comment by blakeblackshear** [comment]
Is it sending the request over http to 9200?

**Comment by blakeblackshear** [comment]
I see nothing suspicious in the elasticsearch logs. I also simplified my config to this and still receive the same error:
```
input {
  stdin {}
}

output {
  elasticsearch {
    host => "elasticsearch.service.ngd"
    template_overwrite => true
    template => "/etc/logstash/elasticsearch-template.json"
  }
}
```

**Comment by untergeek** [comment]
So what happens if you switch and use `protocol => http`?

**Comment by blakeblackshear** [comment]
I pulled this down into vagrant to try and narrow it down. In AWS, I think I may have been blocking a needed port which caused the timeout. In vagrant, I still dont get the template, but I dont see the timeout error. Using `protocol => http` has the same effect. Documents are being added to the elasticsearch index, but no template is being created.

**Comment by blakeblackshear** [comment]
Turns out that I had an issue with the template file I was using. Not sure what the 30s timeout error was caused by, but rebuilding my environment seems to have removed the issue.

**Comment by jeffsilverm** [comment]
I had the same problem, and adding the protocol => http resolved it for me.

WASE-AM02017641:logstash silvj170$ logstash --version
logstash 1.5.4
WASE-AM02017641:logstash silvj170$ 

output {
  elasticsearch { 
    host => "obfustcated"
    port => 9203
    index => "cld-logstash=%{+YYYY.MM.DD}"
    protocol => http
 }
 stdout { codec => rubydebug }
}

**Comment by mishraak** [comment]
I found unsupported protocol exception in elasticsearch logs. adding protocol=>http to output block in logstash conf and restarting elasticsearch solved issue for me.

**Comment by sbarvick** [comment]
This is all about making a proper connection to ES.  The `Failed to install template: https: unknown error {:level=>:error}`  is a big clue and the documentation is not terribly clear.  e.g. why can't we use the https port yet the documentation says that you can (and then is it sending the password in the clear?).   The following notes in the output config ended up working for me.  

(in logstash-1.5.4)
output {
    elasticsearch {
        protocol => "http"
        host => ["http-hostname-only--not-url-not-https-and-no-port"]
        port => "9200"
        user => "username"
	password => "password"
        action => "index"
        flush_size => "500"
        index => "my-traffic-index"
    }
    stdout { }
}

Once you can establish a proper connection,  you won't have the template error or the eventual `Failed to flush outgoing items` after you 'send' your flush_size lines but can't flush them because they weren't really received.
