### ISSUE TITLE
Verify http and transport works through Amazon ELB

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#13]
I've gotten reports that `protocol => http` fails when pointed at an Amazon ELB. We should test and verify that it works. Should also verify that `protocol => transport` works in these situations.

Most especially, it's worth verifying behavior under misconfigured (by default, sometimes) load balancers that close idle connections or disable http 1.1 keep-alive.

References:
- https://github.com/elasticsearch/logstash/issues/2060

**Comment by xelibrion** [comment]
Hey guys, it seems logstash stops sending logs to ES cluster using `protocol => transport` after ELB recycles IP addresses with sniffing disabled - looks like SimpleNodeSampler simply removes a node from the list, without trying to re-resolve DNS name.

**Comment by colinsurprenant** [comment]
older issues followup: is this still a valid issue? /cc @andrewvc

**Comment by jordansissel** [comment]
Transport client is no longer supported.

HTTP seems to work fine lately. I'm closing this.
