### ISSUE TITLE
Elasticsearch Output Drop Events Sent to Closed Index

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#134]
(This issue was originally filed by @detoor at https://github.com/elastic/logstash/issues/1937)

---

In our use case of logstash we have two outputs, Flume (long term archive), ES (short term search).  Occasionally old data is processed and logstash will attempt to write it to a closed index in ES.  This appears to eventually lead to logstash failing to write to either output (even for current/new data) as logstash continually attempts to write the old data to the closed index.

```
output {
    tcp {
        host => "FLUMEHOST"
        port => 4242
        mode => "client"
        codec => "json_lines"       
    }

    elasticsearch {
    host => "ESHOST"
    node_name => "LogstashMaster-one"
    cluster => "clustername"
    index_type => "%{logType}"
    }
}
```

One possible work-around/fix might be to expose the "ignore_unavailable" ES flag to the logstash elasticsearch output.

**Comment by camarasingham** [comment]
Hi Jordansissel, has this bug been resolved?

**Comment by jrbeilke** [comment]
+1 just got bit by this bug recently when we setup Curator to auto-close old indices but Logstash was still processing events from that time period

**Comment by tomsommer** [comment]
+1

**Comment by jordansissel** [comment]
Logstash should be DLQing any 404 doc responses. What version of the Elasticsearch output plugin are you using? (`bin/logstash-plugin list --verbose` will show you)

**Comment by HitkoDev** [comment]
@jordansissel Index_closed_exception is 403

**Comment by jordansissel** [comment]
Ahh indeed. I was confusing automatic index creation failures (404) with index closed.

The code doesn't specifically highlight a 403 document response code, which means it will retry it indefinitely (not drop).

I tested with a fresh install of Logstash 5.6.0, and I see it retry:

```
% curl -XPOST localhost:9200/foo/_close
...
% bin/logstash -e 'output { elasticsearch { index => "foo" } }'
...
[2017-09-13T08:34:31,088][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 403 ({"type"=>"index_closed_exception", "reason"=>"closed", "index_uuid"=>"4w5V0HMXQreYpe-5Ow8Rqg", "index"=>"foo"})
[2017-09-13T08:34:31,097][INFO ][logstash.outputs.elasticsearch] Retrying individual bulk actions that failed or were rejected by the previous bulk request. {:count=>1}
```

I cannot reproduce the "drop" in Logstash 5.6. Please advise on what version of Logstash you are using, and I recommend you upgrade to 5.6.0 if it is not this version.

**Comment by jordansissel** [comment]
At this time, I am unable to reproduce the reported problem (dropping events sent to a closed index). If you experience this, please open a new issue w/ details including the Logstash version and your elasticsearch output configuration.

**Comment by tomsommer** [comment]
Wasn't the problem the fact that it retries indefinitely? Or did I miss something?

**Comment by HitkoDev** [comment]
@jordansissel that's not the problem.

Logstash will retry sending packages to closed indices, which eventually blocks the output pipe and prevents other packages from being written.

**Comment by hraab** [comment]
Why is this issue closed? As others said, the problem is not that events got droppped. The problem is that events will block LS output after a while.

**Comment by jsvd** [comment]
@hraab historically we have gone back and forth between preferring that the pipeline flows vs preventing data loss and we have settled on the latter.

I see no reason to consciously write data to closed indices so we can assume it's a mistake and we opt to retry vs drop the data.

It's outside of the scope of this issue, but this plugin could have an option like `:drop_on => []` allowing people to list response codes they wish to drop. It would always be empty by default, however.

**Comment by hraab** [comment]
Thanks for the fast reply!

There's obviously no reason to write data to closed indices. :) But that can happen if indices have been closed by Curator but according log events for that days(s) comes in later (for whatever reason). 

I'd prefer an option to DLQ events which cause 403.

**Comment by jsvd** [comment]
> I'd prefer an option to DLQ events which cause 403.

for that I should point you to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/697 where it has been/was discussed
