### ISSUE TITLE
Store encrypted ES password in config file or allow prompt

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#143]
(This issue was originally filed by @sherry-ger at https://github.com/elastic/logstash/issues/3140)

---

The password for ES user is stored in plain text in the Logstash config file, which is not secure.  It would be better if the password is masked or encrypted in the config file.  Or prompt for the password at Logstash startup.

**Comment by blysik** [comment]
How about allowing logstash to reference environment variables in config files?

Then you could just have something like

password => ENV['ES_PW']

**Comment by jordansissel** [comment]
@blysik I don't think environment variables add any security that files don't already have. Do they?

**Comment by blysik** [comment]
Environment variables are a common way to separate config files and secrets.  Config files are checked into source control and deployed via configuration management.  Environment variables are deployed separately by other means.

"Other means" is vague, but it depends on the company and tools used.  In a Heroku-like environment, environment variables would be set in a web UI separate from your application config files.

**Comment by imadulhaque** [comment]
logstash and elastic search provide what we need, but providing plain text password in config file will turn down the option of using ES+logstash down in our company. are there any updates on this?

**Comment by mohantnr** [comment]
Hi,
is there any update on encrypting password in logstash.

echo above  comment

**Comment by jordansissel** [comment]
No updates at this time.

"Encrypt passwords" is very vague. Can you suggest a specific set of
requirements and describe your threat models so we can discuss addressing
them?

**Comment by andrewvc** [comment]
I think we should decide that there isn't much 'there' here and close this issue. #450 makes logging of passwords by accident near impossible. 

In my opinion the FS layer is the right place to be doing this.

**Comment by aciokler** [comment]
We really need this feature. Any updates?

**Comment by jordansissel** [comment]
Tracking this here: https://github.com/elastic/logstash/issues/6892

Closing this ticket. Please watch https://github.com/elastic/logstash/issues/6892 for news.
