### ISSUE TITLE
Wrong error: "Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above."

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#147]
(This issue was originally filed by @lathspell at https://github.com/elastic/logstash/issues/2056)

---

After installing logstash=1.4.2-1-2c0f5a1 I started logstash-web but did not notice that logstash itself was not running. When pointing my browser to the web interface, it just gave me the error:

    Upgrade Required Your version of Elasticsearch is too old. Kibana requires Elasticsearch 0.90.9 or above.

This is wrong, I installed the Logstash Debian package which bundles Elasticsearch 1.1.1. As a newbie was puzzled and removed / downloaded / reinstalled the package several times until I noticed that there was a second error message:

    Error Could not reach http://localhost:9200/_nodes. If you are using a proxy, ensure it is configured correctly

Maybe this could be improved so that it says "... If you use the bundled Elasticsearch, make sure the logstash agent daemon is running, if you use a dedicated Elasticsearch daemon, check if is in version 0.90.9 or higher!"

**Comment by andrewvc** [comment]
@jordansissel isn't logstash web dead? Can we close this?

**Comment by suyograo** [comment]
+1

**Comment by jordansissel** [comment]
logstash web (which was kibana in Logstash 1.3) is gone. +1 to close.
