### ISSUE TITLE
No events pushed to ES (1.5.0.rc2 ->1.5.0.rc3)

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#148]
(This issue was originally filed by @svenmueller at https://github.com/elastic/logstash/issues/3164)

---

After upgrading to RC3 (from RC2), events are only pushed to ES for a couple of seconds after starting logstash service (can be seen in Kibana). After a couple of seconds, ES/Kibana doesn't show any incoming events anymore. Logstash service is running properly and the log files don't give any hint. 

The configuration/settings are already provided here: https://github.com/elastic/logstash/issues/3003

**Comment by andrewvc** [comment]
This issue seems dead and is probably no longer correct. Mind if I close it @jordansissel ?
