### ISSUE TITLE
RFC: Change the default protocol to http

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#150]
The current protocol is `node`. This means Logstash joins the cluster. The cons of this `node` default are:

* bidirectional communication must be possible between Logstash and the _entire_ cluster.
* Logstash's NodeClient can serve as a client node and answer search queries. Probably not expected.
* Shield users cannot use NodeClient, anyway, without granting Logstash full access to the cluster as a member of the cluster (full privileges)
* The default NodeClient uses multicast for discovery, and some operating systems (like CentOS, I think?) and networks (like AWS EC2's network) block this by default.
* Exceptions in Elasticsearch are serialized over the network using the standard Java Serializable. In our experience, Java's Serializable isn't stable across different JVM versions (exceptions will fail to deserialize).

Changing to HTTP as the default would make it:
* easier to integrate with Shield
* easier to debug (http is simpler than the transport protocol, probably)
* independent of Elasticsearch ABI (transport serialization)
* independent of JVM version
* Logstash release could be shipped _without_ the Elasticsearch libraries (saves 10-20mb)

Downsides:
* We'd want to have a default `host` setting, `localhost` is probably OK.
* We need discovery and sniffing enabled in the http protocol also.

**Comment by jordansissel** [comment]
Also open for discussion is to change the default protocol to `transport` instead, but I think the `transport` protocol has similar problems as `node` does (exception serialization, etc).

**Comment by talevy** [comment]
+1 for `default => http`

**Comment by suyograo** [comment]
My vote for `default=>http` as well. This eliminates any jar issues or potential version compatibility issues. We don't have to ship with ES jars then and add an extra plugin to enable transport functionality

**Comment by jordansissel** [comment]
@suyograo Oh yeah! I forgot about the jars. We can make that a mixin plugin and shrink the Logstash default release by many megs! I'll update the "benefits"

**Comment by talevy** [comment]
related to that point about the jars: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/122

**Comment by jordansissel** [comment]
Being that this is a backwards incompatible change, I'd like to have a detailed upgrade process (and expectation setting) for existing users before we ship this change.

**Comment by andrewvc** [comment]
Doing some benchmarking here, it is currently the case that the HTTP protocol runs at the same speed or faster. On my quad core MBP with a local ES instance I ran a series of tests with an input of `input { generator { lines => [ "foo", "bar", "baz" ] } }` and various `output` settings. No filters were enabled. With one worker the HTTP output and node outputs were almost exactly the same in terms of throughput. With workers == 3 HTTP got a significant boost (~20%) and the node output got slower, probably because it doesn't use connection sharing. While this could be fixed the single threaded results aren't encourage in terms of that actually working better.

Results below:

```
These tests were run by starting the processing pipeline then issuing a command like 'curl http://localhost:9200/_cat/nodes; curl -XDELETE 'http://localhost:9200/node_ls_test'; sleep 30; curl 'http://localhost:9200/node_ls_test/_search?search_type=count&pretty' . Running the test this way removes startup time as a factor.

# Node Protocol * 3 Workers
command: bin/logstash -e 'input { generator { lines => [ "foo", "bar", "baz" ] } } output { elasticsearch {  protocol => node   index => node_ls_test  workers => 3 cluster => avc_cluster host => "127.0.0.1:9300" } }'
hits: 519717

# HTTP Protocol * 3 Workers
command: bin/logstash -e 'input { generator { lines => [ "foo", "bar", "baz" ] } } output { elasticsearch {  protocol => http  index => http_ls_test  workers => 3 } }'
hits: 732628,

# Node Protocol * 1 Workers
command:  bin/logstash -e 'input { generator { lines => [ "foo", "bar", "baz" ] } } output { elasticsearch {  protocol => node bind_port => 9303  index => node_ls_test cluster => avc_cluster host => "127.0.0.1:9300" } }'

# HTTP Protocol * 1 Workers
```

**Comment by andrewvc** [comment]
Per a discussion with @suyograo we'll likely be moving out support for the node and transport protocols from this gem. They're a source of user confusion and don't offer much in terms of performance improvements or reliability in the real world. In fact, they seem to cause more trouble than they're worth (esp. if you mix jar versions between the client and the cluster).

Given that our strategy will be to: 
1. Remove all node/transport functionality from this gem (WIP here: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/216)
2. Move the current contents of this gem to a new logstash-output-elasticsearch-native plugin and release that.

**Comment by suyograo** [comment]
@andrewvc :+1:

**Comment by andrewvc** [comment]
This has been done in master!
