### ISSUE TITLE
Unable to use variable for index

### ISSUE THREAD

**Issue by naisanza** [logstash-plugins/logstash-output-elasticsearch#154]
I'm running Logstash 1.5.0 on Ubuntu 14.10 and if I use the documented variable for creating the index name, I am faced with errors. Two of the errors are listed below

Using this output causes failures and errors. Using a string, such as 'indextext' does not cause errors.

```
output {
    if [type] == "IndexTest" {
    elasticsearch {
        index => "%{+YYYY.MM.dd}"
    }
    }
}
```

Logstash debug errors

```
retrying failed action with response code: 429 {:level=>:warn}
```

```
{:timestamp=>"2015-05-21T22:17:34.364000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>142, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:464:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1507:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn, :file=>"stud/buffer.rb", :line=>"231", :method=>"buffer_flush"}
```

**Comment by talevy** [comment]
This is a known issue and will be resolved in the next release of the `logstash-output-elasticsearch` plugin to version `0.2.5`.

once published, an ol'
```
bin/plugin update logstash-output-elasticsearch # update 0.2.4 -> 0.2.5
```
should do the trick. 

I'll update this thread when it is released. changes are on master, just blocked on a few things 
before we can publish. should happen by tomorrow. I apologize for the inconvenience. There is an issue with certain expectations within the error's log message itself. If you choose to switch to `protocol => http`, this should resolve that issue.

**Comment by naisanza** [comment]
@talevy thank you!

**Comment by talevy** [comment]
@naisanza pushed new version now. you can go ahead and try and update!

let me know how it goes after that!

**Comment by andrewvc** [comment]
This seems to be resolved.
