### ISSUE TITLE
Logstash should handle when the index name violates ES index naming convention

### ISSUE THREAD

**Issue by joshuar** [logstash-plugins/logstash-output-elasticsearch#156]
Currently, Elasticsearch has restrictions on index names in that they can only contain lowercase alphabetical characters, cannot begin with an underscore, and cannot contain commas.

In v1.5.2, if the Elasticsearch output defines an index name that violates any of the conditions above, the pipeline still runs, but the user gets a bunch of cryptic bulk request failures:

```
failed action with response of 400, dropping action: <bulk request details...>
```

Meanwhile, ES threw a `org.elasticsearch.indices.InvalidIndexNameException` that isn't visible to the end-user of Logstash.  It might be good to expose this exception or throw a similar error in Logstash so the user knows exactly what's happened or even do some syntax checking on the index name before sending an event through this output.

Just a note, the behaviour appears even worse in v1.4.2, no bulk errors are thrown (or if they are, they aren't visible), the ES exception occurs but for a user watching LS, it looks as though the output worked unless you go and check ES.

This appears to be at least the problem for #144 and possibly other issues where a user is using a variable substitution in the index name where that substitution could violate the ES naming conventions.

**Comment by joshuar** [comment]
Here is a quick config that can verify the problem:

```
input {
    stdin { }
}

output {
    stdout {
        codec => "rubydebug"
    }
    elasticsearch {
        host => "localhost"
        index => "ImABadBoy"
    }
}
```

For 1.5.0, you'll get the rejected bulk request and the stdout result.  For 1.4.2, you'll get just the stdout result, no bulk request error. Check your ES log to see the invalid index exception in both cases.

**Comment by andrewvc** [comment]
Thanks for the report, apologies for the delay! These error messages have been greatly improved in the latest versions of this output, especially when the debug level is set to info.

If you have further wishes for improvement please open a new issue.
