### ISSUE TITLE
Integration test: Poison message in a batch should drop only that message and not entire batch

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#158]
We need a test to confirm this behavior: https://github.com/elastic/logstash/issues/3283

**Comment by jsvd** [comment]
we already have tests for the different per-document response codes https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/fc2dfd5fd8a6006d1983818e16f21705fca9fb09/spec/integration/outputs/retry_spec.rb#L126

closing
