### ISSUE TITLE
Node Protocol Client does not support update requests

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#16]
Currently, the node client does not handle `update` requests

link to file location: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/bedbba9f7ffc012afc5e1cc04b716f5815e67a69/lib/logstash/outputs/elasticsearch/protocol.rb#L204

**Comment by jverelst** [comment]
+1 on this, because we would like to be able to update documents in ElasticSearch with extra data through logstash

**Comment by Da-Wei** [comment]
I am unable to use "update" action with http protocol :
Got error to send bulk of actions to elasticsearch server at 172.17.0.11 : [400] {"error":"ActionRequestValidationException[Validation Failed: 1: script or doc is missing;2: script or doc is missing;]","status":400} {:level=>:error}

But with this pull request https://github.com/elastic/logstash/pull/1581, "update" and "upsert" works. 
I only test http protocol part of this patch on v1.5.0rc2 distribution but code for "node" protocol is present.

**Comment by talevy** [comment]
closed by: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/116
