### ISSUE TITLE
Add back option to disable_verify for ssl usecase

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#160]
We used to have an option to disable verification of SSL certificate called `disable_verify` and it was removed because that defeats the purpose of having security enabled. I agree in general, but this may help quick POCs and development setups so I am wondering if we can discuss this option here. 

I know we should not be exposing a half solution for security, but maybe call it `ssl_verify_will_disable_security` or something explicit to warn users. Any feedback?

**Comment by scholarj** [comment]
I'd like to add that all HTTPs clients I know of not only have an option to disable cert verification but apparently it's so commonly requested that it's often front and center in the documentation - not some obscure setting you have to hunt for. Ex: web browsers give a stern warning but most have a link right in the warning for continuing and adding an exception for the given host.

IMO the option should be presented to the user for a decision not made for them. I could see making the case that you cannot trust an average web browser user to make a good decision when faced with the overhead of adding a CA cert to their configuration. But certainly a logstash administrator is qualified to make such a decision for their deployment/testing.

**Comment by kevinkluge** [comment]
I like the idea of being able to disable.  But the default should be enabled.  We should push people to a secure config.

Another personal preference -- make the config name include "enable".  Otherwise, with "...disable...", you get double negatives and people have to think too much.

**Comment by jordansissel** [comment]
@kevinkluge +1 on avoiding double negatives. We can also try to standardize the setting's name across all plugins that use SSL and also support destroying trust of SSL.

**Comment by jordansissel** [comment]
My rough proposal is:
* A simple-named setting `ssl_certificate_verification => false` or something
* A warning emitted to users that this setting disables trust and makes SSL insecure

**Comment by suyograo** [comment]
@jordansissel +1 for `ssl_certificate_verification`

**Comment by suyograo** [comment]
Fixed in #167
