### ISSUE TITLE
flush operation can lead to OOM due to huge memory overhead 

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#164]
When it's time for a flush (by either reaching flush_size, flush_interval or teardown) the memory cost of setting up the bulk operation can lead to OOM.

For example, using the following config:

`input { stdin { } } output { elasticsearch { protocol => "http" host => "127.0.0.1" flush_size => 10000 index => "ugh" } }`

And piping in 300.000 messages of 200-400 bytes each will cause logstash to crash:

```
Logstash startup completed
Exception in thread ">output" java.lang.UnsupportedOperationException
    at java.lang.Thread.stop(Thread.java:869)
    at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
    at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
    at java.lang.Thread.run(Thread.java:745)
```

NOTE: logstash 1.4.2 was able to terminate the task under the same conditions.

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497

**Comment by andrewvc** [comment]
#497 mitigates this, which is why I'll mark this as resolved. There is no perfect way to prevent OOMs in Java.
