### ISSUE TITLE
Make logstash-output-elasticsearch timeout configurable

### ISSUE THREAD

**Issue by sherry-ger** [logstash-plugins/logstash-output-elasticsearch#166]
This is a follow up to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/103.  Add a configurable timeout to the ES output.

Reason: if there were occasional network "hiccups", it would result in hard TCP connection drops (connection reset by peer) which can take up to 2 hours to result. This renders the HTTP client (in this case logstash) needlessly idle and exposes the user to data latency issues.  It would be easier for the user to handle the issue if there were a resulting timeout.

**Comment by suraj-kamath** [comment]
I am looking for such a specific need where in I can configure a timeout . 
The use of "*_timeout" fields threw an error , stating undefined fields. 
How can i do this ?

**Comment by suraj-kamath** [comment]
More updates this is the error/warning that i keep getting intermittently over the console, when run in debug mode :

![client protocol exception for logstash jira](https://cloud.githubusercontent.com/assets/12824518/10276838/c540b578-6b6f-11e5-939f-dcc8db0ae8da.jpg)

@logstash-dev's / @suyograo can you please provide any directions on this ?

**Comment by jsvd** [comment]
timeout has been configurable now for quite some time, for example in 7.3.5: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v7.3.5/lib/logstash/outputs/elasticsearch.rb#L184-L186
