### ISSUE TITLE
feauture request. Configurable path for HTTP protocol

### ISSUE THREAD

**Issue by ewaza** [logstash-plugins/logstash-output-elasticsearch#168]
In my environment I'm required to have logstash connect to ES via a reverse HTTP proxy which is not mounted on the root URL.

I'm able to get what i want in a hacky way because of lib/logstash/outputs/elasticsearch/protocol.rb line 64 and the fact that 'port' is a string
```
uri = "#{options[:protocol]}://#{options[:host]}:#{options[:port]}"
````
In my config I can say:
```
output { elasticsearch { 
  host => "my_host" 
  protocol => 'http'
  port => "443/my-path/"
  ssl => true		  
}}
```
As far as I can see there is currently no other way to achieve this. It would be nice if this becomes an official supported feature. If you like I can provide the patch, but I'm afraid I don't have the time to do so anytime soon. For someone who is already familiar with the Logstash plugin architecture it should be a piece of cake.

**Comment by andrewvc** [comment]
Just released as 0.2.9
