### ISSUE TITLE
Seeing "The target server failed to respond" INFO-level log messages when sending over HTTP

### ISSUE THREAD

**Issue by aaw** [logstash-plugins/logstash-output-elasticsearch#169]
I'm testing Logstash 1.5.0 locally against an Elasticsearch setup with basic auth, so the config for my elasticsearch output looks something like:

```
elasticsearch { protocol => 'http' host => 'X.X.X.X', port => 49153, user => 'me' password => 'XXXX' }
```

When I run Logstash with this config, everything works but I see the following messages repeatedly in the logs (these are debug logs for context, but the lower-level INFO logs from org.apache.http show up when running without --debug):

```
Sending bulk of actions to client[0]: X.X.X.X {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"461", :method=>"flush"}
Jun 09, 2015 6:46:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://X.X.X.X:49153: The target server failed to respond
Jun 09, 2015 6:46:47 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://X.X.X.X:49153
Shifting current elasticsearch client {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"468", :method=>"flush"}
Switched current elasticsearch client to #0 at X.X.X.X {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"518", :method=>"shift_client"}
```

I don't see these retries every time Logstash sends messages, more like every other time when testing. Elasticsearch is only returning 200's for any requests from Logstash and I've verified that all of my messages are actually making it to Elasticsearch, so there doesn't seem to be any real error occurring here.

Do I have something configured incorrectly that's causing bad connections to stay in the pool and be retried when they shouldn't? Otherwise, if this indeed is just a spurious warning, is there any way to silence it in my Logstash logs?

**Comment by aaw** [comment]
For anyone else reading this who wants to suppress this logging (since you seem to get a few info-level messages per bulk send to Elasticsearch) here's how I worked around it:

* In a logstash-1.5.0 installation, add log4j-1.2.17.jar to the runtime jars. It already exists as a dependency of other plugins, so after you do a `bin/plugin install` you should be able to copy it, for example, like this:

```
$ cp vendor/bundle/jruby/1.9/gems/jruby-kafka-1.4.0-java/lib/log4j/log4j/1.2.17/log4j-1.2.17.jar vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/vendor/jar-dependencies/runtime-jars/
```

* Create a `log4j.properties` file to override the log settings. Mine looks like:

```
log4j.rootLogger=INFO, stdout
log4j.logger.org.apache.http=WARN  # Turn off verbose INFO-level HTTP client logging for retries
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```

* Use the `LS_JAVA_OPTS` environment variable to point logstash to your `log4j.properties` file. You can do this by executing the following in a shell before running logstash:
```
export LS_JAVA_OPTS="-Dlog4j.configuration=file:/full/path/to/your/log4j.properties"
```

I'd still be interested to hear whether these retries are expected or it's some bug in the client pooling and also whether there's an easier way to disable these log messages.

**Comment by splashx** [comment]
I get these messages if I increase my workers number (from 5 to 30 for example). 
Like you are experiencing, my data is still sent and I can find everything is indexed.
Via Bigdesk I can see there are 30 HTTP channels, so I the workers manage to connect after all.

**Comment by pickypg** [comment]
This appears to be related to #85.

**Comment by andrewvc** [comment]
Apologies for the delay. This seems to be an issue with overloading the ES instances. I'm going to close this based on that. If you are having continuing issues please open a new issue or ask a question on https://discuss.elastic.co/c/logstash

We also now have better logging and connection handling that should remove this issue for most people.
