### ISSUE TITLE
Configuration option "host" is inconsistent with elasticsearch input "hosts" option.

### ISSUE THREAD

**Issue by joshuar** [logstash-plugins/logstash-output-elasticsearch#172]
It looks like the elasticsearch output plugin uses [`host`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-host) while the elasticsearch input plugin uses [`hosts`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elasticsearch.html#plugins-inputs-elasticsearch-hosts).  Both options essentially do the same thing in the respective plugins.  It would be nice if the name was consistent in both plugins.

**Comment by andrewvc** [comment]
This has been fixed in master, and will be released with LS2.0 :) Thanks for filing the issue @joshuar !
