### ISSUE TITLE
Change the default bulk size to 500 instead of 5000 documents

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#181]
The index request bulk size (`:flush_size`) is by default set to 5000. That is really high for a default because we have no idea about the individual sizes of the document. This could potentially lead to unnecessary memory pressure if the documents are big (in bytes). Its better to be conservative here and lower the default to 500. Based on the size of the documents being indexed, users can always change it in the config.

Also, we should expose a `flush_size_bytes` for doing a bulk request -- thats a better measure than # of documents

**Comment by andrewvc** [comment]
This has been fixed in master already! I will open a separate issue for `flush_size_bytes`, which is a separate design issue.
