### ISSUE TITLE
Sniffing support for http protocol

### ISSUE THREAD

**Issue by jimmyjones2** [logstash-plugins/logstash-output-elasticsearch#182]
I've seen this is already part of #150, but regardless, it would be really good to have sniffing support for http to match the transport protocol (#27)

**Comment by suyograo** [comment]
`elasticsearch-ruby` client that we use already has this support to sniff or load nodes automatically and we should be able to use this feature. 
Ref: http://www.rubydoc.info/gems/elasticsearch-transport#Reloading_Hosts

**Comment by andrewvc** [comment]
It looks like sniffing is not working at present based on my browsing of https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb . I think we need to call `reload_connections!` instead of setting `client_settings["client.transport.sniff"] = @sniffing` which we do now. 

@karmi does that sound right?

**Comment by karmi** [comment]
@andrewvc As @suyograo suggested, `reload_connections` is the nomenclature in the Ruby client (either in configuration Hash or via method call)

**Comment by andrewvc** [comment]
While there is some support now in the ruby client, but it works on a one time basis IIRC. I'm not sure if the transport protocol polls the cluster to sniff for new nodes / prune old ones, but we'll probably have to invoke the sniffing periodically ourselves.

@karmi I think it may make sense to add this to the ruby client given the dynamic nature of an ES cluster. Are there any existing plans to add this to the ruby client? If not, would you accept a patch around this?

**Comment by karmi** [comment]
@andrewvc Sorry, not following “add this to the ruby client given the dynamic nature of an ES cluster”. What should be added? (The reloading is done on [every N-th request](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#reloading-hosts), and is disabled by default.)

**Comment by andrewvc** [comment]
@karmi ah, I missed that in the source code. Perfect!

**Comment by andrewvc** [comment]
This has already been added in master! It will be released with logstash 2.0 :)
