### ISSUE TITLE
[refactor] Push the retrying on network failures to elasticsearch-ruby

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#183]
Investigate if we can reuse the retry feature of `elasticsearch-ruby` client which [retries](http://www.rubydoc.info/gems/elasticsearch-transport#Randomizing_Hosts) a failed request on a different host. Today we implement that feature using [`::shift_client`](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L583) method, but it will be nice to reuse existing code

I am not referring to the retry rules we have on `503`,`429` http codes, which _can_ be pushed down to elasticsearch-ruby, but thats a different discussion

**Comment by jsvd** [comment]
we don't use elasticsearch-ruby any more
