### ISSUE TITLE
Does document_id overwrite the entire entry, or only fields that exist from the filter and leave other fields alone?

### ISSUE THREAD

**Issue by naisanza** [logstash-plugins/logstash-output-elasticsearch#186]
I'm wondering if using document_id will replace the entire entry that matches the _id, or only "update" the entry; and leaves all other fields alone. 

For example, if `_id: "33dd"` exists in the index with the fields `a` `b` `c`, and on my second run I have a filter with fields for `c` `d` `e`. Will the resulting entry become: `abcde` with `c` "updated" and `de` added. Or, will it become `cde`?

**Comment by andrewvc** [comment]
@naisanza it will replace the entire thing. In the future please post questions to https://discuss.elastic.co/c/logstash , the github issues are for bug reports / feature suggestions.
