### ISSUE TITLE
Documentation misleading for 'host' setting

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#187]
The 'host' setting often gives examples as 'host:port' like `127.0.0.1:9200` and implies to the user that 'host:port' combinations work. In practice, this doesn't seem to work, so either we should make it work or we should remove the misleading informatino.

**Comment by untergeek** [comment]
But I thought we _do_ allow host:port now.  Unless we rolled back the configuration modification, I thought we allowed multiple hosts for http round-robining, which required host:port annotation.  Also, doing node protocol with multiple "discovery" hosts also seemed to require this.

**Comment by jordansissel** [comment]
Not sure; a user on IRC was reporting that host:port did not work for either http and transport

**Comment by untergeek** [comment]
Hmm.  We should verify which version he was using, and do some tests.

**Comment by andrewvc** [comment]
just confirmed this is working on the HTTP output

**Comment by suyograo** [comment]
Thanks @andrewvc.
