### ISSUE TITLE
[Tests] Allow running integration tests against pre-existing elasticsearch instance

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#190]
During the migration to Docker, the ability to run integration tests against a local elasticsearch 
instance was lost. This ticket is to ensure that is fixed!

Some possible solutions would be to use environment variable flags

I think, by default, tests should expect a locally running elasticsearch on `localhost:9200/9300`

some possible flags to set (not sure which is best):
```
DOCKER=1 # run default container and use elasticsearch running inside
ES_HOST=localhost ES_HTTP_PORT=9200 ES_NODE_PORT=9300 # use this info as connection info for existing elasticsearch instance
```

**Comment by andrewvc** [comment]
This has already been fixed, and is the default now!
