### ISSUE TITLE
[Test] re-enable testing of node protocol where suited

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#193]
locations:

* https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/spec/integration/outputs/templates_spec.rb#L4
* https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/spec/integration/outputs/retry_spec.rb#L20

**Comment by andrewvc** [comment]
Moved to https://github.com/logstash-plugins/logstash-output-elasticsearch_java/issues/21
