### ISSUE TITLE
plugin isn't recongnized after an update

### ISSUE THREAD

**Issue by OuesFa** [logstash-plugins/logstash-output-elasticsearch#202]
Hi,
LS 1.5.0.rc2-1
An issue occured after updating a plugin.
Updated logstash-output-elasticsearch 0.1.18 to 1.0.3

When i start logstash, i've this messsage: 
*:message=>"The error reported is: \n  Couldn't find any output plugin named 'elasticsearch'. Are you sure this is correct? Trying to load the elasticsearch output plugin resulted in this error: undefined method `load_runtime_jars!' for LogStash::Environment:Module"}*

Need your help please, i tried to reinstall  the plugin, it doesn't work.

**Comment by suyograo** [comment]
@OuesFa i don't think you should be using LS 1.5.0.rc2-1. Please upgrade to 1.5.2 and check this?

**Comment by OuesFa** [comment]
Thanks for your quick reply, i try to upgrade.

**Comment by suyograo** [comment]
ok, will close this now. Please reopen if this does not work!
