### ISSUE TITLE
Logstash 1.5.2 - Some messages are not pushed to ES - 

### ISSUE THREAD

**Issue by mailsanjayyadav** [logstash-plugins/logstash-output-elasticsearch#206]
Hi,

I am trying to push data from my rabbitmq into elasticsearch via logstash. My rabbitmq is producing around 500 msg/sec. I can see some data indexed in Elasticsearch. But logstash is throwing following error for some cases and these records are not present in elasticsearch nodes - 

{:timestamp=>"2015-07-18T12:06:36.406000+0530", :message=>"failed action with response of 400, dropping action: [\"index\", {:_id=>nil, :_index=>\"inventory-2015.07.18\", :_type=>\"inventorylog\", :_routing=>nil}, #<LogStash::Event:0x5be10b77 @metadata={\"retry_count\"=>0}, @accessors=#<LogStash::Util::Accessors:0xd04a904 @store={\"comments\"=>\"entryexit\", \"operation\"=>\"DCR_BOC\", \"quantity\"=>1, \"sellerId\"=>1, \"shipmentId\"=>\",87527916\", \"skuId\"=>4012046, \"storeId\"=>1, \"supplyType\"=>\"ON_HAND\", \"timeStamp\"=>\"2015-07-18T12:06:35.805+05:30\", \"warehouseIds\"=>\"28,36\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-07-18T06:36:35.813Z\", \"type\"=>\"inventorylog\"}, @lut={\"type\"=>[{\"comments\"=>\"entryexit\", \"operation\"=>\"DCR_BOC\", \"quantity\"=>1, \"sellerId\"=>1, \"shipmentId\"=>\",87527916\", \"skuId\"=>4012046, \"storeId\"=>1, \"supplyType\"=>\"ON_HAND\", \"timeStamp\"=>\"2015-07-18T12:06:35.805+05:30\", \"warehouseIds\"=>\"28,36\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-07-18T06:36:35.813Z\", \"type\"=>\"inventorylog\"}, \"type\"], \"[type]\"=>[{\"comments\"=>\"entryexit\", \"operation\"=>\"DCR_BOC\", \"quantity\"=>1, \"sellerId\"=>1, \"shipmentId\"=>\",87527916\", \"skuId\"=>4012046, \"storeId\"=>1, \"supplyType\"=>\"ON_HAND\", \"timeStamp\"=>\"2015-07-18T12:06:35.805+05:30\", \"warehouseIds\"=>\"28,36\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-07-18T06:36:35.813Z\", \"type\"=>\"inventorylog\"}, \"type\"]}>, @data={\"comments\"=>\"entryexit\", \"operation\"=>\"DCR_BOC\", \"quantity\"=>1, \"sellerId\"=>1, \"shipmentId\"=>\",87527916\", \"skuId\"=>4012046, \"storeId\"=>1, \"supplyType\"=>\"ON_HAND\", \"timeStamp\"=>\"2015-07-18T12:06:35.805+05:30\", \"warehouseIds\"=>\"28,36\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-07-18T06:36:35.813Z\", \"type\"=>\"inventorylog\"}, @metadata_accessors=#<LogStash::Util::Accessors:0x487c7111 @store={\"retry_count\"=>0}, @lut={}>, @cancelled=false>]", :level=>:warn, :file=>"logstash/outputs/elasticsearch.rb", :line=>"517", :method=>"submit"}

Here is my config - 
input {
 rabbitmq {
   codec => "json"
   type => "inventorylog"
   host => "erp"
   prefetch_count => 500
   queue => "inv_events_key"
   durable => true
 }
}

output {
 if [type] == "inventorylog" {
   elasticsearch {
     protocol => "http"
     host => "erp"
     port => 9200
     cluster => "erp"
     codec => "json"
     flush_size => 5000
     idle_flush_time => 10
     index => "inventory-%{+YYYY.MM.dd}"
   }
 }
}

**Comment by andrewvc** [comment]
Apologies for the delay, but this is not a bug report but a question. Questions should be asked on discuss.elastic.co/c/logstash .
