### ISSUE TITLE
Failed to query elasticsearch for previous event

### ISSUE THREAD

**Issue by ganesh2303** [logstash-plugins/logstash-output-elasticsearch#207]
I'm using new elasticsearch 1.6.0, i'm facing certain issue while making correlation in elasticsearch filter. In the query field in elasticsearch i'm just comparing the two field from one type field to another type field. when i run the logstash first time correlation gets failed and it thrown the error "Failed to query elasticsearch for previous event". After that i'm just deleting the ".log-courier" without deleting index again the run the logcourier in this scenario logstash gets correlated. Really i'm clueless why it doesn't happen in the first time.Kindly give me your valuable suggestion for this....

![elasticsearch](https://cloud.githubusercontent.com/assets/1695045/8771862/0d288640-2e7b-11e5-86c8-91325bce501e.png)

**Comment by andrewvc** [comment]
Can you please report this issue against https://github.com/logstash-plugins/logstash-filter-elasticsearch , this repo is for the output. Additionally, please paste the full error as text, not a screenshot. Your screenshot is cut-off and missing vital information.
