### ISSUE TITLE
Use LS json serialization framework in es-ruby client library

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#208]
This output uses `es-ruby` client which internally uses `multi_json` module for serializing bulk requests. Since we have a json wrapper in `Logstash::Json` (https://github.com/elastic/logstash/blob/master/lib/logstash/json.rb) we should plug this to the underlying es-ruby client lib for serialization

**Comment by colinsurprenant** [comment]
we should prioritize this so we benefit all the upcoming json serialization improvements in logstash.

**Comment by andrewvc** [comment]
No longer relevant. We now use our own client.
