### ISSUE TITLE
Better User Experience When Elasticsearch is Down

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#219]
Currently if elasticsearch dies weird errors can occur. We should perform some sort of sniffing to check if ES is up, and report it ASAP to the user in a very noticeable way. This was moved from this thread: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/141#issuecomment-127418528

**Comment by talevy** [comment]
++

**Comment by andrewvc** [comment]
One of the current issues is that you just get generic errors around sending events to ES not working. It'd be better to give users a reason why these errors are happening. I think if we say "We can't talk to Elasticsearch at this URL" that will be much more helpful.

Additionally, on register we could check if say `/_cluster/health` can be reached to give an early warning, before any events are sent, that perhaps we may not be able to hit our endpoint.

So, I propose two changes:

1. Change "got error to send bulk" error messaging to say something like "Could not write event '{}' through bulk API to http://server:port/_bulk" which will help admins diagnose the issue better.
2. Add a ping healthcheck on register that will detect if ES is reachable or not with strong messaging around the error. Something like "Elasticsearch output healthcheck failed. Elasticsearch is not reachable at http://server:port/_cluster/health. Are you sure you've configured your Elasticsearch settings correctly?". We could even set a flag if the healthcheck passes and make a note of this on "got error to send to bulk" errors to say "a healthcheck failed on plugin startup as well".

**Comment by jordansissel** [comment]
Agreed on helping provide stronger diagnostics from ES on errors (specific events, or network faults, or cluster problems)

**Comment by andrewvc** [comment]
@jordansissel do you think the two pronged approach I mentioned is the right path here?

**Comment by jordansissel** [comment]
@andrewvc for item 1; I think showing which event(s) failed and each specific failure for that event (I think the bulk response has the per-doc failure exceptions we could show to users). For item 2, having a background health check going on to check cluster health could be useful indeed to help better-inform any reports to users. +1 on both changes. I suspect we'll add more in the future, but this is a great start :)

**Comment by andrewvc** [comment]
@jordansissel thanks! I'll get started then :)

**Comment by hkarpf** [comment]
+1 on this, as I'm having read timeout issues, but my cluster is up and running.  Does it continue to try and output to elasticsearch, e.g. a retry?

**Comment by andrewvc** [comment]
This has been a part of the ES output since LS5.x. Closing.
