### ISSUE TITLE
Failed to flush outgoing items / no method 'type' for arguments

### ISSUE THREAD

**Issue by sayotte** [logstash-plugins/logstash-output-elasticsearch#223]
@talevy asked me to open a new issue, as he/she felt it's distinct from https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/63 

After running without issue for a period of time (at least an hour), I am seeing this error with logstash-1.5.3, followed ultimately by the process exiting.

> Failed to flush outgoing items {:outgoing_count=>1, :exception=>#<NameError: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest>, :backtrace=>["/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:262:in `build_request'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:223:in `bulk'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch/protocol.rb:222:in `bulk'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:519:in `submit'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:518:in `submit'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:543:in `flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:542:in `flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:508:in `receive'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):191:in `output_func'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}
Got error to send bulk of actions: no method 'type' for arguments (org.jruby.RubyArray) on Java::OrgElasticsearchActionIndex::IndexRequest {:level=>:error}

Here is my logstash.conf:
```
input {
  syslog {
    type => "syslog"
  }
}

filter {
  if [message] =~ /IPTables/ {
    if [message] =~ /Rejected/ {
      grok { 
        match => { "type" => "syslog" }
        add_tag => [ "netfilter", "rejected_packets" ] 
      }
    }
    else if [message] =~ /Dropped/ {
      grok { 
        match => { "type" => "syslog" }
        add_tag => [ "netfilter", "dropped_packets" ]
      }
    }
        
    grok {
      match => { 
        "message" => "\[\d+\.\d+] IPTables-\w+: IN=%{NOTSPACE:in_iface} OUT=%{NOTSPACE:out_iface}? MAC=%{NOTSPACE:mac_addr} SRC=%{IP:src_ip} DST=%{IP:dst_ip}"
      }
    }
    grok {
      match => { 
        "message" => [
          "LEN=\d+ TOS=%{NOTSPACE:tos} PREC=\S+ TTL=\d+ ID=\d+ (DF )?PROTO=%{NOTSPACE:protocol} TYPE=%{NUMBER:type:int} CODE=%{NUMBER:code:int} ID=\d+ SEQ=\d+",
          "LEN=\d+ TOS=%{NOTSPACE:tos} PREC=\S+ TTL=\d+ ID=\d+ (DF )?PROTO=%{NOTSPACE:protocol} SPT=%{NUMBER:src_port:int} DPT=%{NUMBER:dst_port:int} WINDOW=\d+ RES=\S+ %{GREEDYDATA:flags}",
          "LEN=\d+ TOS=%{NOTSPACE:tos} PREC=\S+ TTL=\d+ ID=\d+ (DF )?PROTO=%{NOTSPACE:protocol} SPT=%{NUMBER:src_port:int} DPT=%{NUMBER:dst_port:int} LEN=\d+"
        ]
      }
      add_tag => [ "proto_%{protocol}" ]
    }
    if [in_iface] == 'eth0' {
      geoip {
        source => "src_ip"
      }
    }
  }
  else {
    drop { }
  }
}
  
output {
  stdout { codec => rubydebug }
  elasticsearch {
    protocol => transport
    port => 9300
    host => "172.17.0.2"
  }
}
```

Elasticsearch version is 1.7.1. Both processes are running in docker containers.

**Comment by talevy** [comment]
thanks!

are you receiving this error occasionally, or always?

One thing you may want to try is to use `protocol => http` it tends to be easier to manage operationally.

regarding this `type` issue. I believe you are overriding the value of `type` into a number via this grok expression:

```
 "LEN=\d+ TOS=%{NOTSPACE:tos} PREC=\S+ TTL=\d+ ID=\d+ (DF )?PROTO=%{NOTSPACE:protocol} TYPE=%{NUMBER:type:int} CODE=%{NUMBER:code:int} ID=\d+ SEQ=\d+",
```

the `%{NUMBER:type:int}` is setting the `Event[type]` field to be this integer. I would recommend trying to rename this into something other than `type`

let me know if all that helps!

**Comment by sayotte** [comment]
Gee, you narrowed that down pretty fast haha. This is failing quickly but not consistently... less than a few hours, more than a few minutes.

Your suggestion would explain the behavior-- the match line in question should pick up messages about dropped ICMP packets, which occasionally but not in a steady stream.

I'll rename the field to "icmp_type" and report back if I don't see this within a few hours.

**Comment by sayotte** [comment]
I thought twice about waiting.

Sending an ICMP packet that should be rejected, triggering the message and hitting that line *does* reproduce the error.

Renaming "type" to "icmp_type" in that match line and sending the same ICMP packet demonstrates that the problem's gone.

Thanks for your fast help @talevy !
