### ISSUE TITLE
failed action with response of 400 -> Need more detailed error messages

### ISSUE THREAD

**Issue by philbb** [logstash-plugins/logstash-output-elasticsearch#225]
While using logstash to ingest data from a file into ES, I received the error : 
`failed action with response of 400, dropping action`
This is extremely generic and does not help pinpoint the error. 
I suspect the error is a data type mismatch between the ES mapping and the `convert` instruction in the logstash conf file, but it would be helpful if that could be included in the error message.
I've seen people getting `failed action with response of 400` for a large variety of errors, so their solutions (posted online) were not at all useful to me or other searching for that error.  
The logstash error messages really should be more specific.

**Comment by leprechaun** [comment]
This is the kind of bug for which there is no fix. I can accept ES reacting the way it does, after all, it's *us* being weird.

We can change the code and make your event find it's way into elasticsearch, but it changes user expectations.

I didn't see this bug report before filing mine.

https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/233

**Comment by ppf2** [comment]
+1.  This makes troubleshooting and historical debugging very difficult.  

Take the following as an example.

You have a bunch of exceptions coming back from Logstash (using latest 1.5.4) like the following.

```
{:timestamp=>"2015-09-04T13:22:32.432000-0700", :message=>"failed action with response of 400, dropping action: [< the full json event body]", :level=>:warn, :file=>"logstash/outputs/elasticsearch.rb", :line=>"554", :method=>"submit"}
```

That's it, even at the --debug level in Logstash.  You have no idea what is going on and why it is throwing a 400.

What makes it worse is that on the Elasticsearch side, no exceptions are thrown at the default logging level.  So unless they have turned up action.bulk to DEBUG level (unlikely for it can be very verbose), there's no information that will tell you when the bulk item is rejected and abandoned.

Elasticsearch is correctly responding with the reason/error (example below) for these failed bulk items.

```
            "status": 400,
            "error": "MapperParsingException[failed to parse [created_at]]; nested: MapperParsingException[failed to parse date field [2014-07-23 17:20:54 -0700], tried both date format [dateOptionalTime], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: \"2014-07-23 17:20:54 -0700\" is malformed at \" 17:20:54 -0700\"]; "
```

Logstash needs to capture these and report back to the Logstash user so they can take appropriate actions :)

**Comment by andrewvc** [comment]
+1 here, we need to include the elasticsearch response here

**Comment by andrewvc** [comment]
I've started work on this in my beta4 branch https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/247

Will finish this work on tuesday :).

**Comment by andrewvc** [comment]
Just as an update, I've got a WIP branch here. Something is borking the tests that I'll have to look at next week: https://github.com/andrewvc/logstash-output-elasticsearch/pull/2

**Comment by andrewvc** [comment]
This should now be fixed when #247 is merged. This will make it out in the next LS2.0 beta

**Comment by andrewvc** [comment]
This is now in the 2.0 betas.The java version does not yet have this, but will soon! (it has a separate issue https://github.com/logstash-plugins/logstash-output-elasticsearch_java/issues/20 )

**Comment by cdenneen** [comment]
@andrewvc any chance to put this in the 1.x branch for elasticsearch output?

**Comment by andrewvc** [comment]
@cdenneen this should support ES 1.x and 2.x. It is unlikely that we'll ever backport this to LS 1.5 however due to time concerns.
