### ISSUE TITLE
Enable TLS (Client) Authentication

### ISSUE THREAD

**Issue by torrancew** [logstash-plugins/logstash-output-elasticsearch#23]
This is being filed mostly for documentation purposes, until some upstream patches spring into existence.

We recently enabled TLS mutual auth on our Kibana/ES proxy, with much success. Unfortunately, we can't Logstash with this configuration, so it is still pointed at a non-proxied ES. In attempting to add the functionality to support this, I realized that the elasticsearch-ruby library's Manticore adapter does not expose any auth-related SSL settings, and ultimately found [some issues in Manticore's SSL](https://github.com/cheald/manticore/issues/10) configuration details that make this not very straightforward. Once a fix is pushed into either Manticore or [elasticsearch-ruby](https://github.com/elasticsearch/elasticsearch-ruby/issues/80) we should be able to implement this with relative ease.

**Comment by jsvd** [comment]
Does the current version of this plugin solve your problem? Can we close this issue, @torrancew ?

**Comment by torrancew** [comment]
@jsvd this issue is specifically about TLS certificate authentication, so until we get that added, I would consider this still needed. I am working on the manticore side of things to help plumb this over now.

**Comment by andrewvc** [comment]
@torrancew good news, client certs were added quite a while ago and now work correctly! You can set one via the `keystore` setting. /cc @jsvd
