### ISSUE TITLE
ES output does not handle "@" symbol in password for Shield user

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#232]
To repro:
1.  Create Shield user (eg. logstash4) that has the @ symbol as part of the password, eg. logst@sh
2.  Confirm that the user works outside of LS:

```
curl -u logstash4:logst@sh -XPOST "http://localhost:9200/logstash-test/type/_bulk" -d'
{"index":{}}
{"city": "hallo city" }
{"index":{}}
{"city": "hallo city2" }
'
```

3. Then use the above user/password in the LS config

```
output {
  elasticsearch {
  host => localhost
  cluster => elasticsearch_1_7_1_shield
  protocol => http
  user => "logstash4"
  password => "logst@sh"
 }
}
```

It will throw an AuthenticationException

```
Got error to send bulk of actions: [401] {"error":"AuthenticationException[unable to authenticate user [logstash4] for REST request [/_bulk]]","status":401} {:level=>:error}
```

Perhaps the @ in the password is confusing with Ruby's instance variables ..

**Comment by AdeMiller** [comment]
I believe the issue here is that the plugin is not escaping the URL that gets used. So `logst@sh` ends up on the wire as a request to `http://logstash4:logst@sh@localhost/` which will not get parsed correctly.

**Comment by andrewvc** [comment]
Thanks for reporting this @ppf2 , I'll take a look at this on monday

**Comment by jpapejr** [comment]
Just found this as well.. Switching from a user of xxx@xx.xx.xx to xxxx worked so this look like a bug with the url escaping.

**Comment by AdeMiller** [comment]
I would recommend looking at this pretty seriously escaping is often indicative of a security issue

**Comment by suyograo** [comment]
This has been fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/287
