### ISSUE TITLE
400 client error on mapping coersion errors

### ISSUE THREAD

**Issue by leprechaun** [logstash-plugins/logstash-output-elasticsearch#233]
I've run into this problem, and I'm not quite sure since when.

Because I'm using Elasticsearch mapping auto management, the order in which messages are received is very relevant.

For example:
First event of the day

```
{
    "@timestamp":"2015-08-25 01:01:34",
    "message": {
        "key": "value"
    }
}
```

A subsequent event that same day

```
{
    "@timestamp":"2015-08-25 00:01:34",
    "message": "a string"
}
```

```
user@host [master *%]:~/$ curl -v -XPOST --data-binary @problematic-event.json https://elasticsearch-host:9200/logstash-2015.08.25/logs
* Hostname was NOT found in DNS cache
*   Trying X.X.X.X ...
* Connected to elasticsearch-host (X.X.X.X) port 9200 (#0)
> POST /logstash-2015.08.25/logs HTTP/1.1
> User-Agent: curl/7.38.0
> Host: elasticsearch-host:9200
> Accept: */*
> Content-Length: 844
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 844 out of 844 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=UTF-8
< Content-Length: 281
< Connection: keep-alive
< 
* Connection #0 to host elasticsearch-host left intact
{"error":"RemoteTransportException[[HOSTNAME][inet[/IP:9300]][indices:data/write/index]]; nested: MapperParsingException[object mapping for [message] tried to parse field [message] as object, but got EOF, has a concrete value been provided to it?]; ","status":400}
```

ElasticSearch borks because it can't coerce the type against the existing mapping, which kind of makes sense. However, in a large scale deployment, where I encourage developers to log data structures instead of plain strings, I will likely come across this problem more often as the log volume grows.

Current solutions include:
1. create types based on upstream data segmentation

All my applications provide me with fields like "source.application", "source.project". I can use these to create per application, or per project types/mappings. Any clash would be limited to a single team/project, making it an easier problem to ~~solve~~manage.

eg,

```
{
    "@timestamp":"2015-08-25 01:12:35", 
    "_type": "%{project}_%{application}_%{type}",
    "actual_data_type": "%{type}"
     /* ... */
}
```

However, it means that types/mappings that should be common, say HTTP access logs, have duplicated mappings, which leads to some inefficiency I cannot measure, which I'm not sure is relevant, but it's there on paper and at the very least, an annoyance.
1. Give each application it's own set of indices

Variation on a theme. Makes queries more complicated, would need to hack Kibana (Using V3 here) to support more than just the date in the dynamic index selection.
1. Find these occurences and coerce it into an object

```
{
    "@timestamp":"2015-08-25 00:01:34",
    "message": {
        "string": "a string"
    }
}
```

This just seems messy, making queries more complicated, and ultimately, still open to failures.
1. Create new mappings if required

Say this mapping coersion failure happens, the elasticsearch plugin could re-submit the event with a new somewhat randomized mapping, potentially adding a tag, eg "mapping_coersion_fail"

This may skew your analytics if you're dependent on the `_type` field, but I MUCH MUCH prefer the data to be present (but mislabelled) versus not having the data at all.

A QA flagged an issue with data not being in ES. I had to re-trace the flow of events from the app to ES, which is a bit more complicated than it could be, only to find out, at the last step, that I had a few hundred megs of logstash logs about this error.

I'm aware of this: https://github.com/elastic/logstash/issues/2607 which would add a queue for events that fail to go somewhere. But as my problem is ElasticSearch specific, these alternatives may be worthy of consideration.

Thoughts?

**Comment by andrewvc** [comment]
This is really more of an ES issue. The only real fix is to have a type per application, OR do your `actual_data_type` fix. In the future these sorts of questions are better asked on discuss.elastic.co/c/logstash
