### ISSUE TITLE
Logstash agent hangs.

### ISSUE THREAD

**Issue by DanKans** [logstash-plugins/logstash-output-elasticsearch#234]
Hi, 

I have a problem with logstash agent and its sending data to ES cluster feature.

Logstash agent is spawn by wrapper process, logs are processing and sending normally due to occurence in logs this information:

{:timestamp=>"2015-08-26T02:00:48.665000-0700", :message=>"Shifting current elasticsearch client", :level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"572", :method=>"flush"}
{:timestamp=>"2015-08-26T02:00:48.665000-0700", :message=>"Switched current elasticsearch client to #0 at ES.loadbalancer", :level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"623", :method=>"shift_client"}

After that logstash is "freezing" and no data is sending to ES cluster.

I think it might be an issue with connectivity between logstash-output plugin and ES cluster.

Details about configuration:

ES: 1.4.4
Logstash version: 1.5.0
plugin: logstash-output-elasticsearch-1.0.7-java
Java version: jdk-1.7.0_21
Some settings: 
-Xmx256m
-Xms256m
-Xss2048k

Logstash configuration:

input {
  file {
    type => "TYPE"
    codec => multiline
        {
            pattern => '^\{'
            negate => true
            what => previous
        }
    path => [ "/logs/log.log" ]
    exclude => ["*.gz"]
    sincedb_path => "/db/TYPE"
    }
  
  heartbeat {
	threads => 1
	message => "heartbeat"  
	interval => 120
	debug => false
    }
}

filter: {}
  if [type] == "TYPE"  {
    mutate
    {
        replace => [ "message", "%{message}" ]
        gsub => [ 'message','\n','']
    }
    if [message] =~ /^{.*}$/
    {
        json { source => message }
    }
  }
}

output {
  elasticsearch {
    host => "ES.loadbalancer"
    protocol => "http"
  }
}

JSTACK:
https://gist.github.com/DanKans/61e0ed94da1366ce6dc3

Thank in advance !

**Comment by ph** [comment]
Can you try to update to the latest version of logstash? 
Logstash 1.5.0 had a deadlock issue that was fixed in newer version and I think this might be your problem.

**Comment by DanKans** [comment]
Thank you for your replay. I'll use the newest stable version. Closing issue.
