### ISSUE TITLE
no (or some) events indexed when workers > 1

### ISSUE THREAD

**Issue by peterskim12** [logstash-plugins/logstash-output-elasticsearch#24]
This is with Logstash 1.4.2, Elasticsearch 1.4.0.

I have a very simple config to index a small batch of 1000 json events:

```
input {
  	stdin {
		codec => json_lines {}
	}
}

filter {
	date {
		match => [ "stbReportTime", "ISO8601"]
	}
}

output {
	# stdout { codec => rubydebug }
	stdout { codec => dots }
	elasticsearch {
		protocol => http
		host => "localhost"
		index => "testindex"
		workers => 2
	}
}
```

After running with:

bin/logstash -f logstash.conf < data.json

the index 'testindex' does not get created and there are no events indexed in Elasticsearch. 

When I add some template definitions, then it seems to create the index but only index some of the events (usually about 483; that number seems to be consistent):

```
input {
  	stdin {
		codec => json_lines {}
	}
}

filter {
	date {
		match => [ "stbReportTime", "ISO8601"]
	}
}

output {
	# stdout { codec => rubydebug }
	stdout { codec => dots }
	elasticsearch {
		protocol => http
		host => "localhost"
		index => "testindex"
		template => "index_template.json"
		template_name => "testindex"
		template_overwrite => true
		workers => 2
	}
}
```

After removing the workers => 2 parameter, all 1000 events are indexed properly.

This could be the same issue as referenced in this JIRA ticket: https://logstash.jira.com/browse/LOGSTASH-1535.

**Comment by suyograo** [comment]
Fixed via https://github.com/elasticsearch/logstash/pull/2180
