### ISSUE TITLE
Add integration test for sniffing

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#243]
Example test could be as follows:
1. launch an ES instance
2. start the plugin and have run until sniffing period ends
3. launch another ES instance, wait for next sniffing period
4. kill the original instance and verify it is still working

**Comment by andrewvc** [comment]
We now have an integration test for sniffing that tests the response, and unit tests that check the other behavior.

As much as I like this idea I don't know when we will have the time to do it.

**Comment by talevy** [comment]
I agree, I think the new tests that were added + RATS really covers the goals here. 

closing.
