### ISSUE TITLE
ElasticSearch output won't proccess events (Logstash as reindexer for ElasticSearch)

### ISSUE THREAD

**Issue by EnvyChan** [logstash-plugins/logstash-output-elasticsearch#244]
Hi,

**A moment for specs first:**

ElasticSearch 1.7 
Logstash 1.5.1
Java 1.8
RHEL 6.2

I've been trying for the past two days to use Logstash as a reindexer for elasticsearch (using ElasticSearch input and ElasticSearch Output with not filter inbetween).

For some indexes, generally the smaller ones (not all small ones) this works perfectly. 
But for larger indexes, size ranging from 40mb-15G I have not output at all.

I'm running the config file under an angent with --verbose and --debug and I have no errors comming up at all.

**This is the config I'm using:**

input{
       elasticsearch{
              hosts=>["old_es_cluster_ip"]
              port=>9200
              docinfo=>true
              index=>"copied_index_name"
              scroll=>"10m"
              size=>10000
              scan=>true
              type=>"copied"
       }
}
output{
         if "copied" in [type]{
                elasticsearch{
                       index=>"%{[@metadata][_index]}"
                       document_type => "%{[@metadata][_type]}"
                       document_id => "%{[@metadata][_id]}"
                       manage_template => false
                       port => 9200
                       protocol => "http"
                       host => ["es_ip_here"]
                       workers => 5
                }
                stdout {
                       codec => "dots"
                }
         }
}

**This is the output I get for every index I can't get logstash to reindex:**

sh /opt/logstash/bin/logstash -f /etc/logstash/conf.d/elastic_to_elastic --verbose --debug
DEBUG: exec /opt/logstash/vendor jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-Xmx12G /opt/logstash/lib/bootstrap/environment.rb
logstash/runner.rb agent -f /etc/logstash/conf.d/elastic_to_elasting //verbose --debug
Using version 0.1.x input plugin 'elasticsearch'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x input plugin 'json'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x input plugin 'elasticsearch'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x input plugin 'plain'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x input plugin 'stdout'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Using version 0.1.x input plugin 'dots'. This plugin isn't well supported by the community and likely has no maintainer. {:level=>:info}
Create c;oemt tp e;astocsearch server on <es_ip_here>: {:level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}
Pipeling started {:level=>:info}
Logstash startup complete
Create client to elasticsearch server on <es_ip_here>: {:level=>:info}
Create client to elasticsearch server on <es_ip_here>: {:level=>:info}
Create client to elasticsearch server on <es_ip_here>: {:level=>:info}
Create client to elasticsearch server on <es_ip_here>: {:level=>:info}
Create client to elasticsearch server on <es_ip_here>: {:level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}
New ElasticSearch output {:cluster=>nil, host=>["es_ip_here"], :port=>9200, :embedded=>false, :protocol=>"http", :level=>:info}

...After sometime I just get this:
Plugin is finished {"plugin=><Logstash::Inputs::Elasticsearch hosts=>["es_ip_here"], index=>"copied_index_name", scroll=>"10m", type=>"copied", query=>"{\"query\":{\"match_all\":{} }}" docinfo_target=>"@metadata",docinfo_fields=>["_index","_type","_id"]>, :level=>:info}
Plugin is finished {:plugin=><LogStash::Outputs::Stdout>, :level=>:info}
Pipeline shutdown complete. {:level=>:info}
Logstash shutdown complete 

**Things I tried so far:**
--Reindexing to the same cluster - no change 
--Enlargen LS_HEAP_SIZE - It has 16G right now. And is quite irrelevant since it has no memory issues while running.
--I've tried adding debug logger messaged in the logstash code. I've started from the ElasticSearch input plugin. I could defintly see the the plugin was getting the JSONs from the queries for each index tried. 
In pipeline.rb I came to the conclusion that it was waiting for input threads. Maybe for some reason just not passing them on to the Output?
-- In the configuration file I've tried changing for input the scroll time and the result set size. I tried changing it to the size of the index (for a small index) but with not help. I also don't get a bad response from elasticsearch (for a timeout) neither do I see one in the ES log. 

Doubtfully it is a memory issue (index size issue) since, yes, most small indexes do pass through, but some indexes with smaller sizes don't.

Last point - we use ES output plugin in all our configurations, this is the first time something like this happens. (From file, tcp, udp and snmp)

Side note, when I use the example on the elastic website for query=>"*" I get errors back from elasticsearch.

Am I doing something that wrong? Maybe something in my configuration? What am I missing?

Help will be appreciated,

Simona

**Comment by andrewvc** [comment]
Hi Simona, apologies for the delay. Really sorry to hear about your troubles here. The recommended forum for these questions is our discuss site. Issues here are more for specific issues with this plugin.

You can find our discuss forum here https://discuss.elastic.co/c/logstash
