### ISSUE TITLE
Provide user information to migrate from host to hosts

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#246]
In 2.0 we moved to `hosts` to better document that the option supports multiple ES hosts. Lots of folks still use the old param. Can we add a warning in `#register` if they are using `host` to now uses `hosts`. 

Today we get this warning (which is expected):

`Unknown setting 'host' for elasticsearch {:level=>:error}`

We should instead provide a better guidance like `host` is now moved to `hosts`

**Comment by suyograo** [comment]
Actually same thing for `protocol` setting too, just so we can aid people with this migration. Thoughts?

**Comment by andrewvc** [comment]
@suyograo shouldn't we make this a breaking change? I think having deprecated options in 2.0 is a bad idea. When else will it be considered OK to change them?

Maybe we should accept the option but immediately raise a `ConfigurationError` if its set?

**Comment by suyograo** [comment]
@andrewvc no, no, not having deprecated in 2.0. If someone already has this option we don't accept it, but guide them using logging to using the new options.

**Comment by andrewvc** [comment]
Ah, so, @suyograo I'm thinking that we should try and add a new config option `:obsolete` to logstash that acts like `:deprecated` in that it displays a message, but instead of continuing doesn't let you continue to startup logstash.

Thoughts?

Otherwise I have to declare it as a deprecated option, then check in `register` for it, and raise a `ConfigurationError`

**Comment by jordansissel** [comment]
I'm open to an :obsolete flag. The behavior being similar to the :deprecated flag - that an error is emitted "THis setting is obsolete. <some message describing how to resolve this>" as well as causing a configuration error on logstash startup

Example use: `config :host, :obsolete => "Use the `hosts` setting instead."`

**Comment by jordansissel** [comment]
haha just realized I repeated what @andrewvc suggested. +1 on that suggestion :)

**Comment by suyograo** [comment]
Awesome, lets move forward on `:obsolete`

**Comment by jordansissel** [comment]
@suyograo this could help for Logstash 2.0 actually, we could change all current `:deprecated => ...` to `:obsolete => ...` and do the actual code removal later. Thoughts? We can discuss that on a separate meta ticket

**Comment by suyograo** [comment]
Done in #277
