### ISSUE TITLE
Issue with HTTP SSL/TLS

### ISSUE THREAD

**Issue by acchen97** [logstash-plugins/logstash-output-elasticsearch#248]
Issue getting HTTPS to work with ES 1.7

ES 1.7 is Shield enabled with basic auth and SSL/TLS.  Similar config works with a LS 1.5.4 instance, but not with a LS 2.0-beta1 instance.  Config file and errors below:

Config file:
input {
  stdin { }
}
output {
  stdout { codec => rubydebug }

  elasticsearch {
    hosts => "xyz"
    index => "test1"
    user => "es_admin"
    password => "changeme"
    ssl => true
    cacert => '/path/cacert.pem'
  }
}

acchen$ bin/logstash -f path/test_conf_http_ssl.conf
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->xyz:9200: The target server failed to respond
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->xyz:9200
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->xyz:9200: The target server failed to respond
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->xyz:9200
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->xyz:9200: The target server failed to respond
Sep 04, 2015 2:49:49 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->xyz:9200
Failed to install template: xyz:9200 failed to respond {:level=>:error}
Logstash startup completed
test
{
       "message" => "test",
      "@version" => "1",
    "@timestamp" => "2015-09-04T21:51:33.388Z",
          "host" => "xyz"
}
Attempted to send a bulk request to Elasticsearch configured at '["xyz:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["xyz:9200/"], :ssl=>{:truststore_password=>"GKBFdYTj2tGQ", :truststore=>"/var/folders/8j/xtwqr5t16tdcnp91g6g4_wt40000gn/T/cert8305315699113281739.jks", :keystore=>"/Users/acchen/Documents/Elastic_FBI/Github/elasticsearch-internal-support-tools-master/genShieldCerts/java/out/artifacts/ESSLHelper_jar/all_certs/alvin1/alvin1.jks", :keystore_password=>"changeme"}, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{:truststore_password=>"GKBFdYTj2tGQ", :truststore=>"/var/folders/8j/xtwqr5t16tdcnp91g6g4_wt40000gn/T/cert8305315699113281739.jks", :keystore=>"/Users/acchen/Documents/Elastic_FBI/Github/elasticsearch-internal-support-tools-master/genShieldCerts/java/out/artifacts/ESSLHelper_jar/all_certs/alvin1/alvin1.jks", :keystore_password=>"changeme"}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :headers=>{"Authorization"=>"Basic ZXNfYWRtaW46bHVja3kxMjM="}, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"xyz:9200 failed to respond", :error_class=>"Manticore::ClientProtocolException", :backtrace=>["/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245:in `call_once'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148:in `code'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `bulk'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:361:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:358:in `submit'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:384:in `flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:351:in `receive'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):29:in `output_func'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:error}

Failed to flush outgoing items {:outgoing_count=>1, :exception=>"Manticore::ClientProtocolException", :backtrace=>["/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:70:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:245:in `call_once'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/manticore-0.4.4-java/lib/manticore/response.rb:148:in `code'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `bulk'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:361:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:358:in `submit'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:384:in `flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:216:in `buffer_flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:193:in `buffer_flush'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/buffer.rb:159:in `buffer_receive'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.pre.beta2-java/lib/logstash/outputs/elasticsearch.rb:351:in `receive'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):29:in `output_func'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/Users/acchen/Documents/Elastic_FBI/Elastic_Sandbox/Logstash/logstash-2.0.0.snapshot1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.snapshot1-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}

**Comment by andrewvc** [comment]
Thanks @acchen97 , will take a look at this ASAP :)

**Comment by andrewvc** [comment]
This should now be fixed in beta5. Please re-open if this is still an issue!
