### ISSUE TITLE
Option "port" broken (2.0.0.beta3)

### ISSUE THREAD

**Issue by Da-Wei** [logstash-plugins/logstash-output-elasticsearch#249]
Hi !
When I run integration tests with docker all tests failed because container uses another port than 9200.
The configuration parameter "port" defined in elasticsearch.rb is not provided to the class LogStash::Outputs::Elasticsearch::HttpClient and the "host:port" format is not understood by the new parameter "hosts" (default port value 9200 is added to "host:port" ).

**Comment by andrewvc** [comment]
Thanks @Da-Wei , that is a killer find. I'll be looking into that today!

**Comment by andrewvc** [comment]
@Da-Wei now fixed in beta5. Please re-open if this is still broken for you!
