### ISSUE TITLE
Unknown setting "host" for elasticsearch

### ISSUE THREAD

**Issue by jmcomets** [logstash-plugins/logstash-output-elasticsearch#258]
Hi all,

I'm getting an unusual error when running current beta1 version of Logstash. The error is as noted in the title `Unknown setting 'host' for elasticsearch {:level => :error}`. I'm using the following in my configuration :

    if "error" in [tags] {
        elasticsearch {
            host => ["localhost"]
            index => "myindex"
            document_type => "error"
        }
    }

**Comment by jmcomets** [comment]
Erf, resolved. I upgraded to the latest version of LogStash, and now plugins aren't bundled...

**Comment by seantang-galaxy** [comment]
it should be "hosts"
