### ISSUE TITLE
Flush on shutdown

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#261]
Currently in the new version of this plugins we don't flush when are shutting down the pipeline.
We should manually call flush if we receive the ShutdownSignal.

From @jsvd 

reproduce steps:
1. start elasticsearch
2. use logstash 2.0 branch
3. bin/plugin install --version="2.0.0.beta6" logstash-output-elasticsearch
4. bin/logstash -e "input { generator { count => 50 } } output { elasticsearch { } }"
5. run logstash, wait to finish, then check elasticsearch event count

**Comment by suyograo** [comment]
@andrewvc can you take a look at this please?

**Comment by andrewvc** [comment]
@suyograo yup, will do

**Comment by andrewvc** [comment]
Hmmmm, it would seem that `#close` is never being invoked. This may be an LS core issue?

**Comment by andrewvc** [comment]
I was testing against a version of LS without shutdown. I can't actually repro this issue however. Works for me! @jsvd we should sync up and figure this out interactively maybe if you're still seeing this

**Comment by suyograo** [comment]
@jsvd were you waiting for ES to refresh before you tested it?

**Comment by cdahlqvist** [comment]
I also experienced an issue with respect to flushing, but it seemed to depend on the number of workers I used. The following example did flush and wrote the data to the index:

```
echo test | logstash -e "input{stdin{}} filter{} output{elasticsearch{protocol => "http"}}"
```

The following example, where the number of workers is set to 2, did however not flush and the records were therefore lost:

```
echo test | logstash -e "input{stdin{}} filter{} output{elasticsearch{protocol => "http" workers => 2}}"
```

**Comment by andrewvc** [comment]
@cdahlqvist it looks like you're using LS1.x, this issue is specifically for the 2.x betas. It is, unfortunately, a known issue in 1.x

**Comment by jsvd** [comment]
I couldnt replicate this again on logstash-2.0.0-beta2 + elasticsearch 1.7.2, so I'm closing the issue.
@cdahlqvist please open another issue focused on 1.x
