### ISSUE TITLE
clarify which keystore to use when having an array of http hosts

### ISSUE THREAD

**Issue by nellicus** [logstash-plugins/logstash-output-elasticsearch#263]
docs are far from clear on this

https://www.elastic.co/guide/en/logstash/2.0/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-keystore_password

cc @debadair @palecur

**Comment by andrewvc** [comment]
@nellicus I'm not sure what your question is. Is it between using `keystore` and `truststore`, or something else?

**Comment by nellicus** [comment]
@andrewvc as per subject

```
clarify which keystore to use when having an array of http hosts
```

when you have

```
hosts => ["w530:9200","w530:9201","w530:9202"]
```

which keystore to use in

```
keystore => "/opt/elk/PRODSEC/FS/secure/node1.jks"
keystore_password => "changeme"
```

the one for node publishing w530:9200 or the node publishing on w530:9201 or the node publishing on w530:9202?

let me know if this makes it clearer

thanks

**Comment by andrewvc** [comment]
Antonio this should affect all hosts. I'll update the docs to reflect that

**Comment by nellicus** [comment]
@andrewvc 

using the a keystore containing one of the node certificate and the rootCA certificate does not work:

```
Failed to install template: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target {:level=>:error}
```

What are the exact specs of the keystore that we need to reference?

**Comment by andrewvc** [comment]
Hmmm, I'll try and take a look later this week. Maybe @jsvd can weigh in here?

**Comment by andrewvc** [comment]
@nellicus did you try googling that error? This looks like one solution for your keystore (which appears to not be complete) https://developer.salesforce.com/forums/?id=906F00000008lzhIAA

**Comment by nellicus** [comment]
@andrewvc I'll try with

```
cacert => /path/to/rootca/cert.pem
```
looks like that's the way to go for http connection which I appear to have missed https://www.elastic.co/guide/en/shield/current/logstash.html#ls-http-ssl

**Comment by andrewvc** [comment]
@nellicus please open a new issue if you find further bugs!

**Comment by andrewvc** [comment]
Yes, generally keystores are harder to work with. Keep in mind though that
you'll still need to use a keystore if you need client x509 auth
