### ISSUE TITLE
Verify this plugin round-robins for every bulk request

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#274]
The elasticsearch-ruby client is supposed to round-robin requests to the nodes specified in the `hosts` setting. From internal testing it seems like one of the node is getting hit more often than the other. The setting used in testing was `[localhost:9200, localhost:9201]`

![round-robin](https://cloud.githubusercontent.com/assets/1595958/10546440/d17e1d6e-73e2-11e5-9a89-21ed6e990bea.png)

y-axis in the graph is the bytes-in to a port. Data in bulk request used for testing was the same size, so we should not see 2:1 requests distribution to hosts, should have almost equal distribution

**Comment by gingerwizard** [comment]
The following test was performed:

1. Two node cluster running on 9202 and 9201 respectively.
2. Logstash configuration indexed data over HTTP. Following output configuration:

output {
    elasticsearch {
    	host => ["localhost:9202","localhost:9201"]
    	cluster => "test-cluster"
    	protocol => "http"
    	workers => 1
    	index => "test"
    	flush_size => 500
	}
}

3. Packetbeat monitoring HTTP ports 9202, 9201. Packetbeat configured to index into separate Elastic cluster on 9200 so as to not skew results.

4. Kibana configured to use 9200 packetbeat index. Only requests with HTTP path path:"/_bulk" considered in the following visuals.

5. 4 visuals as shown below.  
 - Sum of bytes over time per port
- Total requests over time per port
- Total Requests port 9201
- Total Requests port 9202
- Sum of bytes port 9201
- Sum of bytes port 9201
 
6. The same log line was sent to logstash using nc from a file containing 1m duplicate lines.  Ensures packet data is of equal size. No filters in logstash.

![image](https://cloud.githubusercontent.com/assets/12695796/10548156/bef2bb66-7430-11e5-94bb-b083372c9ce2.png)


The above shows a balance of requests. Issue can be closed.

Thanks
Dale

**Comment by gingerwizard** [comment]
Wrong image.

![image](https://cloud.githubusercontent.com/assets/12695796/10548204/e4c9960c-7430-11e5-96a4-ceae35691904.png)

**Comment by TinLe** [comment]
There is a related bug where in the first two hosts listed in hosts => get more connections and consumed lots more filehandles.

It's easily reproduced in logstash versions 2.1.0 - 2.1.3, and logstash versions 2.2.0 - 2.2.2
