### ISSUE TITLE
Improve default template

### ISSUE THREAD

**Issue by sathieu** [logstash-plugins/logstash-output-elasticsearch#275]
I suggest the following:
* Use "index": "not_analyzed" on all string fields (except message?)
* Use "doc_values": true on all string fields

**Comment by untergeek** [comment]
> - Use "index": "not_analyzed" on all string fields (except message?)

- This is already [addressed](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L24) by making all strings have a .raw, not_analyzed variant.
- And the message field is [already mapped](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json#L10-L17) to still be analyzed.

> - Use "doc_values": true on all string fields

2 things:

1. doc_values can only be used on not_analyzed strings
2. doc_values will automatically be applied to not_analyzed strings by default in Elasticsearch 2.0

As such, the current template should already address your concerns for future releases of Logstash and Elasticsearch.

**Comment by talevy** [comment]
If I am not mistaken, The Logstash template indexes every string field as both the original analyzed field, as well as an additional `<fieldname>.raw` field which is not analyzed. In such a case, Elasticsearch 2.x enabled doc values by default for all numeric and unanalyzed fields.

So, If I am not mistaken, the current template achieves both of these in Elasticsearch 2.x.

**Comment by talevy** [comment]
woops. did not mean to close this. I had a draft comment that I wished to cancel after seeing @untergeek 's reply... clicked the wrong button

**Comment by untergeek** [comment]
@sathieu On consideration, we may be introducing the means to have doc_values in < 2.0 versions of Elasticsearch, as this may be a valid use case for some time.

**Comment by sathieu** [comment]
Why is the analyzed variant needed?

**Comment by untergeek** [comment]
@sathieu This is the _default_ template.  A breaking change like that (since so many others are currently using the .raw field in Kibana or other places) would cause a lot of chaos.  Also, there are a great many users indexing things like syslog, where the message field is not completely parsed.  Having the ability to do full-text search (because the field is analyzed) is a very valid use case for these people.

In the future we may go a different direction, but for now, we don't want to break anyone's setup needlessly.  We're doing our best to help bridge between Elasticsearch 1.x and 2.x so Logstash users can make a more seamless transition.

If you have such a need, we encourage you make your own template with no analyzed strings (save for the "message" field, if you like) and use that.

**Comment by sathieu** [comment]
thanks @untergeek.

I already use a custom template (pushed by puppet, and not logstash). I created this issue to bring improvement to others, and also make sure I understand field mapping correctly.

When you say "many users indexing things like syslog, where the message field is not completely parsed" (this is my case), I think this is handled by having the "message" field analyzed.

Also, for not_analysed strings, wildcard search are still possible (with a performance reduction?).

**Comment by untergeek** [comment]
It's a pretty steep reduction, and taxing, as it involves pulling the data and analyzing it.  This is not the "out of the box" experience we want for new users.

Yes, you can do full text search on "message", but there's no reason you can't do that on other fields too.  Logstash may put many of the default input's data into the message field, but not all do this, and not all inputs make use of the message field.

I'm not saying you're incorrect to do as you've done.  Your use case is a good fit for what you're doing and your proposed changes. I am saying that your proposed changes would negatively affect too many users (especially new ones) to put in place.  

There was a lot of discussion with the Elasticsearch team when we put this template together.  It was deemed a good fit for the broadest possible number of use cases.  It was never intended to be one-size-fits-all.  It was the best solution to help users not abuse Elasticsearch heavily right out of the box.  That's its whole purpose for being.

Once users become knowledgeable of their needs, we recommend fully mapping their data and using that (which you've done).

We may, in the near future, have a "recipe" site where users can share their configurations, dashboards, mappings, etc.  When it becomes available, this would be a great place to share the wisdom of your experience.
