### ISSUE TITLE
Node Protocol Client does not support create requests

### ISSUE THREAD

**Issue by pickypg** [logstash-plugins/logstash-output-elasticsearch#28]
Similar to #16, the node client does not support `"create"` actions.

Create is the same as index operations except that it should require the ID (otherwise it's going to be implicitly create operation anyway!).

**Comment by talevy** [comment]
PR for this issue has moved to here: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/39

**Comment by suyograo** [comment]
Closed via https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/39
