### ISSUE TITLE
Buffer based on bytes, not doc sizes

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#284]
This moves the second half of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/181 here. We should have a buffer sized definable by byte size, not buffer size.

**Comment by ppf2** [comment]
+1 on this, esp. for events from java apps, you don't know when it is going to dump a gigantic soap/rest response or java stack trace to the log :)

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497

**Comment by andrewvc** [comment]
#497 addresses this to my satisfaction.
