### ISSUE TITLE
Document time unit for retry_max_interval parameter

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#290]
> retry_max_interval
> Value type is number
> Default value is 5
> Set max interval between bulk retries

Would be nice to document the time unit, says just 5 right now, let's add a note that this metric is in seconds.

**Comment by GlenRSmith** [comment]
:+1:

**Comment by jsvd** [comment]
[it now shows](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-retry_max_interval):

> Set max interval in seconds between bulk retries.
