### ISSUE TITLE
Encryption of keystore passwords 

### ISSUE THREAD

**Issue by ersushantsood** [logstash-plugins/logstash-output-elasticsearch#295]
As on discussion portal of elastic that there is no support available for adding Encrypted passwords for the SSL keystores and truststores in Logstash and Elastic Search in the configuration files . For Compliance point of view I cannot store passwords in plain text for keystores in Configs.please confirm if this can be achieved later.

**Comment by andrewvc** [comment]
@ersushantsood currently we do not support this. We may add some sort of support for this in the future but it is not on our direct roadmap. 

Have you considered using an encrypted volume for your server?

**Comment by andrewvc** [comment]
Closed due to this being a question and being idle.

**Comment by andrewvc** [comment]
Actually, we now support .keystore files so this is fixed.

**Comment by Ihjaz** [comment]
Hi Andrew,

Is there a sample configuration that shows how I can configure the keystore password in encrypted form?
