### ISSUE TITLE
Error when handling events with data field

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#296]
From https://github.com/elastic/elasticsearch-ruby/issues/234 by @Ockejanssen

---

When trying to import json event with a sub property called data

```
/opt/logstash/bin/logstash --debug -w 1 -e 'input { tcp { port => 12201 type => "deckard2" codec => "json"} } output { stdout { codec => "json" } elasticsearch { hosts => ["localhost:9200"] index => "bla" retry_max_items => 0 manage_template => false}}'
```

```
echo '{"ww":{"id":2222,"data":{"a":"b","description":"c","name":"d"}},"f":8770,"post_date":"2015-11-03T08:17:04.536Z"}' | nc 0 12201
```

```



The line 81 
when payload.any? { |d| d.is_a?(Hash) && d.values.first.is_a?(Hash) && (d.values.first[:data] || d.values.first['data']) }
```

causes the error. The problem is d.values.first['data']

I inserted some debug info:

```
ES: [["index", {:_id=>nil, :_index=>"bla", :_type=>"deckard2", :_routing=>nil}, {"ww"=>{"id"=>2222, "data"=>{"a"=>"b", "description"=>"c", "name"=>"d"}}, "post_date"=>"2015-11-03T08:17:04.536Z", "@version"=>"1", "@timestamp"=>"2015-11-03T10:35:43.457Z", "host"=>"127.0.0.1", "type"=>"deckard2"}]]
HTTP_CLIENT: index {:_id=>nil, :_index=>"bla", :_type=>"deckard2", :_routing=>nil} {"ww"=>{"id"=>2222, "data"=>{"a"=>"b", "description"=>"c", "name"=>"d"}}, "post_date"=>"2015-11-03T08:17:04.536Z", "@version"=>"1", "@timestamp"=>"2015-11-03T10:35:43.457Z", "host"=>"127.0.0.1", "type"=>"deckard2"}
BULK: [{"index"=>{:_id=>nil, :_index=>"bla", :_type=>"deckard2", :_routing=>nil}}, {"ww"=>{"id"=>2222, "data"=>{"a"=>"b", "description"=>"c", "name"=>"d"}}, "post_date"=>"2015-11-03T08:17:04.536Z", "@version"=>"1", "@timestamp"=>"2015-11-03T10:35:43.457Z", "host"=>"127.0.0.1", "type"=>"deckard2"}]
BULK 2: {"index":{"_id":null,"_index":"bla","_type":"deckard2","_routing":null}}
{"ww":{"id":2222}}
{"a":"b","description":"c","name":"d"}
CLIENT: {"index":{"_id":null,"_index":"bla","_type":"deckard2","_routing":null}}
{"ww":{"id":2222}}
{"a":"b","description":"c","name":"d"}
LLLLLLLLLLLLLLLL: 500 {"index":{"_id":null,"_index":"bla","_type":"deckard2","_routing":null}}
{"ww":{"id":2222}}
{"a":"b","description":"c","name":"d"}
```

Attempted to send a bulk request to Elasticsearch configured at '["http://localhost:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["http://localhost:9200/"], :ssl=>nil, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :level=>:debug, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"[500] {\"error\":\"IllegalArgumentException[Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]]\",\"status\":500}", :error_class=>"Elasticsearch::Transport::Transport::Errors::InternalServerError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in`perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:120:in`perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:89:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:57:in`bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:356:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in`synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:351:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:385:in`flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in`each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in`buffer_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:344:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80:in`handle'", "(eval):27:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252:in`outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169:in `start_outputs'"], :level=>:error, :file=>"logstash/outputs/elasticsearch.rb", :line=>"399", :method=>"flush"}

**Comment by suyograo** [comment]
From https://github.com/elastic/elasticsearch-ruby/issues/234#issuecomment-153368522

I just installed logstash-2.0.0 from https://download.elastic.co/logstash/logstash/logstash-2.0.0.tar.gz

Yes, I try to push a document with a data property through logstash. 
{"ww":{
   "id":2222,
   "data":{"a":"b","description":"c","name":"d"}
  },
"f":8770,"post_date":"2015-11-03T08:17:04.536Z"
}

**Comment by guyboertje** [comment]
Closing: can't recreate at this time.
