### ISSUE TITLE
add option to set _parent in order to properly handle parent-child relationships

### ISSUE THREAD

**Issue by drdebian** [logstash-plugins/logstash-output-elasticsearch#297]
As a user that deals with lots of relational tables that need to find their way into ES, I would like to be able to specify the correct parent when loading child documents using logstash. Currently, this is quite cumbersome (if it works properly at all).

The solution seems quite straightforward to me, the config should accept a "parent" parameter which is directly stored in the _parent metafield of ES. Bonus points for also handling routing to the right shard automatically.

**Comment by jimmyjones2** [comment]
Sames as #129?

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/307

**Comment by drdebian** [comment]
Thank you very much!
