### ISSUE TITLE
Logstash sometimes doesn't send data to ElasticSearch

### ISSUE THREAD

**Issue by ThomasdOtreppe** [logstash-plugins/logstash-output-elasticsearch#301]
For a weird reason, the following logs (and probably others) aren't stored in ElasticSearch:

```
{"message":"'htpasswd' checksum test failed for /etc/nginx/.htpasswd","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"error"}
{"message":"'logstash_conf' timestamp was not changed for /etc/logstash/conf.d","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"info"}
{"message":"'logstash' process PID changed from 18232 to 18462","@version":"1","@timestamp":"2015-01-10T16:35:07.000Z","host":"ubuntu","path":"/var/log/monit.log","type":"monit","loglevel":"error"}
```

Here are the 3 lines coming from the log file:
```
[MST Nov 10 09:35:07] error    : 'htpasswd' checksum test failed for /etc/nginx/.htpasswd
[MST Nov 10 09:35:07] error    : 'logstash' process PID changed from 18232 to 18462
[MST Nov 10 09:35:07] info     : 'logstash_conf' timestamp was not changed for /etc/logstash/conf.d
```

And here is the config file for monit:
```
input {
        file {
                path => '/var/log/monit.log'
                sincedb_path => "/var/logstash/monit.db"
                sincedb_write_interval => 1
                type => 'monit'
        }
}

filter {
        if [type] == 'monit' {
                grok {
                        match => [ 'message', '%{SYSLOG5424SD:timestamp_noyear} %{LOGLEVEL:loglevel}%{SPACE}: %{GREEDYDATA:message}' ]
                        overwrite => 'message'
                }
                ruby {
                        init => "require 'time'"
                        code => "Time.strptime(event['timestamp_noyear'], '[%Z %b %d %H:%M:%S]') - Time.now > 2500000 ? event['year'] = Time.now.year - 1 : event['year'] = Time.now.year"
                }
                mutate {
                        add_field => {
                                "timestamp" => "%{timestamp_noyear} %{year}"
                        }
                }
                date {
                        match => [ "timestamp", "[zzz MMM DD HH:mm:ss] yyyy", "[zzz MMM  D HH:mm:ss] yyyy" ]
                        locale => "en"
                        remove_field => [ "timestamp", "timestamp_noyear", "year" ]
                }
        }
}
```

Here are the ouputs:
```
output {
        file {
                path => "/home/logstash/issue.json"
                codec => "json"
        }
}
```

and the other output configuration file:
```
output {
        elasticsearch {
                host => [ localhost ]
                protocol => "http"
        }
}
```

It seems like everything from monit (and most likely others) isn't stored at all and there is no log whatsoever about it in /var/log/logstash (besides the stdout file saying that everything is being redirected to /var/log/logstash/logstash.log): the files are empty.

System info:

 * Ubuntu 14.04.3 64bit LTS
 * Logstash 1.5.5
 * Official JDK 8
 * ElasticSearch 1.7.3

**Comment by guyboertje** [comment]
@ThomasdOtreppe - I have tried to recreate your problem locally but I do get entries in ES.

How do you know you are not getting these documents into ES?

**Comment by ThomasdOtreppe** [comment]
I can see data logged to the file and they're not present in Kibana/ElasticSearch.

**Comment by guyboertje** [comment]
@ThomasdOtreppe - I meant what index did you query on in ES to verify that they are not there.  There is an error in your filter chain that means the timestamp is being created as `2015-01-10T16:35:07.000Z` and that means they are likely to be in a different index from what you are expecting.

**Comment by ThomasdOtreppe** [comment]
I didn't notice the date parsed is wrong and I guess I was looking at the wrong index.

**Comment by ThomasdOtreppe** [comment]
How come the date is wrongly parsed? I don't see what's wrong in the date match.

**Comment by guyboertje** [comment]
I did not have time to look into what is wrong.  But then again I am not the best person to help with the date filter.

I suggest you close this issue and seek help from the wider community on https://discuss.elastic.co/c/logstash
