### ISSUE TITLE
Remove the master only nodes from the hosts list auomaticly when using sniffing 

### ISSUE THREAD

**Issue by ESamir** [logstash-plugins/logstash-output-elasticsearch#303]
In 2.0 the sniffing  setting asks Elasticsearch for the list of all cluster nodes and adds them to the hosts list. This will return ALL nodes with HTTP enabled (including master nodes!). 
it will be safer if we remove the master only nodes automatically.

**Comment by andrewvc** [comment]
You're 100% that we should be doing this :) . We plan on doing this very soon.

**Comment by astefan** [comment]
+1 on this. Sending indexing requests to the master node can cause serious stability issues. Especially given that, usually, a master only node doesn't need as many hardware resources as a data node and it is usually a low powered node.

**Comment by blavoie** [comment]
Is disabling http port (9200) on master nodes a good workaround, and also good practice?
Let them only communicate for cluster stuff...
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#_disable_http

**Comment by tomsommer** [comment]
+1

**Comment by jrbeilke** [comment]
@andrewvc would you mind taking a look at my open PR to implement improved sniffing of elasticsearch data nodes? I believe that should resolve this issue and #599

**Comment by andrewvc** [comment]
Fixed in #694
