### ISSUE TITLE
sniffing in logstash 2.0.0 results in file_descriptor exhaustion

### ISSUE THREAD

**Issue by vlaadbrain** [logstash-plugins/logstash-output-elasticsearch#306]
When Sniffing is enabled. within logstash-output-elasticsearch (2.1.2).  the call to client.transport.reload_connections! builds __new__ connections without reaping old ones.  this causes elasticsearch client nodes to run out of file_descriptors

I've also posted this issued https://github.com/elastic/elasticsearch-ruby/issues/241 for the elasticsearch transport.

**Comment by magnusbaeck** [comment]
Also reported here: https://discuss.elastic.co/t/logstash-too-many-open-files/35589

**Comment by jsvd** [comment]
We're addressing this in elasticsearch-ruby and manticore, more info in https://github.com/elastic/elasticsearch-ruby/issues/241#issuecomment-159946526

**Comment by suyograo** [comment]
Fixed via elasticsearch-ruby release 1.0.15 https://github.com/elastic/elasticsearch-ruby/commit/eab9444055577c7c644f039055faca595dd29378

**Comment by jsvd** [comment]
version 2.2.0 of this plugin has been released which includes #322 that ensures https://github.com/elastic/elasticsearch-ruby/commit/eab9444055577c7c644f039055faca595dd29378 works without race conditions

**Comment by anelson-vidscale** [comment]
Which version of logstash contains this fix?
