### ISSUE TITLE
Allow http output to non-root url

### ISSUE THREAD

**Issue by sfritz** [logstash-plugins/logstash-output-elasticsearch#31]
I have a proxy in front of my es cluster.  I'm proxying requests to http://nginx.example.local/elasticsearch through to one of my elasticsearch nodes (eg http://es1.example.local:9200/).  The plugin doesn't appear to allow output to a non-root url, since it expects a host name instead of a url.  

Currently (logstash-1.4.2), the following configuration sends requests to nginx.example.local/elasticsearch:80, rather than nginx.example.local:80/elasticsearch:

```
output {
  elasticsearch {
    protocol => "http"
    host => "nginx.example.local/elasticsearch"
    port => "80"
  }
}
```

I'd like to be able to configure a path:
```
output {
  elasticsearch {
    protocol => "http"
    host => "nginx.example.local"
    path => "/elasticsearch"
    port => "80"
  }
}
```

**Comment by andrewvc** [comment]
Good news! This was added quite a while ago! Thanks for the suggestion though @sfritz
