### ISSUE TITLE
Adjust manage_template's order to higher than zero.

### ISSUE THREAD

**Issue by jeesim2** [logstash-plugins/logstash-output-elasticsearch#325]
Hello.

There is really annoying and easy to make a mistake problem to me.

I have defined my own elasticsearch template for logstash-*
```
/_template/default_template
{
  "default_template": {
    "order": 0,
    "template": "logstash-*",
    "settings": {
      "index.number_of_replicas": "4",
      "index.number_of_shards": "1"
    },
    "mappings": {
      "_default_": {
        "dynamic_templates": [
          {
            "string_match": {
              "mapping": {
                "index": "not_analyzed",
                "type": "string",
                "doc_values": true
              },
              "match_mapping_type": "string",
              "match": "*"
            }
          },
          {
            "other": {
              "mapping": {
                "doc_values": true
              },
              "match_mapping_type": "*",
              "match": "*"
            }
          }
        ],
        "_all": {
          "enabled": false
        }
      }
    }
  }
}
```

So I configured logstash.conf to use already defined template by
```
output {
                elasticsearch {
                        index => "logstash-%{+YYYY.MM.dd}"
                        document_type => "......."
                        hosts => ["....."]
                        manage_template => false // <-- setting this false.
                        workers => 2
                }
...
```

But if someone me or other one run ANY logstash-elasticsearch job
with configuration like this by mistake or not awared about manage_template...
```
                elasticsearch {
                        index => "someindex..........."
                        document_type => "usertext"
                        hosts => ["....."]
                        workers => 2
                }

// not set
manage_template => false
```
this will create a new template to the cluster something like,
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json
(it's order will be 0 automatically).

In that situation,
templates 'dynamic_template' and 'logstash'  are both matched "logstash-XXXX",
and the order of both of them are '0'.
but always new index matched with logstash's default template.

If I do not noticed unexpected template creation (logstash's default tempalte).
really really hard work will happen tomorrow.
Because a new logstash-index created by template (logstash' default).
when this happen I have to spend all day to delete the wrong indexed index, and reindex it.

Due to logstash's daily index created according to UTC 
It is also hard to delete some local days documents spread to 2 index.

My idea is, How about define 'order' and set the value higher than 0 , for example 10 ?
so if logstash template created, user created template will selected to the new index.

**Comment by untergeek** [comment]
The easiest way is to name your template `logstash` instead of `default_template`.  It is this name that the output plugin looks for.  If it finds a pre-existing template named `logstash`, it will not overwrite it or add another, unless you have `template_overwrite => true`.

**Comment by jeesim2** [comment]
@untergeek  OK, thanks.
I will try it.
