### ISSUE TITLE
null host exception

### ISSUE THREAD

**Issue by Bradox** [logstash-plugins/logstash-output-elasticsearch#33]
My LS configuration is:

```
input {
    stdin{}
}

output {
      elasticsearch {
              cluster => "logstash"
              index => "rabbit-logstash-%{+YYYY.MM.dd}"
        }
}
```

On debug I see that the host it's not set

New Elasticsearch output {:cluster=>"logstash", :host=>nil, :port=>"9300-9305", :embedded=>false, :protocol=>"node", :level=>:info, :file=>"logstash/outputs/elasticsearch.rb", :line=>"319"}

Then I get this exception when events reach to LS:

Failed to flush outgoing
``` items {:outgoing_count=>1, :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/home/alejandro/devel/logstash-official/vendor/plugins/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:380:in `flush'", "/home/alejandro/devel/logstash-official/vendor/plugins/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:378:in `flush'", "/home/alejandro/devel/logstash-official/vendor/plugins/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:375:in `flush'", "/home/alejandro/devel/logstash-official/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/home/alejandro/devel/logstash-official/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/alejandro/devel/logstash-official/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/buffer.rb:159:in `buffer_receive'", "/home/alejandro/devel/logstash-official/vendor/plugins/jruby/1.9/gems/logstash-output-elasticsearch-0.1.9-java/lib/logstash/outputs/elasticsearch.rb:372:in `receive'", "/home/alejandro/devel/logstash-official/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):28:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/alejandro/devel/logstash-official/lib/logstash/pipeline.rb:272:in `output'", "/home/alejandro/devel/logstash-official/lib/logstash/pipeline.rb:231:in `outputworker'", "/home/alejandro/devel/logstash-official/lib/logstash/pipeline.rb:160:in `start_outputs'"], :level=>:warn, :file=>"stud/buffer.rb", :line=>"231"}
```

The exception is thrown here:

 @logger.debug? and @logger.debug "Sending bulk of actions to client[#{@client_idx}]: #{@host[@client_idx]}"

Seems like @host is null so it throws the exception. Host should have been initialized.

**Comment by talevy** [comment]
Hey @Bradox. I am unable to recreate this issue. Are you sure you have Elasticsearch configured to accept multicast connections? When using the `node` protocol without a `host` set, the plugin client discovers the Elasticsearch Cluster using Multicast.

Please verify that your ES cluster is running within the same network, and that this line is not 
present in the `elasticsearch.yml` config file: `discovery.zen.ping.multicast.enabled: false`

I have added extra comments here making this clearer: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/40

Please let me know if you think this may be the cause of the issue. If you are still having issues, please let us know!

Thanks

**Comment by suyograo** [comment]
Please reopen this issue if you encounter it again
