### ISSUE TITLE
Updated to 2.3.1 and receiving no such file to load for httpclient-4.5

### ISSUE THREAD

**Issue by thehybridtechnician** [logstash-plugins/logstash-output-elasticsearch#335]
Ran a logstash update which upgraded logstash-output-elasticsearch to 2.3.1.  Upon starting Logstash, I received the following error.  I downgraded logstash-output-elasticsearch to 2.3.0 and I am back up and running.

````
The error reported is:
    you might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command

no such file to load -- org/apache/httpcomponents/httpclient/4.5/httpclient-4.5 (LoadError)
/opt/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.1/lib/jar_dependencies.rb:367:in `do_require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.1/lib/jar_dependencies.rb:282:in `require_jar'
/opt/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.1/lib/jar_dependencies.rb:0:in `require_jar_with_block'
/opt/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.1/lib/jar_dependencies.rb:281:in `require_jar'
/opt/logstash/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.1/lib/jar_dependencies.rb:376:in `require_jar'
/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore_jars.rb:4:in `(root)'
org/jruby/RubyKernel.java:1040:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
file:/opt/logstash/vendor/jruby/lib/jruby.jar!/jruby/kernel19/kernel.rb:1:in `(root)'
file:/opt/logstash/vendor/jruby/lib/jruby.jar!/jruby/kernel19/kernel.rb:13:in `require_relative'
org/jruby/RubyKernel.java:1040:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore.rb:5:in `(root)'
org/jruby/RubyKernel.java:1040:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:1:in `(root)'
org/jruby/RubyKernel.java:1040:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:1:in `(root)'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.3.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:1:in `(root)'
org/jruby/RubyKernel.java:1040:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.3.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:5:in `(root)'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.3.1-java/lib/logstash/outputs/elasticsearch.rb:1:in `(root)'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.3.1-java/lib/logstash/outputs/elasticsearch.rb:49:in `ElasticSearch'
org/jruby/RubyKernel.java:1079:in `eval'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.3.1-java/lib/logstash/outputs/elasticsearch.rb:48:in `(root)'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/plugin.rb:1:in `(root)'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/plugin.rb:80:in `lookup'
org/jruby/RubyProc.java:281:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:304:in `plugin'
org/jruby/RubyProc.java:281:in `call'
(eval):11:in `initialize'
````

**Comment by sc0rp10** [comment]
+1

**Comment by sysmonk** [comment]
I've got the same issue, which kinda makes any installs / updates impossible. 

Logstash 2.1.0 here, issue began after running bin/plugin update.

**Comment by aschaef** [comment]
+1 I've got the same issue after running bin/plugin update. Any fix in the meantime?

**Comment by fw8** [comment]
+1 Downgrade to 2.3.0 didn't help (-> could not find compatible versions for gem "manticore")

**Comment by aschaef** [comment]
I saw an error when running bin/plugin update which showed:

Error Bundler::InstallError, retrying 2/10
An error occurred while installing manticore (0.5.2), and Bundler cannot continue.
Make sure that `gem install manticore -v '0.5.2'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported

If I try running `gem install manticore -v '0.5.2'` I just get the error:

ERROR:  Could not find a valid gem 'manticore' (= 0.5.2), here is why:
          Found manticore (0.5.2), but was for platform java
ERROR:  Possible alternatives: MINT-core, handscore, antidote, antinode, fat_core

**Comment by aschaef** [comment]
I've got a fix which just worked for me. I re-pointed my gem install command to use jruby packed with logstash and found that manticore 0.5.2 was failing to install due to a missing dependency with ruby-maven-3.3.8. The following 2 commands got me back up and running with logstash-output-elasticsearch v2.3.1:

`[user@host ~]# env GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 /opt/logstash/vendor/jruby/bin/jruby /opt/logstash/vendor/jruby/bin/gem install ruby-maven`

this installed the lastest v.3.3.8 and then I ran

`[user@host ~]# env GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 /opt/logstash/vendor/jruby/bin/jruby /opt/logstash/vendor/jruby/bin/gem install manticore -v '0.5.2'`

after that install completed successfully I was able to restart logstash. Hope this helps!

**Comment by suyograo** [comment]
We are discussing this in: https://discuss.elastic.co/t/logstash-2-1-fails-to-start-after-logstash-output-elasticsearch-update/38330/5

Lets follow up tehre

**Comment by akshatiitj** [comment]
+1

**Comment by davidsmandrade** [comment]
+1
