### ISSUE TITLE
Move "flushing buffer at interval messages" to debug level?

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#336]
It looks like we are now writing out the full contents of the buffer at the info/verbose level which can drown other more useful info messages.

```
Flushing buffer at interval {:instance=>"#<LogStash::Outputs::ElasticSearch::Buffer:
```

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/06ea707f1891201020e67ebe680838be2036adee/lib/logstash/outputs/elasticsearch/buffer.rb#L90

Have we considered writing this only to the debug level?

**Comment by andrewvc** [comment]
That is a good call @ppf2 , it's very irritating. The good news is that with LS 2.2 this plugin no longer manages its own buffer and will never need to log this.

**Comment by andrewvc** [comment]
That being said, we should fix this.
