### ISSUE TITLE
add rate limiting

### ISSUE THREAD

**Issue by djschny** [logstash-plugins/logstash-output-elasticsearch#338]
@cdahlqvist and I were talking earlier today and would really like to see rate limiting in the ES output plugin. This has multiple uses/benefits:

* Sometimes you want to throttle or limit how fast ingestion happens to make sure it does not negatively impact your search performance. This would allow that.
* During testing for capacity planning and other exercises, controlling how fast the indexing happens is important.

Obviously this would default to off, but you can control based upon delay in between bulk requests, or similar.

**Comment by andrewvc** [comment]
@djschny shouldn't rate limiting happen at the Elasticsearch level? (maybe by reducing queue sizes or threadpool settings?). 

If we do decide to implement rate limiting, FWIW, I believe we should do so at the logstash pipeline level, not in individual plugins. It could be a standard option for outputs added by the Outputs::Base class. 

What do you think?

**Comment by djschny** [comment]
Negative, rate limiting at the Elasticsearch level would be bad in this situation and is not what is needed. The rate limiting on the ES side should be set for the max of what the cluster can take in general. When you adjust that, you affect __all__ clients as opposed to selective ones.

Imagine a situation where you have bulk ingestion happening via LS pipeline and while it is important, it is secondary compared to the indexing that is happening by a different application layer. In that situation we want a controlled/sustained index rate from the LS pipeline, but we want the app layer to go as fast as it needs to.

Yeah, pipeline level sounds great, it then can benefit all output plugins.

**Comment by jordansissel** [comment]
You can achieve rate limiting today by combining the throttle filter with
the sleep filter. It may not be the best feeling solution, but it will work.

**Comment by suyograo** [comment]
FYI, we have a throttle filter which controls the rate of flow of events https://www.elastic.co/guide/en/logstash/current/plugins-filters-throttle.html

**Comment by jordansissel** [comment]
The throttle filter detects the throttle condition but the action not takes
is mostly just to tag the event. To stall the pipeline you want to use the
sleep filter on events tagged by throttle filter.

**Comment by djschny** [comment]
That's awesome guys. It will work when you want to throttle __all__ events and not just ones destined to a specific output, but this is totally acceptable in my book. I can close the ticket, sorry for not seeing this before.
