### ISSUE TITLE
date math in index

### ISSUE THREAD

**Issue by stdweird** [logstash-plugins/logstash-output-elasticsearch#346]
we are try to create a quarterly index in elasticsearch with the ES output, but so far we don't seem to succeed.

can we use date math or some other expressions (like `+YYYY.Q`) or somethign like that?

**Comment by itkovian** [comment]
According to the error the above raises, I see we can use these: http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

So, would it be possible to compute the quarter in the config from the datestamp of the message and use that to create an index-name?

**Comment by andrewvc** [comment]
@stdweird The best way to do that would be to add a 'quarter' field to each event in the filter stage and write the events to 'logstash-%{[quarter]}'.

For non-bug questions please use https://discuss.elastic.co/c/logstash instead of the github issues. Thanks! (closing for this reason)
