### ISSUE TITLE
ES output plugin creates 2016.02.32, 2016.02.33, etc.. indices after month switchover

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#354]
One way to reproduce this is to use the topbeats input and have topbeats send events to Logstash. And turn back time on your laptop to just before the UTC midnight switchover between 1/31 and 2/1 and see the topbeat-2016.02.32 index gets created after topbeat-2016.01.31.  On LS 2.1.1 and topbeats 1.0.1.

```
input
{
beats {
    port => 33333
}
}

output 
{ 

elasticsearch 
{ 
workers => "2" 
manage_template => false 
index => "topbeat-%{+YYYY.MM.DD}" 
} 
}
```

It does not seem like a beats issue because beats is generating the right timestamp in its records.  And it doesn't seem like a beats input issue because I can confirm that the @timestamp is correct by printing out the events in a filter.

This is looking like an ES output plugin issue since the very first document in the resulting topbeat-2016.02.32 has a @timestamp of 2016-02-01T00:00:04.194Z.

```
[2016-01-31 16:00:05,976][INFO ][cluster.metadata         ] [node-1] [topbeat-2016.02.32] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings [process, filesystem]
```

```
{
  "took": 54,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 189,
    "max_score": null,
    "hits": [
      {
        "_index": "topbeat-2016.02.32",
        "_type": "process",
        "_id": "AVKaIRfJyKlqeqah4CCw",
        "_score": null,
        "_source": {
          "@timestamp": "2016-02-01T00:00:04.194Z",
          "beat": {
            "hostname": "Iceman",
            "name": "Iceman"
          },
          "count": 1,
          "proc": {
            "cpu": {
              "user": 33,
              "user_p": 0,
```

Not able to reproduce this using the generator input though, so perhaps it is related the bursts of events within the same @timestamp coming from topbeats.  For example, in this case, there are 8 events sharing the same 2016-02-01T00:00:04.194Z @timestamp in the resulting index.

**Comment by ppf2** [comment]
topbeat-2016.01.30 
topbeat-2016.01.31 <------ happens after month switchover
topbeat-2016.02.32
topbeat-2016.02.33

**Comment by masaruh** [comment]
I think it's because index pattern is `topbeat-%{+YYYY.MM.DD}` instead of `topbeat-%{+YYYY.MM.dd}`. `D` is "day in year".

**Comment by suyograo** [comment]
good catch @masaruh @tsg where is beats default index for LS defined?

**Comment by suyograo** [comment]
LS uses Joda to format the index pattern. Joda formats are defined here: http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

`D` is day in year as @masaruh mentioned

**Comment by ppf2** [comment]
Good catch @masaruh ! Updated [doc](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common_configs.rb#L9) with Joda format reference.
