### ISSUE TITLE
HTTP 429 should not log as a warning

### ISSUE THREAD

**Issue by pickypg** [logstash-plugins/logstash-output-elasticsearch#372]
HTTP 429 is part of normal behavior to indicate backoff behavior from ES:

```
{:timestamp=>"2016-02-25T08:01:46.196000-0800", :message=>"retrying failed action with response code: 429", :level=>:warn}
```

Seeing it as a warning really kind of indicates that something is wrong rather than a notification. It seems like logging this at info level (or even debug) may be more appropriate to avoid scaring people.

**Comment by jordansissel** [comment]
We can move this to info-level logging. That would make them hidden by default but shown when --verbose or --debug flags are used.

**Comment by acchen97** [comment]
Resolved with https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/373.
