### ISSUE TITLE
Update template to ES

### ISSUE THREAD

**Issue by paltryeffort** [logstash-plugins/logstash-output-elasticsearch#380]
Hi,
I am referring to my problem https://github.com/elastic/elasticsearch/issues/16698 but I guess here is the better place to ask.
I observed the following:
On startup, logstash-output-elasticsearch sends the specified template to ES. However, if ES is at that time not available (not running, network issue etc) the template never gets send to ES even if it's reachable at some point. The data gets send to ES eventually but not the template.
I set template_overwrite to true but I guess this only has effect if the template on the logstash local disk changed.

Shouldn't the plugin make sure that it sends the template successfully to ES before sending any data?

**Comment by andrewvc** [comment]
Apologies for the delay. This was fixed a long time ago. Please update to the latest and open a new issue if you have further problems.
