### ISSUE TITLE
doc_as_upsert and other update options does not intitalized if action set dinamicaly

### ISSUE THREAD

**Issue by kiryam** [logstash-plugins/logstash-output-elasticsearch#383]
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client_builder.rb#L38

```
common_options.merge! update_options if params["action"] == 'update'
```

Client class creating while plugin initialization and if option "action" set like this:  
action => "%{[@metadata][action]}" i.e. "dynamically" 

All "update options" will not set

```
update_options = {
        :doc_as_upsert => params["doc_as_upsert"],
        :script_var_name => params["script_var_name"],
        :script_type => params["script_type"],
        :script_lang => params["script_lang"],
        :scripted_upsert => params["scripted_upsert"]
      }
```

**Comment by sebesvn** [comment]
Hey there,

I ran into this issue myself today.
Could we have an update for a possible fix?

Thanks a lot!

**Comment by satheeshravirintern** [comment]
Issue still exist in logstash 2.4 . Not sure about 5.0.

**Comment by guillaumeautran** [comment]
I'm also experiencing the issue in logstash 2.4 Does anyone know if this is addressed in 5.0 versions?

**Comment by phoenixgao** [comment]
Issue still exist 5.4.2, could someone review https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/385 and merge?

**Comment by agaoglu** [comment]
Can confirm on 5.6.0.

**Comment by ItamarBenjamin** [comment]
still happens on 6.2
fix is available #239 , why isn't it merged already?

**Comment by jsvd** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/385 was merged, closing this.

**Comment by mihomir** [comment]
I may be missing something, but I am experiencing the same issue with the elasticsearch-output plugin 9.2.4. And when I looked at that MR #385, I specifically don't see "doc_as_upsert" as being handled for an update action.
