### ISSUE TITLE
https URLs should set ssl options

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#388]
Using an HTTPS URL will ignore custom keystore settings, this needs to be fixed.

**Comment by jsvd** [comment]
The more I tried to implement a fix for this, the more I think this is not a good approach..
Supporting full schemas in hosts array just leads to potential issues..theoretically you can do:

`hosts => ['https://localhost:9200', 'http://localhost:9201']`

what if we force :ssl to be set and restrict hosts to be a list of "host:ip" ?

**Comment by andrewvc** [comment]
I actually think we should do this because it's a better user experience.
We should raise an error if https and http are mixed.

**Comment by jsvd** [comment]
I don't see how:

```
elasticsearch {
  hosts => ['https://host1.local.lan:9200', 'http://host1.local.lan:9201']
}
```

is better than:

```
elasticsearch {
  hosts => ['host1.local.lan:9200', 'host1.local.lan:9201']
  ssl => true
}
```

the second seems less noisy and less error prone than the first.
Also, b/c of the way the ssl and hosts options are handled, it's a bit awkward to make one depend on the other. Anyway, if you feel strongly about this we can do it, I'll add the extra validation.

**Comment by andrewvc** [comment]
@jsvd the rationale is that people are more familiar with the URL syntax and it's easier for hosted services like Found that express their endpoinst as URLs. 

I agree that with a large host list it isn't as nice, but we support both syntaxes.

I'm glad to discuss the pros and cons here, but given that we've already released this I'd rather not go back and take away a new feature people may already be using.

This syntax is much nicer when people are using paths as well, such as `http://foo.bar/proxy-path`.

I would personally like to figure out a way to get usernames/passwords in there in a secure way as well. This would be great for elastic cloud where the config page lists the full URL as the endpoint. A user could just copy/paste that in.

**Comment by andrewvc** [comment]
I'll just add that the only reason we don't support user/password in there now is that we don't have a secure way of hiding a portion of a config option.

**Comment by jsvd** [comment]
this was addressed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/e7259de52f88643cc3311ce73d4dfa4663041a87
