### ISSUE TITLE
Sniffing in 2.2.2 causes memory leak & OOM

### ISSUE THREAD

**Issue by spuzon** [logstash-plugins/logstash-output-elasticsearch#392]
Hi,
   I run few instances of logstash, since upgrade to 2.2.2 i started to notice permanent crashes caused by OOM errors. Bigger heap only increase interval between OOMs. I checked heap dump and found excessive amount of **org.apache.http.config.Registry** objects. 

Out of 3GB I had 887000 Registries taking 1.4GB of memory.
![screen shot 2016-03-14 at 8 39 01 am](https://cloud.githubusercontent.com/assets/7383511/13737791/3f454496-e9c0-11e5-9769-e9a9f8f2f614.png)

I started to monitory tenured memory utilization and amount of Registries object instances on the heap for each logstash instance.

**Number of Registry objects 1GB heap (jmap -gchisto)**

![screen shot 2016-03-14 at 8 38 16 am](https://cloud.githubusercontent.com/assets/7383511/13738001/e4b23c12-e9c1-11e5-8633-f85277803fa8.png)

**Tenured memory utilization 1GB heap (jstat -gcutil)**
![screen shot 2016-03-14 at 8 41 41 am](https://cloud.githubusercontent.com/assets/7383511/13738006/eeda75e2-e9c1-11e5-881f-bb92323e24d8.png)

Drops from 85% to few percent indicate watchdog killed process as there was no point to waste CPU due to CMS cycles as memory won't be recycled.

You may notice one series of data on those screenshots that looks pretty fine, that's instance with sniffing set to false, all others had sniffing => true

Once disabled sniffing on all instances the problem is gone.

**Disabled Sniffing: Number of Registry objects 1GB heap (jmap -gchisto)**
![screen shot 2016-03-14 at 8 54 32 am](https://cloud.githubusercontent.com/assets/7383511/13738066/67883a6a-e9c2-11e5-9961-4beacc47c148.png)

**Comment by jsvd** [comment]
I've done some investigation and it is possible that the HttpClient objects from Manticore aren't being freed..my findings are in https://github.com/cheald/manticore/issues/45

**Comment by suyograo** [comment]
This has been fixed in version 2.5.3.Many thanks to @jsvd and @cheald. 

To install this you can do: 

`bin/plugin install --version 2.5.3 logstash-output-elasticsearch`

**Comment by cheald** [comment]
FWIW, Manticore::Client instances are intended to be create-once-reuse-many. If you're frequently creating new instances, that's highly suboptimal; Clients are fully threadsafe and may be created once and then shared among arbitrarily many workers. All the work is managed by the Client's backing pool. This class of leak is likely because of frequent Manticore::Client instantiation.

I'll poke around a bit in the plugin and see how it's being used - might be that we can find a more efficient way to use Manticore :)

**Comment by cheald** [comment]
It actually looks like this was recently changed. elastic/elasticsearch-ruby@067842d46ac826ebf49f16bdc5dea71b96ae3366 looks like it should sidestep the many-instances issue, combined with today's fixes should make Manticore _much_ more friendly to user resources!

**Comment by suyograo** [comment]
@cheald thanks. @andrewvc has been working to make our Manticore usage more efficient. See https://github.com/elastic/elasticsearch-ruby/pull/281. 

We would love any feedback though :)
