### ISSUE TITLE
Migrating logstash 1.5.4 to Logstash 2.2

### ISSUE THREAD

**Issue by jay-dihenkar** [logstash-plugins/logstash-output-elasticsearch#395]
Hi,

How do I migrate this block to logstash 2.2 es output : 

```
elasticsearch {
                host => "xx.xx.xx.xx"
                port => "8084"
                ssl => true
                ssl_certificate_verification => false
                protocol => "http"
                path => "/path-to/elasticsearch"
                user => "username"
                password => "password"
                idle_flush_time => 1
                flush_size => 5000
                retry_max_interval => 10
        }
```

The `ssl => true` and `http` are not working togather!!

I get this : 

```
{:timestamp=>"2016-03-15T16:19:49.231000+0530", :message=>"** WARNING ** Detected UNSAFE options in elasticsearch output configuration!\n** WARNING ** You have enabled encryption but DISABLED certificate verification.\n** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true", :level=>:warn}
Error: You specified a plain 'http' URL 'http://xx.xx.xx.xx:8084/path-to/elasticsearch' but set 'ssl' to true! Aborting!
```

**Comment by jsvd** [comment]
this plugin now is dedicated to http/https, so you can just use ssl => true and remove the "protocol => http"

**Comment by jay-dihenkar** [comment]
Already tried...! I updated the config to : 
```
elasticsearch {
                hosts => ["http://xx.xx.xx.xx:8084"]
                ssl => true
                ssl_certificate_verification => false
                path => "/path-to/elasticsearch"
                user => "username"
                password => "password"
                idle_flush_time => 1
                flush_size => 5000
                retry_max_interval => 10
        }
```

produced the error I stated above!

Error : 
```
{:timestamp=>"2016-03-15T16:19:49.231000+0530", :message=>"** WARNING ** Detected UNSAFE options in elasticsearch output configuration!\n** WARNING ** You have enabled encryption but DISABLED certificate verification.\n** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true", :level=>:warn}
Error: You specified a plain 'http' URL 'http://xx.xx.xx.xx:8084/path-to/elasticsearch' but set 'ssl' to true! Aborting!
```

Suggest me the updated config!

**Comment by jsvd** [comment]
if you're using a full url the you need to use https:// instead of http://

**Comment by jay-dihenkar** [comment]
My URL is actually a `http` URL!

**Comment by jsvd** [comment]
sorry not sure I'm understanding, could you please try instead: 

```
elasticsearch {
                hosts => ["xx.xx.xx.xx:8084"]
                ssl => true
                ssl_certificate_verification => false
                path => "/path-to/elasticsearch"
                user => "username"
                password => "password"
                idle_flush_time => 1
                flush_size => 5000
                retry_max_interval => 10
        }
```

**Comment by jay-dihenkar** [comment]
Magically SOLVED! Thanks!

**Comment by jay-dihenkar** [comment]
I'm getting the same issue with logstash 2.3.3, logstash output elasticsearch v2.7.0 **but working for logstash output elasticsearch v2.5.1 with logstash 2.2.2**

Config : 

elasticsearch {
                hosts => [ "10.13.1.33:8080" ]
                user => "uname"
                password => "pass"
                idle_flush_time => 30
                flush_size => 100
                ssl => true
                ssl_certificate_verification => false
                path => "/dashboard/elasticsearch"
                retry_max_interval => 10
        }


Client protocol exception : 

{:timestamp=>"2016-06-30T15:21:42.877000+0530", :message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"https://10.13.1.33:8080/dashboard/elasticsearch/\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", :error_message=>"SSL peer shut down incorrectly", :error_class=>"Manticore::ClientProtocolException", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:37:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:79:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:256:in `call_once'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:153:in `code'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `perform_request'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.17/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.17/lib/elasticsearch/api/actions/bulk.rb:88:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `non_threadsafe_bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/common.rb:172:in `safe_bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/common.rb:101:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/common.rb:29:in `multi_receive'", "org/jruby/RubyArray.java:1653:in `each_slice'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.0-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:301:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:301:in `output_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :client_config=>{:hosts=>["https://10.13.1.33:8080/dashboard/elasticsearch/"], :ssl=>{:enabled=>true, :verify=>false}, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{:enabled=>true, :verify=>false}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :headers=>{"Authorization"=>"Basic YWRtaW46YWRtaW5wYXNz"}, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false, :http=>{:scheme=>"https", :user=>nil, :password=>nil, :port=>8080}}, :level=>:error}

**Comment by jsvd** [comment]
closing this as the initial issue was solved
