### ISSUE TITLE
append array of json

### ISSUE THREAD

**Issue by fadaytak** [logstash-plugins/logstash-output-elasticsearch#397]
hi,

how can i append an array on elasticsearch with json object using logstash from csv

exemple of csv

a csv containt lines id,key1,key2 1,toto1,toto2 1,titi1,titi2 2,tata1,tata2

the result should be 2 documents

```
{
    "id": 1,
    [{
        "key1": "toto1",
        "key2": "toto2"
    }, {
        "key1": "titi1 ",
        "key2": "titi2"
    }]
}
,{
    "id": 2,
    [{
        "key1": "tata1",
        "key2": "tata2"
    }]
}
```

cordially

**Comment by andrewvc** [comment]
Hi, this is not a bug but a howto question. Please ask it on https://discuss.elastic.co/c/logstash
