### ISSUE TITLE
Use correct templates based on Elasticsearch versions

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#401]
ES 5.0 has numerous mapping changes as described here https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/386. Much effort has been put into making this a backward compatible change recently, but we'd still like users to migrate to the new mapping settings and not carry the old cruft around. 

As such, we should:
* Ship both ES 2.x (old) and ES 5.0 (new) templates
* Enhance this plugin to detect if ES 5.0 is running (when the first attempt to upload template is made), and if so, use the 5.0 template version. If ES version 2.x is running, use the other template. 

**Note: We should do this only when default template is used and the existing template* configs should apply to both the versions**

We may need to introduce a new config option to select different paths for 5.0 and 2.x templates on disk.

**Comment by pickypg** [comment]
I came back to this issue to double check that this part was here:

> We should do this only when default template is used.

I just wanted to call it out for whoever implements it because otherwise it will break some things. :)

**Comment by suyograo** [comment]
Thanks @pickypg . Made it stick out :)

**Comment by tsg** [comment]
What does "force upgrade" mean? Overwrite it?

**Comment by suyograo** [comment]
@tsg when I mean't force upgrade, I actually meant forcing users to upgrade to a 5.0 template if they are running against ES 5.0. If they already have a `logstash` template, we wouldn't overwrite it.

**Comment by acchen97** [comment]
After discussion with @suyograo and @jordansissel we plan to backport this logic for 2.4 as well. Therefore, both LS 2.4 and 5.0 will have compatible default templates with both ES 2.x and 5.0.

**Comment by suyograo** [comment]
@jsvd moving this to @purbon

**Comment by suyograo** [comment]
@jsvd will start on this. 

For ref: beats did something similar as well: https://github.com/elastic/beats/pull/1993

**Comment by suyograo** [comment]
Fixed in #455
