### ISSUE TITLE
support for external version numbers in ES output plugin

### ISSUE THREAD

**Issue by ragogitpub** [logstash-plugins/logstash-output-elasticsearch#405]
ES supports external version numbers.

https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html

We have a need where we could be indexing ES with potentially same object from different places. 

But in case things go out of sync, we would like to provide our version number field.

This should work with bulk load.

This should also have capability to ignore the version conflict errors if one of the indexing requests in a batch fails.

**Comment by phongsiri-tr** [comment]
+1

**Comment by vvcephei** [comment]
This is especially important when indexing data that comes from a database, for exactly the same reason that ES supports OCC.

I'm writing an input plugin for EmoDB right now, and lack of document versioning is going to make it impossible for me to guarantee correctness. Once I get past prototype, I reckon I'll have to send a PR to add it, unless you're already planning to add it yourselves.

Thanks,
-John

**Comment by jordansissel** [comment]
You can provide a document id for each event using the `document_id` setting in the elasticsearch output - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_id

**Comment by vvcephei** [comment]
Thanks for the reply, Jordan.

Yep, I was aware that I can provide the document id. The issue is that, to
ensure the index stays in sync with the database, I need to use ES's
external version feature also. Basically, for any document coming from my
database, I would like to set the ES version equal to the db version number.

This way, if two updates arrive out of order for the same document, I can
be sure the later one will apply and the earlier one will be discarded.

Thanks,
John

**Comment by jordansissel** [comment]
Oh I see, I have completely  misread this. My bad :)

Thank you for helping clarify things for me.

**Comment by vvcephei** [comment]
No worries! I figured that was what happened. ;)

**Comment by vvcephei** [comment]
@jordansissel I think I want to go ahead and submit a PR for this.

I've read https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md, and I'll follow the guidelines.

Do you want to discuss design decisions, or should I troll for a design review in irc, or should I just put together a PR and discuss design there?

Mostly, it'll be fairly straightforward. The only odd thing I was thinking is that specifying a version to the elasticsearch output seems to imply you want to use external verisioning.

Do you think I should add two configurations (one for the version number and one for the version type, mirroring ES's api) or just the one (version number, with version_type=external implied)?

Thanks,
-John

**Comment by vvcephei** [comment]
note, this issue duplicates #279 and also #365, to some extent.

**Comment by vvcephei** [comment]
@ragogitpub @phongsiri-tr If you are interested, I have submitted PR #528 to address this issue.

**Comment by jsvd** [comment]
this was implemented in version 6.2.0 of this plugin through https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/528
