### ISSUE TITLE
Docs say to set retry_on_conflict however the setting does not exist

### ISSUE THREAD

**Issue by jjfalling** [logstash-plugins/logstash-output-elasticsearch#408]
https://www.elastic.co/guide/en/logstash/2.2/plugins-outputs-elasticsearch.html#_retry_policy shows the retry policy changed and if the user sees 409s then they should set `retry_on_conflict`, however this setting does not exist.

**Comment by andrewvc** [comment]
This will be addressed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/409 apologies for the issue!
