### ISSUE TITLE
Log errors when max retries reached and message is dropped

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#417]
We should log a warning/error when a document has reached its retry limit

or at least better document where to see the errors and what errors you can see in the logs.

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common.rb#L82

**Comment by ph** [comment]
I don't believe we should **not** drop message for any reason, we should just block forever..

**Comment by ph** [comment]
@andrewvc I think you went through the different uses cases we should support for the retry scenarios?
