### ISSUE TITLE
codec plugin is not support ?

### ISSUE THREAD

**Issue by WoolenWang** [logstash-plugins/logstash-output-elasticsearch#420]
Hi.
     I have a general usage to split the event to multi event so that i can insert into the elasticsearch with multi doc ( because the data was upload with in a package , the package was include many info need to split) , i have try to use filter plugin to split the event , but it seem to be very hard to split in a filter but in the codec i can simple call many times the block so i can split the event, then i try it with the stdout, it work but in the elasticsearch plugin it get something wrong, is that this plugin is not support codec?
- Version: logstash-2.2.2
- Operating System: Linux ubuntu 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it):
  elasticsearch {
      codec => split {
  
  ```
  }
  action => "index"
  hosts => "localhost:9200"
  index => "test_wwl1"
  document_type => "ac_one"
  timeout => 30
  workers => 2
  manage_template => false
  max_retries => 10
  retry_max_interval => 60
  ```
  
  }
- Sample Data: just some array in hash that i try to split event
- Steps to Reproduce:
  write a simple split codec plugin 

public
    def encode(event)
        @logger.info('get one event', :event => event)
        if event[@split_key].is_a? Hash
            @on_event.call event,LogStash::Event.new(event.to_hash.merge(event[@split_key]))
        elsif event[@split_key].is_a? Array
            array = event[@split_key]
            hash = event.to_hash.clone
            hash.delete @split_key
            array.each do |one_split|
                @on_event.call event,LogStash::Event.new(hash.merge(one_split))
            end
        else
            @on_event.call event,event
        end
    end

and then try to input one event with an array in @split_key so that it can work to split the event.

**Comment by andrewvc** [comment]
Codecs do not apply to this output since the event must always be converted to a JSON document. Look into using the split filter instead. 

Closing since this is the wrong place for this, and this is not an actual issue.
