### ISSUE TITLE
Failed index action (status: 400) due to unsupported index_name : tag parameter.

### ISSUE THREAD

**Issue by kan1207** [logstash-plugins/logstash-output-elasticsearch#436]
When I am trying to use logstash to read through a configuration file, I come up with map parsing error. 

>  :response=>{"index"=>{"_index"=>"logstash-2016.06.07",
> "_type"=>"txt", "_id"=>nil, "status"=>400,
> "error"=>{"type"=>"mapper_parsing_exception", "r eason"=>"Failed to
> parse mapping [_default_]: Mapping definition for [data] has
> unsupported parameters:  [ignore_above :  1024]",
> "caused_by"=>{"type"=>"mapper_parsing_exception", "reason"=>"Mapping
> definition for [data] has unsupported para meters:  [ignore_above :
> 1024]"}}}}, :level=>:warn}←[0m

I found that there is no problem is groking my logs but just do not know what is the matter of the error.

Here is my logstash.conf

```
input{
    stdin{}
    file{
        type => "txt"
        path => "C:\HA\accesslog\trial.log"
        start_position => "beginning"
    }
}
filter{
    grok{
    match => {"message" => ["%{IP:ClientAddr}%{SPACE}%{NOTSPACE:date}%{SPACE}%{TIME:time}%{SPACE}%{NOTSPACE:x-eap.wlsCustomLogField.VirtualHost}%{SPACE}%{WORD:cs-method}%{SPACE}%{PATH:cs-uri-stem}%{SPACE}%{PROG:x-eap.wlsCustomLogField.Protocol}%{SPACE}%{NUMBER:sc-status}%{SPACE}%{NUMBER:bytes}%{SPACE}%{NOTSPACE:x-eap.wlsCustomLogField.RequestedSessionId}%{SPACE}%{PROG:x-eap.wlsCustomLogField.Ecid}%{SPACE}%{NUMBER:x-eap.wlsCustomLogField.ThreadId}%{SPACE}%{NUMBER:x-eap.wlsCustomLogField.EndTs}%{SPACE}%{NUMBER:time-taken}"]}
        }

}
output{
    elasticsearch { hosts => ["localhost:9200"] 
    }
    stdout { codec => rubydebug }   
}
```

Please help. Thanks.

**Comment by jsvd** [comment]
this just seems to be an issue with the template. that said, this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
