### ISSUE TITLE
es output causes exceptions when using credentials

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#441]
Because manticore sets up auth+proxy in the same method and triggers this if either one is set (see https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L498)

Then, if in Logstash we set credentials, manticore also tries to set the proxy (see https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L532)

Manticore does `proxy = options.fetch(:proxy, {})`, and it receives the options from this plugin (see https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v3.0.2/lib/logstash/outputs/elasticsearch/http_client_builder.rb#L49-L63). If there are no proxy settings passed in this plugin the options hash contains `{:proxy => nil}`, it makes `options.fetch(:proxy, {})` return `nil`.

This then causes:

```
/tmp/logstash-5.0.0-alpha4 % bin/logstash -f ../logstash-5.0.0-alpha4/my.config
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
UNEXPECTED POOL ERROR {:e=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :level=>:warn}
undefined method `[]' for nil:NilClass {:class=>"NoMethodError", :level=>:error}
Pipeline main started
UNEXPECTED POOL ERROR {:e=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :level=>:warn}
An unknown error occurred sending a bulk request to Elasticsearch. We will retry indefinitely {:error_message=>"undefined method `[]' for nil:NilClass", :error_class=>"NoMethodError", :backtrace=>["/private/tmp/logstash-5.0.0-alpha4/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:550:in `auth_from_options'", "/private/tmp/logstash-5.0.0-alpha4/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:497:in `request_from_options'",
```

**Comment by andrewvc** [comment]
Thanks for the report @jsvd I will address this as part of my refactor in https://github.com/andrewvc/logstash-output-elasticsearch/tree/use-uri-type

**Comment by jsvd** [comment]
Since it's a big-ish refactor and alpha4 is planned to go out next tuesday I'd rather address this separately, but up to you

**Comment by andrewvc** [comment]
@jsvd yes, I agree. I take it you're working on a patch?
