### ISSUE TITLE
Retry TransportService errors

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#449]
```
 "status"=>500, "error"=>{"type"=>"transport_exception", "reason"=>"TransportService is closed stopped can't send request"}}
```

This error indicates that a downstream Elasticsearch node is shutting down. I believe we should retry the failing action when this error occurs because it is a temporary error.

**Comment by andrewvc** [comment]
This is certainly out of date now that we no longer support the transport protocol. Closing.
