### ISSUE TITLE
support compression of request bodies

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#454]
Since elasticsearch supports bulk indexing with compressed bulks, logstash should support this to reduce the size of requests

In 5.0 ES will, by default, support http compression in the requests if it comes with a `Content-Encoding: gzip|deflate`.
Since there is no compression setting negotiation for requests and this plugin will be able to send to both ES 2.x and 5.x for some time, this will either need to be disabled by default, or a version check needs to be executed against the ES cluster.

**Comment by dinnot** [comment]
done in #559

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/563
