### ISSUE TITLE
overwrite_template should default to true

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-output-elasticsearch#458]
With so many old template versions hanging around, and more people comfortable with using their own, it makes sense that we should have `overwrite_template` set to true by default.  Since this is a breaking change, it should only be so in Logstash 5.0.

**Comment by andrewvc** [comment]
I dunno, I think this will surprise people in unexpected ways going forward.

**Comment by untergeek** [comment]
After all this time, I'm meh.

**Comment by andrewvc** [comment]
@untergeek mind if I close this then?
