### ISSUE TITLE
Not able to run the test

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-output-elasticsearch#46]
Running the test as specified with the documentation give this error, without running at all. The process to run the test I followed is the one described in the README file.

    ➜  logstash-output-elasticsearch ✗ bundle exec rspec --tag elasticsearch     
    Using Accessor#strict_set for specs
    Run options:
      include {:elasticsearch=>true}
      exclude {:redis=>true, :socket=>true, :performance=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true}
    Jan 28, 2015 1:49:18 PM org.elasticsearch.node.internal.InternalNode <init>
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] version[1.4.0], pid[78132],  build[bc94bd8/2014-11-05T14:26:12Z]
    Jan 28, 2015 1:49:18 PM org.elasticsearch.node.internal.InternalNode <init>
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] initializing ...
    Jan 28, 2015 1:49:18 PM org.elasticsearch.plugins.PluginsService <init>
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] loaded [], sites []
    Jan 28, 2015 1:49:23 PM org.elasticsearch.node.internal.InternalNode <init>
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] initialized
    Jan 28, 2015 1:49:23 PM org.elasticsearch.node.internal.InternalNode start
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] starting ...
    Jan 28, 2015 1:49:23 PM org.elasticsearch.transport.TransportService doStart
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] bound_address {inet[/0:0:0:0:0:0:0:0:9301]},  publish_address {inet[/192.168.2.112:9301]}
    Jan 28, 2015 1:49:23 PM org.elasticsearch.discovery.DiscoveryService doStart
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] elasticsearch/x1NmjcPsRXukShUeRv-Hkg
    Jan 28, 2015 1:49:53 PM org.elasticsearch.discovery.DiscoveryService waitForInitialState
    WARNING: [logstash-Peres-MacBook-Pro.local-78132-9186] waited for 30s and no initial state was set  by the discovery
    Jan 28, 2015 1:49:53 PM org.elasticsearch.node.internal.InternalNode start
    INFO: [logstash-Peres-MacBook-Pro.local-78132-9186] started
    Failed to install template: waited for [30s] {:level=>:error}

Then if there is no flag given, the registration test fails as it complains there is no milestone set.

    1) outputs/elasticsearch should register
         Failure/Error: output = LogStash::Plugin.lookup("output", "elasticsearch").new("embedded" => "false", "protocol" => "transport", "manage_template" => "false")
         RuntimeError:
           elasticsearch must set a milestone. For more information about plugin milestones, see  http://logstash.net/docs/1.5.0.dev/plugin-milestones 
         # ./spec/outputs/elasticsearch_spec.rb:10:in `(root)'

This was tested using the 1.5 branch, to run this using the master branch makes no complaint about the milestone stuff, but the test with the tag hangs with a similar message:

    INFO: [logstash-Peres-MacBook-Pro.local-78698-8642] elasticsearch/y79rgoLuT5mbEYBT9JVCyA
    Jan 28, 2015 2:09:28 PM org.elasticsearch.discovery.DiscoveryService waitForInitialState
    WARNING: [logstash-Peres-MacBook-Pro.local-78698-8642] waited for 30s and no initial state was set by the discovery
    Jan 28, 2015 2:09:28 PM org.elasticsearch.node.internal.InternalNode start
    INFO: [logstash-Peres-MacBook-Pro.local-78698-8642] started

**Comment by jordansissel** [comment]
Is this still an issue? Jenkins looks green: http://build-eu-00.elasticsearch.org/view/LS%20Outputs/job/logstash_output_elasticsearch_commit/

**Comment by purbon** [comment]
@jordansissel Jenkins looks green because most of this specs are not really executed, you can check https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/spec/outputs/elasticsearch_spec.rb#L16 :cry: :cry: :cry: :cry: 

working on a simple way to enable this.

Milestone is an issue only happening with the 1.5 brunch, but not sure of the 100% status of that.

**Comment by talevy** [comment]
closed in favor of #111
