### ISSUE TITLE
Document ingest pipeline parameter

### ISSUE THREAD

**Issue by cwurm** [logstash-plugins/logstash-output-elasticsearch#467]
Following the introduction of ingest nodes in Elasticsearch, this plugin now supports a `pipeline` parameter for the `elasticsearch` output.

It has yet to be documented in https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb

**Comment by acchen97** [comment]
Closing as this documentation is done.

https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-pipeline
