### ISSUE TITLE
Add Stale Connection Check

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#468]
Sometimes people have bad networks that drop idle connections. For these people we should add the stale connection check as we do here: https://github.com/logstash-plugins/logstash-mixin-http_client/blob/master/lib/logstash/plugin_mixins/http_client.rb#L106

**Comment by PhaedrusTheGreek** [comment]
Networks with firewalls should not necessarily be considered _"bad"_.   TCP timeouts are **essential** in stateful firewalls, as sessions must be tracked, but consume memory.

Wouldn't it be more proper to call this a _keepalive_ function at the application level?  We could have a parameter like:

```
keepalive => "15m"
```

And every 15 minutes do a `GET /` on Elasticsearch with [a reasonable timeout](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/470).

It would then serve as both a  connection test **and** a keepalive.    One that says "Fix if broken", but also "Don't Break".
