### ISSUE TITLE
Tcp time_wait between logstash agent and elasticsearch nodes

### ISSUE THREAD

**Issue by MichelLiu** [logstash-plugins/logstash-output-elasticsearch#473]
My elasticsearch cluster only contains two nodes: host_ip1, host_ip2.
But I found a lot of tcp time_waits between logstash agent and host_ip2 (Another elasticsearch node).
Here is my configuration:

output {
    elasticsearch {
        hosts => ["http://host_ip1:9200"]
        manage_template => true
        index => "logstash-%{+YYY.MM.dd}"
        flush_size => 1500
        idle_flush_time => 10
        workers => 4
        codec => "json"
    }
}

How do I resolve this problem?

**Comment by andrewvc** [comment]
Apologies for the delay. Thank you for the feedback.

The latest version of this plugin is much smarter about connection management and will minimize connections with a fair rotation algorithm. Please try upgrading to LS 5.x and the latest version of this output.

**Comment by andrewvc** [comment]
Please open a new issue if that doesn't solve the problem for you.
