### ISSUE TITLE
Support for sync/async replication in indexing requests

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#48]
from: https://github.com/elasticsearch/logstash/issues/1706

[elasticsearch_http plugin exposed this setting](behttps://github.com/elasticsearch/logstash/blob/v1.4.2/lib/logstash/outputs/elasticsearch_http.rb#L93), might be useful to keep it in the new plugin.

**Comment by untergeek** [comment]
It might, but async is not recommended.  In training we tell people that this only gives the appearance of performance, but nothing is really different within Elasticsearch, other than that you now aren't sure your replicas have been created.

I recommend we remove the option and explain why.

**Comment by jsvd** [comment]
well, elasticsearch_http is being deprecated. if we don't want to support this, we just need to NOT add it to this plugin

**Comment by jordansissel** [comment]
@untergeek async is totally not recommended. Async was added because a customer needed it for a specific edge case. I don't know if this case is still in use.

**Comment by jsvd** [comment]
closing unless a good reason for having this again shows up.
