### ISSUE TITLE
Node not connected error, probably defunct sniffing

### ISSUE THREAD

**Issue by martinhynar** [logstash-plugins/logstash-output-elasticsearch#490]
I have LogStash with elasticsearch plugin and I started to see `node_not_connected` errors in LS log after more data nodes were added. The thing is, the LS instance has configured 3 data nodes (e.g. data001-data003) to send the indexing requests to. Those nodes are dedicated for this and have port 9200 opened. In the cluster, there are also other data nodes, but I don't want them to be used for indexing, however there is this `node_not_connected` error mentioning those unavailable data nodes (with port 9200 closed). The configuration is mentioned bellow, see that `sniffing` is not defined and default is `false` ([doc](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-sniffing)) I would assume that no additional nodes are sniffed and used, only those explicitly configured in `hosts` parameter.

Configuration
- Logstash version 2.3.4 with logstash-output-elasticsearch version 2.7.1
- Operating System: Oracle Linux 6.7
- Elastic output config

```
elasticsearch {
        action => "index"
        codec => "json"
        hosts => ['data001.example.com:9200', 'data002.example.com:9200', 'data003.example.com:9200']
        index => "data-%{+YYYY-MM-dd}%{index-suffix_}"
        manage_template => false
        workers => 1
    }
```

**Comment by martinhynar** [comment]
I tried with explicit `sniffing => false` and the result is the same.

**Comment by andrewvc** [comment]
@martinhynar apologies for the delay. 

We've overhauled sniffing in the latest versions of this plugin. Please try upgrading to LS 5.x + the latest ES output for the best sniffing experience.
