### ISSUE TITLE
Can't use script with params when the script type is file.

### ISSUE THREAD

**Issue by CharlesLdy** [logstash-plugins/logstash-output-elasticsearch#495]
- Version: 2.3.4

Now I set the script type inline. And it always causes the memory leak. ref:https://github.com/elastic/elasticsearch/issues/20114#issuecomment-254427412

To avoid dynamic scripts, I want to set the script type file instead of inline. But it seems that there is no way to set the params for the script in the file. And the param is created by the logstash's input and filter.  the script with params is something like the decription of the elasticsearch's document below..

I cut out some words from the elasticsearch's document about the script:

The file should be named as follows: {script-name}.{lang}. For instance, the following example creates a Groovy script called calculate-score:
> cat "log(_score * 2) + **my_modifier**" > config/scripts/calculate-score.groovy

This script can be used as follows:
> GET my_index/_search
   {
       "query": {
       "script": {
       "script": {
           "lang":   "groovy", 
           "file":   "calculate-score", 
           **"params": {
               "my_modifier": 2
           }**
        }
     }
  }
}

**Comment by CharlesLdy** [comment]
https://discuss.elastic.co/t/update-nested-object-using-script-with-params-in-logstash-elasticsearch-output/49983
someone got the problem too. but there is no response.

**Comment by CharlesLdy** [comment]
sorry, I have been wrong. I have solved my question.

**Comment by v01t** [comment]
HI @CharlesLdy 
how do you pass
`...
"params": {
"my_modifier": 2
}
...`
to ES from logstash-output-elasticsearch configuration part?
Thanks.
