### ISSUE TITLE
Handle large events better

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#499]
Have seen an increased number of incidents where large events are causing
- Logstash to OOM
- Resulting bulk request size constructed by Logstash to exceed the default http max size limit of 100mb in Elasticsearch

This can happen if a single event approaches or exceeds 100mb in size, or a combination of some quite large events ending up in a bulk request that exceeds ~100mb in size.

For the logging use case (esp. ones that consume application logging), this can be difficult for the Logstash administrator to manage because he/she is at the mercy of what the application developers decide to write out to the log files (full soap responses, large dump of debug text, etc..).  Sometimes things will be running smoothly, and then few very large events come along and start to cause problems and affect the indexing of regular/normal sized events.

One common approach to tackle large events in pre-5.0 releases is to write a custom ruby filter to check for the byte size of the message field, tag the events accordingly, and route them to their corresponding ES output that is configured with a different workers and flush_size setting. For example, for events that are larger than say 95mb or so, they can be routed to the drop filter, or to an LS output that sends them to long term storage.  Then for events that are many Mbs to 95mb, they can be routed to an ES output with a flush size and workers of 1.  And regular sized events can use a higher number for flush size and workers.  As you can see, there is a lot of customization and custom settings required to "get this right".

Starting in 5.0, we no longer have a workers setting for the ES output, and everything is tuned based on the pipeline-level workers and batch size settings.  This suggests that instead of having multiple ES outputs, in order to have different worker settings, users will have to route different-sized events to different pipelines instead of output plugins.

After discussing with @jordansissel @andrewvc , it sounds like there is an effort to handle these scenarios better in product so that users will not have to implement workarounds like the ones mentioned above.  

For reference, there are a number of issues previously filed to request features that can potentially help with such a use case.  We may certainly decide to take a different approach (just summarizing below for historical context):
- https://github.com/elastic/beats/issues/1115 (Have beats provide a byte size based filter to route requests closer to the source)
- https://github.com/elastic/logstash/issues/4335 (Provide split by bytes filter in LS)
- https://github.com/elastic/logstash/issues/4000 (Add byte based flush setting for LS ES output) and https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/284 (Buffer based on bytes, not doc sizes)
- https://github.com/elastic/elasticsearch/issues/2902 (Properly handle response from ES when http max size is exceeded)

This is an issue filed to track the efforts in the LS product to handle large events better in the future.  @acchen97 @suyograo

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/497

**Comment by andrewvc** [comment]
Fixed in #497
