### ISSUE TITLE
Handle Elasticsearch bounce when using node protocol

### ISSUE THREAD

**Issue by kurtado** [logstash-plugins/logstash-output-elasticsearch#50]
If Elasticsearch cluster goes down while using node protocol, Logstash will eventually crash. This should be handled more gracefully.

Also need tests to verify.

migrated from https://logstash.jira.com/browse/LOGSTASH-2275

**Comment by jordansissel** [comment]
I think we're doing our best to avoid the node protocol, right @jsvd? If so, we can probably close this. Thoughts?

**Comment by andrewvc** [comment]
We no longer support the node proto
