### ISSUE TITLE
Ensure dns lookups occur any time a new connection is needed

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#51]
Parent ticket: https://github.com/elasticsearch/logstash/issues/2378

A user has reported that Logstash's elasticsearch_http output was using stale dns results when connecting to Elasticsearch - during runtime, dns had changed to move a cluster node, and Logstash didn't re-resolve the name to find the new address.

**Comment by jsvd** [comment]
will this still be a concern in the http only plugin, @andrewvc ?

**Comment by andrewvc** [comment]
@jsvd this will take some research test, but the behavior may very well be different with the new code. I'm really curious how sniffing will interact here.

**Comment by andrewvc** [comment]
@jordansissel to confirm, this was reported with FTW and not manticore yes? I don't believe manticore has this issue being based on apache commons HTTP.

**Comment by andrewvc** [comment]
This is still a bug in that it won't do this currently, but this can be fixed by setting '-Dnetwordaddress.cache.ttl=TTLINSECONDS'. I'll submit a PR to add this info to the docs.
