### ISSUE TITLE
Error when specifying proxy as hash

### ISSUE THREAD

**Issue by cwurm** [logstash-plugins/logstash-output-elasticsearch#517]
The [documentation states](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-proxy) that it's possible to specify the proxy configuration as a hash.

However, this does not seem to be the case at the moment (5.0, but also 2.3 and probably others), at least not the way it's documented.

Example config:
```
input {}
filter {}
output {
  elasticsearch {
    hosts => ["192.168.1.1:9200"]
    user => "elastic"
    password => "changeme"
    proxy => { host: "random" port: 8080 scheme: "http"}
  }
}
```

Error message (run with `-t`):
```
Sending Logstash's logs to /Users/cwurm/Products/Logstash/logstash-5.0.1/logs which is now configured via log4j2.properties
[2016-11-30T09:45:23,775][FATAL][logstash.runner          ] The given configuration is invalid. Reason: Expected one of #, => at line 8, column 20 (byte 149) after output {
  elasticsearch {
    hosts => ["192.168.1.1:9200"]
    user => "elastic"
    password => "changeme"
    proxy => { host
```

**Comment by andrewvc** [comment]
@cwurm it looks like the real issue here is that you're specifying the proxy with `{key: value}` instead of `{key => value}` that should fix this and should be a fine workaround for #516 .

**Comment by andrewvc** [comment]
I'm going to close this issue for now, if switching syntax still causes a problem I can reopen it.

**Comment by cwurm** [comment]
@andrewvc Can we update the documentation to use `key => value` instead of `key: value`?

**Comment by jordansissel** [comment]
Hmm two problems. The docs indicate this is a string setting so even
documenting that it can take some kind of hash is misleading. We should fix
the validation also.

+1

**Comment by andrewvc** [comment]
Reopening this due to the docs issue. Thanks for pointing that out @cwurm .

What this *should* take is the new SafeURI type. Both the hash and the string have the problem of leaking passwords in logs.
