### ISSUE TITLE
Improve logging when "Errno::EBADF: Bad file descriptor" happens

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-output-elasticsearch#542]
Transplanted from https://github.com/elastic/logstash/issues/2241

This message can happen when there are too many CLOSE_WAIT connections, exhausting file descriptors.  We can improve the logging when this exception is caught to be more explanatory.

**Comment by jsvd** [comment]
with the change from elasticsearch-ruby (and ftw) to manticore this error will no longer happen
