### ISSUE TITLE
template_name should be required when multiple output templates are in use

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-output-elasticsearch#544]
[This issue](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/76) is an all-to-often gotcha.  When you have multiple templates specified, by default they overwrite each other under the` template_name` of `logstash`.    

Logstash should be smart enough so that _if multiple outputs have been defined with different templates_, then different`template_name`s should be required to differentiate.

Invalid Config Example:

```
output {
 if "state" in [tags] {
  elasticsearch {
   template => "/state-index-template.json"
   template_overwrite => true
  }
 }
 if "logs" in [tags] {
  elasticsearch {
   template => "/logs-index-template.json"
   template_overwrite => true
  }
 }
}
```

Valid config example:

```
output {
 if "state" in [tags] {
  elasticsearch {
   template => "/state-index-template.json"
   template_name => "logstash-state"
   template_overwrite => true
  }
 }
 if "logs" in [tags] {
  elasticsearch {
   template => "/logs-index-template.json"
   template_name => "logstash-logs"
   template_overwrite => true
  }
 }
}
```

**Comment by jsvd** [comment]
I believe there are use cases where you'll want to have the same template but configure the rest of the plugin in a different way, like:

```
output {
 if "US" in [region] {
  elasticsearch {
   template => "/state-index-template.json"
   template_name => "logstash-state"
   template_overwrite => true
   hosts => ["us-server:9200"]
  }
 }
 else if "rest of the world" in [region] {
  elasticsearch {
   template => "/logs-index-template.json"
   template_name => "logstash-logs"
   template_overwrite => true
   hosts => ["rotw:9200"]
  }
 }
}
```

Unless we see more folks wanting this, I think we can close this for now
