### ISSUE TITLE
2.4 repetitive logging

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-output-elasticsearch#549]
I'm seeing the same excessive logging that was fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/896346b90cc139a32891d2eed48494a1db8f85b3

Could we backport this for 2.4?

Example of repetition (this has had a majority of the data deleted, it started a 5mb single line):
https://gist.github.com/jpcarey/cfa4009f14c5694c67a2467234762504

**Comment by jsvd** [comment]
I think we can close this since any logstash since 2.4 can install a recent version of es output
