### ISSUE TITLE
Error on logstash startup: "elasticsearch must set a milestone"

### ISSUE THREAD

**Issue by rabidscorpio** [logstash-plugins/logstash-output-elasticsearch#55]
I updated 2 plugins, logstash-input-elasticsearch and logstash-output-elasticsearch so I'm not sure if this errror happened after the input initialized or before the output even started:

{:timestamp=>"2015-02-12T00:19:07.854000+0000", :message=>"Using milestone 1 input plugin 'lumberjack'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones", :level=>:warn}
The error reported is: 
  elasticsearch must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones

**Comment by jordansissel** [comment]
This is a problem in 1.5.0 beta1 due to our forward progress towards 1.5.0 GA. It only affects beta1 and will not affect any future releases.
