### ISSUE TITLE
Bulk requests should be send with Content-Type header as application/x-ndjson

### ISSUE THREAD

**Issue by chekkan** [logstash-plugins/logstash-output-elasticsearch#561]
Currently, all request from logstash to elasticsearch is sent with `Content-Type` `application/json`. 

However, the `_bulk` requests should be sent with `Content-Type` `application/x-ndjson` as mentioned here https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-bulk.html

> When sending requests to this endpoint the `Content-Type` header should be set to `application/x-ndjson`.

Even though version 5.1.2 of elasticsearch seems to accept any `Content-Type` value, the use case for sending the correct request header is that if you are using a proxy for elasticsearch and the proxy has a middleware which parses json contents automatically, it will throw an error saying not a valid json.

**Comment by cosmo0920** [comment]
Elasticsearch 6.2 doc uses newline delimited content type(`application/x-ndjson`) in its example usage.
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-bulk.html
Is this issue still postponed?

**Comment by chekkan** [comment]
I reckon this issue can now be closed as the latest logstash version uses the correct content-type header.
