### ISSUE TITLE
document_id doesn't support uppercase column 

### ISSUE THREAD

**Issue by xbkaishui** [logstash-plugins/logstash-output-elasticsearch#566]
in logstash 5.1.1 

document_id => "%{docid}" is ok 
when change to 
  document_id => "%{docId}"  
%{docId} not replace default

**Comment by jbwl** [comment]
Same is true for Logstash / ES 5.3.0 stack, JDBC input, jTDS driver

**Comment by jsvd** [comment]
I've tested this with 6.x stack and works correctly:

```
input { stdin { codec => json } }
output { elasticsearch { document_id => "%{docId}" } stdout { codec => rubydebug } }
```

sent data `{"message": "hey", "docId": 1024 }`
then I could see the event in elasticsearch:

```
% curl -s localhost:9200/logstash-2018.05.17/doc/1024
{"_index":"logstash-2018.05.17","_type":"doc","_id":"1024","_version":1,"found":true,"_source":{"host":"Joaos-MacBook-Pro-5.local","docId":1024,"message":"hey","@timestamp":"2018-05-17T09:52:26.940Z","@version":"1"}}
```

**Comment by saifrehman15** [comment]
I am also doing the same thing . but it's not working.
