### ISSUE TITLE
Retry on unexpected response codes

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-elasticsearch#572]
cloud.elastic.co's proxy will return HTTP 502 if the cluster is being restarted. Currently, the plugin considers 502 to be *NOT* retryable, which means a cluster restart will cause data loss when the Elasticsearch output targets Cloud.

```
[2017-03-07T01:20:06,418][ERROR][logstash.outputs.elasticsearch] Got a bad response code from server, but this code is not considered retryable. Request will be dropped {:code=>502, :response_body=>"{\"ok\":false,\"message\":\"Unable to connect to the server.\"}"}
```

This is an unexpected problem because we only have targeted Elasticsearch-documented response codes in our work, here, and have never planned for an interfering gateway. Should be an easy fix to align more well with the way elastic cloud and other proxy or load balancer systems work.

**Comment by jordansissel** [comment]
I wonder if we should restore the older behavior of retrying on any failure, but perhaps modified thus:

* Drop (or DLQ, when that feature is available) if a known response from Elasticsearch is known to be one that cannot be corrected reasonably[1]
* Retry on any other error (4xx, 5xx)

[1] "cannot be corrected reasonably" -- For example mapping failures.

**Comment by gquintana** [comment]
I had this issue because I have an HAProxy load balancer between Logstash and Elasticsearch.
When HAProxy loses the network connection with ES, it returns 504 error pages (default behaviour in HTTP mode):
```
[504] <html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>
```
I am going to tune this error page and return a fake 503 status code

**Comment by untergeek** [comment]
I think we should have a special corner of the DLQ for 5xx responses.  Have it auto-retry them after a while, perhaps?

**Comment by dmarkhas** [comment]
We have created our own version of the plugin that, on an individual event failure, converts the event's body to a string, generates a new event with a single field "message" that contains this string and sends this new event to an "errors index" provided in the configuration. This provides a high degree of certainty that we will not lose data, even if the original event was rejected by ES for whatever reason (too many fields, wrong mapping, invalid index name, etc.).

I can submit our changes (very minor) as a PR if you think this is something that would be useful to others.

**Comment by jordansissel** [comment]
We have a dead letter queue feature in the works that will do this. No need
for a patch yet :)

**Comment by rparkhunovsky** [comment]
With https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/583 merged and https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/578 closed in favour of the current issue - could plugin's documentation be updated accordingly to reflect what's indeed being retried?
It's not obviously clear whether with DLQ from https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/583 504 server error code becomes retryable or it is only to be implemented.

**Comment by theflyingnerd** [comment]
It's a bit frustrating that the official Elastic.co cloud offering suffers from this, we lost 5 hours of logging while it was down today because the Elastic Cloud's load balancer returned 502's while the cluster was down, dropping the logs from Logstash. Also, just as the cluster was coming back up, we lost an additional small window of logs as the cluster didn't seem to be fully configured momentarily, returning a 401. Could Elastic consider either making the output plugin configurable for additional retryable codes (this would be a non-breaking change, I think?), or otherwise modify the behaviour of the load balancing to return codes that are acceptable to Logstash.

**Comment by waynetaylor** [comment]
+1. Just experienced this today. What options do we have?
