### ISSUE TITLE
Feature Request: Create an option to drop an event based on a duplicate document id

### ISSUE THREAD

**Issue by Exocomp** [logstash-plugins/logstash-output-elasticsearch#574]
See the discussion here https://discuss.elastic.co/t/logstash-drop-duplicate-elasticsearch/77807/7

**Comment by untergeek** [comment]
According to what I read, this feature is already in existence.  You only need to manually specify a `document_id` and use `create` as your `action`:

> create: indexes a document, fails if a document by that id already exists in the index.

See [https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-action](the documentation) for more information.

```
output {
  elasticsearch {
    # (Other config options)
    document_id => "%{myfield}"
    action => "create"
  }
}
```

Ideas for creating a unique `document_id` include using the [`fingerprint`](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html) plugin, which will make a unique hash based on one or more fields.  If all selected fields matched exactly, then the fingerprint would be identical, guaranteeing that no duplicates would appear in Elasticsearch.

**Comment by Exocomp** [comment]
@untergeek, thanks!! I already have a unique id, I was ignorant about the action create option.  Since by default I think it does upsert and that seemed inefficient.  I will go a head with the action create.  Thanks again, I will update the post I had on discuss.

**Comment by iemem15** [comment]
Excellent! Worked for me
