### ISSUE TITLE
Description doesn't make sense for workers setting

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#597]
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-workers

>workersedit
Value type is string
Default value is 1
when we no longer support the :legacy type This is hacky, but it can only be herne

Not sure what the above is supposed to say :)

I think we mean to say that this setting is no longer supported/used, and users should configure pipeline level workers instead?

**Comment by ppf2** [comment]
@andrewvc I believe we stopped supporting this workers setting back when [4.0.0](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/CHANGELOG.md#400) version of the plugin was released?

The [current doc still shows](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-workers) this option as an available setting (with it defaulting to 1).  Should we actually remove this option entirely from the documentation from now on?

**Comment by jsvd** [comment]
closing since workers is no longer a valid option and is gone from the docs
