### ISSUE TITLE
Parent/Child specs failing on latest ES master

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#602]
Builds like: https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/jobs/236051767
are failing with errors like:

```

org.elasticsearch.transport.RemoteTransportException: [KkXNHqC][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.query.QueryShardException: [has_parent] query configured 'parent_type' [4627443913_parent] is not a valid type
```

We need to fix this! I suspect this is related to the removal of types in ES 6.0

**Comment by suyograo** [comment]
@andrewvc I'll take this from you while you focus on other things..

**Comment by jsvd** [comment]
I've done some investigation about these failures and you're right that the main problem is that elasticsearch 5.6 and 6 will only support a single type.
This has an implication in the parent/child feature of ES, where it will no longer be done through the use of multiple types, but through a `join` data type. More about this can be found inhttps://www.elastic.co/guide/en/elasticsearch/reference/5.x/parent-join.html

This implies that the current tests about parent/child must be confined to <= 5.x through tagging and new tests with the join data type must be added and run with both 5.6 and 6.x

**Comment by jsvd** [comment]
an update the support of the `parent` parameter with elasticsearch 6.0.0: the syntax in the bulk request for indexing child documents has gone from

```json
{"index":{"_id":null,"_index":"1112","_type":"doc","_routing":"test"}}
{"foo": {"name": "child_value", "parent": "test"},"message":"Hello World!"}
```

to

```json
{"index":{"_id":null,"_index":"1112","_type":"doc","_routing":null,"parent":"test"}}
{"foo":"child_value","message":"Hello World!"}
```

which means the join definition must be in the _source instead of header. The es output doesn't currently have the ability to do this, so more work is required in the presence of a child document index operation
