### ISSUE TITLE
Passwords needing escaping are broken

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#618]
It seems that https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/605 caused there to be broken behavior here, causing situations like https://discuss.elastic.co/t/error-start-logstash-after-update-from-5-4-3-to-5-5/92418 where the password field would not be automatically URL escaped.

This behavior should be restored.

**Comment by tatdatpham** [comment]
With password have contain special character (like @#!.... ), Logstash can't not work  (ussing x-pack for sending stats to ES and push log fro logstash to ES
