### ISSUE TITLE
429 Errors are not exponentially retried

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#619]
They should be, though they currently are not.

**Comment by jsvd** [comment]
the `retrying_submit` inner loop [uses `next_sleep_interval`](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/5a367516075dd2f898c89fdaeb8f847a175601fd/lib/logstash/outputs/elasticsearch/common.rb#L165) so I think we can close this.
