### ISSUE TITLE
Logstash loses records on 500 status code 

### ISSUE THREAD

**Issue by dmarkhas** [logstash-plugins/logstash-output-elasticsearch#626]
One of the ES nodes in our cluster crashed today, and while the cluster kept functioning some of the bulk insert requests performed by logstash failed with the below error:

[2017-07-19T04:47:46,560][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>500, :action=>["index", {:id=>"19e9c5dc-f23e-4adc-ad46-176869872768", :index=>"computing.network_latency.08f694be-0619-485c-a3a4-0d7dd25cf1ef-2017.29", :type=>"doc", :routing=>nil}, 2017-07-19T04:45:42.038Z %{host} %{message}], :response=>{"index"=>{"index"=>"computing.networklatency.08f694be-0619-485c-a3a4-0d7dd25cf1ef-2017.29", "type"=>"doc", "id"=>"19e9c5dc-f23e-4adc-ad46-176869872768", "status"=>500, "error"=>{"type"=>"node_not_connected_exception", "reason"=>"[data1-iil-005][10.184.95.5:9300] Node not connected"}}}}

This is obviously a temporary issue, so I would expect Logstash to retry - but it didn't, since 500 isn't a retryable code as far as logstash is concerned. Either way, this data was lost. We use Logstash 5.4, but even if we were using the DLQ feature (which is not clear to me in which version it is available), it wouldn't have helped since the elasticsearch output DLQ's only 400 and 404 errors.

Is this something that should be fixed in Logstash, or in ElasticSearch? While Logstash is correct to assume 500 means a permanent failure, this particular exception is somewhat of a gray area.

**Comment by andrewvc** [comment]
Hmmm, we should retry indefinitely, IMHO, on 500 errors, I'll investigate this.

**Comment by andrewvc** [comment]
This will be fixed in #640

**Comment by andrewvc** [comment]
By the way, which JRE/JDK version are you using? Java TLS support differs between them.

**Comment by andrewvc** [comment]
@dmarkhas btw, I also just want to apologize for the bad behavior there. That is definitely a nasty bug.

**Comment by dmarkhas** [comment]
We use JDK 1.8.0.92

I completely understand that you cannot always predict with 100% accuracy what kind of errors ES will return and which of them are retriable.
When I said that the data was lost that was not accurate - since we use a custom version of the plugin (as I mentioned in #572), we didn't lose any data.

**Comment by dmarkhas** [comment]
Also looking at #640 I'm not certain if it is going to fix this particular issue - I believe the 500 code is not returned on the entire bulk request, but for individual documents within that request (the ones that were writing to an index on a node that got disconnected), and as such should be caught in submit, not in safe bulk.

**Comment by andrewvc** [comment]
by the way, are you using the new dead letter queue? Looking at the code it looks like we should retry those 500s at the document level indefinitely https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/common.rb#L152

**Comment by andrewvc** [comment]
BTW, what version of the ES Output are you using, or when did you fork?

**Comment by dmarkhas** [comment]
We're using 6.2.6 - which didn't have DLQ, so it would just drop events that weren't in "RETRYABLE_CODES", which is why we had to make our own changes in the first place.

The DLQ introduced recently is a nice concept but doesn't really work in a large scale containerized environment - we run Logstash in containers (about 40 instances), so we can't rely on the container itself to serve as the DLQ because it is very small (in terms of local storage) and ephemeral.
Instead, we ship all failed events to a special index in ElasticSearch which is one central place with (theoretically) unlimited storage, where we can inspect them easily and reindex back to the correct index.

Looking at the latest version of the code I believe this will work correctly :+1:
