### ISSUE TITLE
incorrect check for dlq_writer leads to not logging DOC_DLQ_CODES failures

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#652]
Currently the `@dlq_writer` [is declared in the register method as](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/f3c4895897cb93303fe58132ff186ea8dbb0c465/lib/logstash/outputs/elasticsearch/common.rb#L21):

```ruby
@dlq_writer = supports_dlq? ? execution_context.dlq_writer : nil
```

In releases of Logstash that support DLQ, the `@dlq_writer` will never be nil, even if DLQ is not enabled, as [a dummy DLQ is set instead of the actual DLQ](https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/pipeline.rb#L88-L94).

This means that individual documents in the bulk that returned one of the DOC_DLQ_CODES will reach:

```ruby
          if @dlq_writer
            @dlq_writer.write(action_event, "Could not index event to Elasticsearch. status: #{status}, action: #{action}, response: #{response}")
          else
            @logger.warn "Could not index event to Elasticsearch.", status: status, action: action, response: response
          end
```

And take the first branch of the conditional. If the DLQ is disabled, the event is written to a dummy DLQ, and no warning is logged. This means that 404 and 400 failures are silent: we neither log nor send them to a DLQ.

**Comment by jsvd** [comment]
@robbavey what do you think is the best way for a plugin to check if the `@dlq_writer` is actually enabled? By enabled I mean it's neither nil nor a DummyDeadLetterQueueWriter.

Right now it's possible to do `@dlq_writer.inner_writer.is_a?(DummyDeadLetterQueueWriter)`, but maybe we should have a more proper API

**Comment by robbavey** [comment]
@jsvd Yeah, its unfortunate that the knowledge of whether the dlq is enabled is abstracted away from the plugin author. In the short term, to support already released Logstash version,  we're likely going to have to access the inner_writer :(, and either use the is_a?, or is_open? methods, neither of which are great. 

Going forward, we should make this friendlier for the plugin developer; we could add an available? (which would test for whether the writer was open), or enabled?
 (which would either check the implementation or call down to an enabled? method on the DLQ writer implementation) methods to the PluginDeadLetterQueueWriter class

**Comment by jsvd** [comment]
I created https://github.com/elastic/logstash/issues/8064 about the lack of an API for DLQ status

**Comment by jordansissel** [comment]
@jsvd  the check for "is dlq enabled" is mainly to enable plugins that run under Logstash where the DLQ doesn't exist.

I wonder if, instead, that the dummy dlq (when DLQ is disabled) does the logging instead of making the plugin author do the check?

**Comment by jsvd** [comment]
this was solved by https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/653
