### ISSUE TITLE
Would please add support config ES host using string

### ISSUE THREAD

**Issue by eisig** [logstash-plugins/logstash-output-elasticsearch#657]
As discuss in  #520, ES hosts array not support for parsing environment variables
The issue in logstash([ES hosts array: Support for parsing Environment Variables](https://github.com/elastic/logstash/issues/6665)) is still open.

Would please add support config ES host using string, let both forms works:
hosts => "es1:9200,es2:9200"
hosts => ["es1:9200","es1:9200"]

**Comment by andrewvc** [comment]
This is a neat idea, but it'd be best solved in logstash core. Ideally we'd have first class array support there. I'm closing this in favor of an issue I opened there: https://github.com/elastic/logstash/issues/8157
