### ISSUE TITLE
Only working config seems to be host=localhost, cluster=elasticsearch

### ISSUE THREAD

**Issue by jjongsma** [logstash-plugins/logstash-output-elasticsearch#66]
I've spent the better part of a day trying different combinations, and it appears that with the logstash-1.4.2 distribution the *only* combination that actually works is:

```
{
   host => "localhost"
   cluster => "elasticsearch"
}
```

I've tried the following combinations (network fully open, no firewall issues here):

#### host => "my.host.com", cluster => "elasticsearch"

Fails for every combination, no nodes found. According to debug logs ES it continually attempts to connect to localhost, and never even tries to connect to the host I specify. Logs show that it my configuration is being processed properly:

```
{:timestamp=>"2015-02-27T22:13:13.821000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@host = \"elasticsearch\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
```

Eventually it fails with a "no master found" error after 30s.

Even if I specify `protocol => "http"`, this behavior remains the same, which is bizarre - why would it be trying to discover peers if it's using the REST API? It almost seems like it's trying to start an embedded node by default and refuses to actually connect to anything else when that fails. I tried explicitly setting `embedded => false` to test that theory, but the behavior remains the same.

#### host => "localhost", cluster => "logstash" (local ES node configured as cluster = "logstash")

It sees and attempts to connect to my local node, but I get "skipping node" log messages because it claims the node's "logstash" cluster name doesn't match.

#### host => "localhost", cluster => "logstash" (local ES node configured as cluster="elasticsearch")

It connects to the local node without complaining about cluster mismatch, advances to the next stage, and then the client complains about a cluster name mismatch. Well, yes, that's true, but why did it even get past the "cluster mismatch" stage from the previous attempt?

#### host => "localhost", cluster => "elasticsearch" (local ES node configured as cluster="elasticsearch")

The only combination I found after 6 hours of experimenting that works.

My best guess is that for whatever reason it's *always* starting up an embedded node with default configuration, and I can't figure out how to shut that off. And if that node fails to connect to anything else (bad cluster name, nothing running on localhost), it craps out and doesn't even try to connect to the host I'm telling it to.

What a frustrating experience for what should be a very basic setup. Either something is seriously wrong with this plugin or the documentation is in need of a major update.

**Comment by jordansissel** [comment]
Can you attach your elasticsearch config?

**Comment by jjongsma** [comment]
%$!@#%$!@#

Ok, after reading through the plugin code and being completely mystified as to how this could be happening, I found a dangling `elasticsearch {}` output block a developer left in a separate config include over here.

Sorry, closing.

**Comment by jordansissel** [comment]
@jjongsma sorry you ended up spending so much time battling this issue. May your future troubleshooting efforts be much quicker! :)
