### ISSUE TITLE
Enhancement: Protect methods with Ruby Contracts

### ISSUE THREAD

**Issue by mcandre** [logstash-plugins/logstash-output-elasticsearch#664]
Contracts can ensure that methods don't try to process calls with strangely typed arguments. It's not a compile time check, but a small runtime penalty for a more robust operation.

https://github.com/egonSchiele/contracts.ruby

Thoughts? Perhaps this is overkill, but I find a lot of Ruby code runs more robustly with contracts rather than pure duck typing

**Comment by andrewvc** [comment]
This is an awesome idea, but our plans are to refactor this plugin relatively soon into Java where that won't be necessary (and it can run a bit faster).

**Comment by jsvd** [comment]
as stated, this plugin is moving more and more into Java (elasticsearch-ruby+ftw was dropped in favor of manticore+httpclient) so I don't think this will happen
