### ISSUE TITLE
Document Type handling with ES6.0

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#669]
Elasticsearch 6.0 is [removing document types](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html)

Beats 6.0 will begin setting `type` to `doc` in the future.

We haven't changed Logstash behavior at all yet.

My thoughts:

1. Currently this plugin will set the `document_type` to the value of the `type` event field. This behavior should be disabled for ES6+ clusters as well as support for sprintf interpolation.
2. We should deprecate `document_type`
3. We should switch our default `logs` type for that setting to `doc` for consistency with beats.

Thoughts?

**Comment by jordansissel** [comment]
I think moving to align with Beats is a good idea on the journey for Elasticsearch removing the concept of document types.

+1

**Comment by jordansissel** [comment]
Closing in favor of #691
