### ISSUE TITLE
Revert back to using host config option for defining multiple hosts

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-elasticsearch#67]
1.4.2 has config option `host` http://logstash.net/docs/1.4.2/outputs/elasticsearch#host 

this was changed in https://github.com/logstash-plugins/logstash-input-elasticsearch/commit/add0954a1f5d5227060dc3adc63e9919361b80ac which is not backward compatible

We need to go back to using host (even if it supports multiple hosts now)

**Comment by jordansissel** [comment]
Yep! `:validate => :arrray` allows single-value settings (intentionally, yay config parser!) so `host => "foo"` and `host => [ "foo" ]` are equivalent in logstash config.

+1 for going back to `host`

**Comment by suyograo** [comment]
Seems to be fixed in the latest https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L101

**Comment by suyograo** [comment]
Tested fixed
