### ISSUE TITLE
Open files issue in logstash

### ISSUE THREAD

**Issue by ankitlnct09** [logstash-plugins/logstash-output-elasticsearch#68]
Hi,

I am using logstash 1.4  file input in which we are facing open file issue in linux server (RHEL).
Please add configuration so that it will only monitor updated files

**Comment by suyograo** [comment]
Hi, I don't understand the issue. Could you please explain further? Also please open an issue here: https://github.com/logstash-plugins/logstash-input-file

**Comment by ankitlnct09** [comment]
Hi Suyog,

I am using logstash on apache server in which logs file are rotated every 10 MB, so for monitoring these file i am using wildcard char  (i.e. * ) in logstash configuration file input. so suppose in a day 100 files are rotated logstash keep opens these 100 files and after some days number of open file by logstash is too high which is effecting the server performance.

If there is any alternative to resolve the above problem, Please forward it to me and if possible please add some solution in logstash input file configuration for monitoring only updated file in case of wildcard using in path.

**Comment by untergeek** [comment]
This sounds more like an input issue than one with the logstash-output-elasticsearch plugin.

That said, why tail log files when you can [configure Apache to send JSON formatted logs directly to Logstash](http://untergeek.com/2013/09/11/getting-apache-to-output-json-for-logstash-1-2-x/)?  That is, if you can add the alternate configuration.  Then you won't have a file handle issue at all.
