### ISSUE TITLE
Plugins always install even if they are already installed

### ISSUE THREAD

**Issue by thejeff77** [logstash-plugins/logstash-output-elasticsearch#684]
when running logstash-plugin install <plugin-name>

It always installs even if it is already installed

Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: 7.4.0
- Operating System: Linux
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by jsvd** [comment]
this is not related to the es output, please open an issue in core at elastic/logstash
