### ISSUE TITLE
Unable to convert an existing field type to date

### ISSUE THREAD

**Issue by OElesin** [logstash-plugins/logstash-output-elasticsearch#69]
I have a field in my log file which contains the timestamp. Logstash automatically converts the field type to string but I want to convert the field type to date. 
How do I go about this?

**Comment by untergeek** [comment]
Without seeing your configuration I'll have a harder time giving a correct response.  Would you be willing to share your configuration here?

Generally speaking, there are two ways this can be accomplished.  One is to use the date filter in Logstash, the other is to set up Elasticsearch to recognize the field as a date type via a mapping template.  The first is preferable.

**Comment by UlrichEckhardt** [comment]
Here's a filter I use:

    date {
      timezone => "Europe/Berlin"
      match => [ "monolog_timestamp", "yyyy-MM-dd HH:mm:ss" ]
      target => "timestamp"
    }

The `monolog_timestamp` was previously extracted from the logs using a grok filter.
