### ISSUE TITLE
Upserts are currently broken

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-elasticsearch#698]
Moved from: https://github.com/elastic/elasticsearch/issues/27148 .

I have confirmed that upserts are currently broken.

Given the config specified in: https://gist.github.com/rfraposa/83c5c526c2a6c55417d4dcd8748fa26e

 The bulks currently look like:

```
{"update":{"_id":"1234","_index":"my_destination","_type":"doc","_routing":null,"_upsert":"{}","_retry_on_conflict":1}}
{"script":{"params":{"event":{"end_time":15,"@version":"1","trip_id":"1234","@timestamp":"2017-10-27T22:00:06.426Z"}},"id":"update_my_docs","lang":"painless"},"scripted_upsert":true,"upsert":{}}
{"update":{"_id":"1234","_index":"my_destination","_type":"doc","_routing":null,"_upsert":"{}","_retry_on_conflict":1}}
{"script":{"params":{"event":{"@version":"1","start_time":10,"trip_id":"1234","@timestamp":"2017-10-27T22:00:06.428Z"}},"id":"update_my_docs","lang":"painless"},"scripted_upsert":true,"upsert":{}}
```

They should not have the `_upsert` parameter set at all, nor should the `lang` value be set. There's also a weird error I'm getting about  `Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes` in rc2.

This needs more research.

**Comment by jsvd** [comment]
@rfraposa just to confirm, I tried with the following output:
```
output {
	elasticsearch {
		action => "update"
 		index => "my_destination"
		document_type => "doc"
		document_id => "%{trip_id}"
		scripted_upsert => true
		script => "update_my_docs"
		script_type => "indexed"
		script_lang => ""
		script_var_name => "event"
		upsert => "null"
	}
}
```

Executed logstash with the following cli arguments (to ensure the order of requests): `bin/logstash -f cfg -w 1 -b 1`
And logstash performed the ingestion, listing the following event in the `my_destination` index:

```json
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "my_destination",
        "_type": "doc",
        "_id": "1234",
        "_score": 1,
        "_source": {
          "testing": "hello"
        }
      }
    ]
  }
}
```

Is this what it's expected to have?

**Comment by rfraposa** [comment]
@jsvd - that does look correct. Let me verify on my rc2 install with the actual data and script, and I will let you know. Thanks!

**Comment by rfraposa** [comment]
@andrewvc @jsvd @jordansissel  - this works! The trick is to set `script_lang => ""` like Joao said, and also set `upsert => "null"`. Otherwise you get 400 errors during the upserts.

This is great news. Thanks for everyone's help!

**Comment by andrewvc** [comment]
Would it be possible to automatically detect the ES version and correctly set these parameters? The UX here of setting an empty string is definitely not what we want ultimately.

**Comment by jsvd** [comment]
@andrewvc it's possible, the only tricky thing is that it requires constructing a "v5" or "v6" version of the request depending on the version of the coordinating node we're hitting if the cluster is during a rolling upgrade, right?

I added [documentation about this requirement](https://www.elastic.co/guide/en/logstash/6.0/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-script_lang), but I agree it's not ideal at all..

**Comment by andrewvc** [comment]
@jsvd that's a good point!

I think that this is a release note to include:

"During a rolling upgrade we will use the scripting API of the highest node seen in the cluster. Use of a load balancer may confuse Logstash in this regard, restarting logstash after the upgrade is advised".

This is a better UX than requiring odd parameters IMHO.

**Comment by jordansissel** [comment]
@andrewvc ++. Long term we can make the connection pool manager identify each node's version and do-the-right-thing depending on the version.

**Comment by andrewvc** [comment]
@jordansissel I like the idea, but I don't know if we can do that due to load balancers (argh!).

I think we should just adjust behavior based on the highest node version seen.

**Comment by jsvd** [comment]
> Long term we can make the connection pool manager identify each node's version 

btw, this already happens https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L245-L248

**Comment by jsvd** [comment]
We understand that the UX can be improved for upserts for 6.x onwards, but maybe this issue should be closed ?

**Comment by andrewvc** [comment]
I opened https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/702 to track the proposed enhancement.
