### ISSUE TITLE
Add possibility to delete document matching given condition

### ISSUE THREAD

**Issue by matino** [logstash-plugins/logstash-output-elasticsearch#705]
I know that currently it is possible to delete a document by `id`. Is it possible to specify additional condition for the delete query, e.g. `is_active=true`?  

The use case I'm facing is that I can have multiple entries in the main database (from which only 1 is active, others are inactive), that are mapped into 1 document in elasticsearch. In such case, I want to delete the document in ES only when the document to be removed is the active one. So when the document to delete is `{"id": 1, "is_active": false"}`, the delete condition won't match and no documents will be removed.

**Comment by jsvd** [comment]
from what I understand this plugin can't support [delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) as it uses the _bulk api. a solution could be to use the elasticsearch filter to fetch the id of the event you want to delete and use that in the es output with a delete action.
