### ISSUE TITLE
Backport retry for non-200 requests

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#706]
Per discussion with @jordansissel , it will be great to backport https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/640 to a 7.x version plugin so that users on 5.x can easily update to it without having to deal with dependency issues of major version installs.

**Comment by jordansissel** [comment]
Looks like it was backported already, nice! https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/608336264fda308b1fca3e2f95ba18c003bea2ba

https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/648

v7.4.0 of the 7.x plugin major should have this feature. (Latest 7.x at time of writing is v7.4.2)
