### ISSUE TITLE
Document type issue with out of the box experience with FB

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-elasticsearch#708]
Currently  if you are using FB or any other beat the client will send a custom `type` field with every events, when you are using the ES output with the default settings, the behavior is to take the value of the event "type" field as the document type instead of the default "doc".

The problem with the type changes in es 6.0 this will make the logstash output throw theses errors and not persist any events to ES.

```
[2017-11-21T14:26:01,991][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"packetbeat-6.0.0-2017.11.21", :_type=>"flow", :_routing=>nil}, #<LogStash::Event:0x4af7bf6>], :response=>{"index"=>{"_index"=>"packetbeat-6.0.0-2017.11.21", "_type"=>"flow", "_id"=>"jEL43l8Bp0AXkoCMsC5q", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [packetbeat-6.0.0-2017.11.21] as the final mapping would have more than 1 type: [icmp, flow]"}}}}
```

**Configuration used:** 

```
input {
  beats {
    port => 5044
  }
}
filter {
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "changeme"
  }
}
```

Not sure what would be the best way to handle this, seems like this behavior could break users configuration if they rely on type. Maybe we should only rely on either _fieldref_ or the "doc" default value and not use the _event.get("type")_

Any ideas @andrewvc @jsvd ?

**Comment by gingerwizard** [comment]
or winlogbeat or metricbeat i suspect - they all produce multiple values for `type`

**Comment by ph** [comment]
@gingerwizard yes, I've changed the wording to be more generic.

**Comment by jordansissel** [comment]
I think for now users will have to set `document_type => "doc"` in their config. Going forward, maybe detecting ES version for a connection and ignoring the `document_type` setting for these connections if ES 6.0+ is detected? It's tricky because we can't just default to "log" if the user already has "foo" as the one-and-only-type in ES (I haven't looked at the code if we try this already, or how complex it would be)

Thoughts on a migration strategy for users?

**Comment by ph** [comment]
@jordansissel We have already logic in place to detect the version of the remote es cluster, so we could go that path without too much trouble.

Currently  this is the current logic we have to apply the document type.

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/fc2dfd5fd8a6006d1983818e16f21705fca9fb09/lib/logstash/outputs/elasticsearch/common.rb#L202-L215

@jordansissel The problem this change in behavior will affect anyone that use type in their configuration not just beats, its a pretty common pattern to define `type => X` on the input.

I am not sure if we can fix the default experience without breaking the behavior.

**Comment by ph** [comment]
@andrewvc thinking more about it, for a 6.0 cluster we should not even support _fieldref_ because of the limit of a single type per index. :(

**Comment by ph** [comment]
cc @dedemorton since this might have doc implication.

**Comment by jordansissel** [comment]
@ph I don't know how to square it; the upgrade path for users feels a bit dangerous no matter what we do. Removing types is very hard.

Maybe the safest approach is to keep an in-memory state of the single type in the targeted index, so before we _bulk to any index, we'll do a lookup to find the type, and then use that for all future _bulk's to that index?

Another option is to DLQ, but honestly  I think that's a bad option.

We could crash instead?

**Comment by gingerwizard** [comment]
Whatever you change here its going to break something - no change and we fail to index data, default to "doc" in 6.0.1 and we break dashboards. Personally i feel the latter is a better problem to have than to simply fail to index on the OOTB experience. Defaulting to doc also aligns more closely with the rest of the stack e.g. beats and our recommendations.

**Comment by ph** [comment]
@jordansissel I totally agree with you, this change is **really** hard. 

> Maybe the safest approach is to keep an in-memory state of the single type in the targeted index, so before we _bulk to any index, we'll do a lookup to find the type, and then use that for all future _bulk's to that index?

This value isn't persisted for restart and not shared with multiple LS instances. I tend to agree with @gingerwizard, I don't see  a fix for the problem without breaking anything.

**Comment by acchen97** [comment]
@ph @andrewvc @jordansissel let's discuss this live, I've set up some time for us to discuss this issue today.

**Comment by andrewvc** [comment]
Spoke with @ph and @acchen97 .

We decided to change the behavior to ignore the type field when ES 6.0+ is detected. Users will still be able to manually interpolate it if they so desire.

We will target this change for 6.0.1

**Comment by jordansissel** [comment]
We’ll need to document the change as it is likely to break a lot of users
schemas

**Comment by gingerwizard** [comment]
Id suggest a really short blog post here if its likely to be a common gotcha. @acchen97 we also need to communicate internally.

**Comment by jordansissel** [comment]
I'm less worried about blog posts that most users are unlikely to read when they upgrade. The problem is this is likely to *break* kibana dashboards, queries, etc, and doing so without notification for users.

Forcing a hard-coded type for 6.0+ is a fine solution in isolation, but this change will silently change the user's document `type` which can cause some very surprising changes in behavior.

**Comment by jordansissel** [comment]
If nothing else, let's simulate what breaks, at minimum, and document the way to resolve it for users (kibana dashboards, queries, etc)

**Comment by andrewvc** [comment]
I've added a note about this to the upgrade guide. That should hold us until we have a patch.

**Comment by andrewvc** [comment]
Link to that PR: https://github.com/elastic/logstash/pull/8708
