### ISSUE TITLE
Bump Elasticsearch version to 1.4.4

### ISSUE THREAD

**Issue by natefaerber** [logstash-plugins/logstash-output-elasticsearch#72]
Kibana 4 has this nasty habit of requiring all nodes in a cluster be at Elasticsearch 1.4.4.  Because of this, we can't connect to the cluster using node protocol.  Is it as easy as replacing the jar in the library tree?  How can we customize a build of this plugin to use a new Elasticsearch library?

thanks

**Comment by suyograo** [comment]
Closed in favor of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/81
