### ISSUE TITLE
Track 429s as a metric

### ISSUE THREAD

**Issue by inqueue** [logstash-plugins/logstash-output-elasticsearch#724]
It would be helpful for tracking pipeline health if 429 errors could be counted in a metric. While 429 are considered to be normal during peak ingestion periods, frequent 429s indicate issues downstream in the pipeline. Tracking the metric would be really helpful.

@jpcarey

**Comment by ppf2** [comment]
Linking to work in progress: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/585

**Comment by jsvd** [comment]
#585 records metrics regarding bulk and document level responses. since it has been merged, I'm closing this.
