### ISSUE TITLE
Zero body size bulk call results in a 400 and infinite loop in 7.x

### ISSUE THREAD

**Issue by cjhodges77** [logstash-plugins/logstash-output-elasticsearch#736]
We are running Logstash 5.6.5. We see repeated 400 errors with the message 'Encountered a retryable error. Will Retry with exponential backoff ' that accumulate until the Logstash instance fails and no longer processes logs. We are unsure why Logstash stops processing, possibly file handlers, as in IOException: Too many open files - TCP input. There are no OOM errors.

Enabling debug on the elasticsearch output we get:
{"level":"ERROR","loggerName":"logstash.outputs.elasticsearch","timeMillis":1517840567573,"thread":"[main]>worker2","logEvent":{"message":"Encountered a retryable error. Will Retry with exponential backoff ","code":400,"url":"http://127.0.0.1:9200/_bulk","body":"{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}"}}

The errors pile up over time and are never dropped. We have DLQ enabled and do see some messages in it but none we believe are related to this issue.

The only way we have found to prevent Logstash from failing is to intermittently restart the process.

https://discuss.elastic.co/t/logstash-5-6-1-inifinite-loop-encountered-a-retryable-error/101753 and https://discuss.elastic.co/t/inifinite-loop-encountered-a-retryable-error-400-error-from-elasticsearch/119290 describe the problem.

We believe we have identified the problem and will raise a PR.

**Comment by andrewvc** [comment]
Apologies @cjhodges77 we're looking int othis.

**Comment by jsvd** [comment]
I should note here that his issue is solved for versions 8.x and 9.x of this plugin. Like the title says, this issue is restricted to 7.x
So, as a workaround, please contemplate the option of updating the es output.

**Comment by jsvd** [comment]
version 7.4.3 has been released with a fix to this issue

**Comment by jsvd** [comment]
(and thanks to @cjhodges77 for the PR)
