### ISSUE TITLE
Elasticsearch output should use the recommended mapping type of _doc for the default document_type value

### ISSUE THREAD

**Issue by ddrake17** [logstash-plugins/logstash-output-elasticsearch#764]
Info:
- Version:
6.2.4
- Operating System:
Linux Mint 18.2

By default the elasticsearch output has a `document_type` of `doc` however according to [the schedule for removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_type) the value `_doc` is preferred. 

FWIW I was pretty confused when I updated my elasticsearch template to use `_doc` and I saw a "Rejecting mapping update to index as the final mapping would have more than 1 type: [_doc, doc]" message in `logstash-plain.log` until I figured out that the default of `document_type` setting (which I wasn't using) for the elasticsearch output plugin was `doc`

**Comment by webmat** [comment]
Hello, could you give me a bit more details about your situation?

* Did you attempt this on an existing cluster?
* As things stand, you're right that the plugin uses type "doc" if your ES cluster is on v6. It will automatically use "_doc" when you upgrade to v7. The only situation where this can be overridden is on older ES clusters ([see the code](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v9.1.3/lib/logstash/outputs/elasticsearch/common.rb#L238-L259))
* If you really want to use "_doc", you can always override the current value by using the deprecated plugin attribute "document_type".

**Comment by ddrake17** [comment]
Absolutely. 

- Yes I attempted this on an existing cluster.

I got it working by using the deprecated "document_type" setting once I figured out what was happening. My point was, I was following the best practice recommended by elastic in the link above of using "_doc" and upgraded my template in elasticsearch accordingly. Then I found out the hard way that it didn't work because the elasticsearch output in logstash wasn't conforming to this best practice. As a simple enhancement, I think it would make sense for the output to conform to this best practice.

**Comment by webmat** [comment]
The subtlety here is that support for "_doc" appeared in 6.2.0, not 6.0.0. Our support matrix is only on major versions, not major.minor. You can read more about this in this discussion #734.

I know it's not ideal to circumvent this via a deprecated attribute, but the default right now is just to use "doc" in Logstash for now. The plugin will automatically move to "_doc" as soon as your cluster goes to ES 7. And As far as I know, "doc" will be supported for a bit in 7. You know, so a rolling upgrade doesn't explode everything :-)

I will close this for now. If you care strongly about this, please join the discussion over in  #734?
