### ISSUE TITLE
When overloaded processing slows until it stops

### ISSUE THREAD

**Issue by simmel** [logstash-plugins/logstash-output-elasticsearch#770]
- Version: 6.x branch commit elastic/logstash@0d38d972f3444f33cfe72527c9dd8b31cc05b2b5
- Operating System: Debian stretch
- Config File (if you have sensitive info, please remove it): In this [.tar-file](https://stockholmuniversity.box.com/shared/static/gvyv5d8ju5foql018hj1pi1zs2pt0fmi.tar) as `config.conf`
`jstack-*` thread dumps, `logstash.log` and `apache.log` are also included in [the .tar-file](https://stockholmuniversity.box.com/shared/static/gvyv5d8ju5foql018hj1pi1zs2pt0fmi.tar).
- Sample Data:
I suspect you can use any syslog data but you need quite a lot of it since it takes a couple of hours to reproduce this bug.

- Steps to Reproduce:
  - Start logstash
  ```
  bin/logstash --pipeline.batch.size 512 --experimental-java-execution -f config.conf -w 6
  ```
  - Send data to it:
  ```
  cat logs.log | pv --line-mode --rate-limit 5000 | nc localhost 2514
  ```
  and it can handle that fine.

  - But when you send more logs at Logstash that it can handle it starts to get slower and slower until it after a couple of days stops completely:

  ```
  cat logs.log | pv --line-mode --rate-limit 100000 | nc localhost 2514
  ```

If you look at the thread dumps you can see that the ones at 11:12 logstash spends almost all of it's threads sending to elasticsearch but at 07:23 it does other work too. And I know that that's just one second of work but this is the result that I get everytime.

You can also see in the `apache.log` that the size of the JSON POSTs is sort of constant but it's the frequency of POSTing which slows.

I've also ruled out excessive GC because GC CPU usage is at ~1-2% tops and I've tried with a 10GB heap and LS behaved the same.

Flow of the logs:
```
┌──────┐  ┌────────┐  ┌──────┐  ┌─────────────┐
│netcat│─▶│logstash│─▶│apache│─▶│elasticsearch│
└──────┘  └────────┘  └──────┘  └─────────────┘
```
Apache is there because we use it in production and I haven't figured out how to get access logs from elasticsearch to show that the rate slows. I can reproduce is without apache too.

AFAICT there is no disk I/O latency to speak of. `iostat(1)` and `sar(1)` reports ~1-2% I/O wait which is to be expected because these are spinning disks. The throughput of writes is ~10-30MB/s.

Doing some *very* simple benches on our disk. Using `/dev/zero` is unfair since our SAN is compressed and deduped IIRC.
```
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/zero of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 2.18828 s, 936 MB/s

real    0m4.694s
user    0m0.284s
sys     0m1.908s
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/zero of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 2.22667 s, 920 MB/s

real    0m4.001s
user    0m0.284s
sys     0m1.940s
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/zero of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 2.30756 s, 888 MB/s

real    0m4.895s
user    0m0.300s
sys     0m2.000s
```
Now with `/dev/urandom`:
```
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/urandom of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 11.0958 s, 185 MB/s

real    0m11.229s
user    0m0.276s
sys     0m8.996s
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/urandom of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 8.11523 s, 252 MB/s

real    0m10.338s
user    0m0.236s
sys     0m7.876s
root@syslog-prod-search03:/local# time sh -c "dd if=/dev/urandom of=ddfile bs=8k count=250000 && sync"; rm ddfile
250000+0 records in
250000+0 records out
2048000000 bytes (2.0 GB, 1.9 GiB) copied, 8.0895 s, 253 MB/s

real    0m9.906s
user    0m0.324s
sys     0m7.744s
```
While doing these benches while `sync` is running `iostat(1)` is reporting <10% iowait.

If you need any more information, please let me know!

This is the (last?) blocker for us to upgrade our LS machines to 6.x.

**Comment by simmel** [comment]
Sorry for hilighting but any news @jsvd @andrewvc ? Anything else I can do to help in this issue?

**Comment by simmel** [comment]
Have you had the time to look into this yet? Is there anything I can do to help?

**Comment by jsvd** [comment]
Sorry, I haven't been able yet. I've now setup the environment you described with:
```
while true; do cat apache.log; done | pv --line-mode --rate-limit 100000 | nc localhost 2514 
```

and logstash 6.2.4 with:

```
HOSTNAME=localhost bin/logstash --pipeline.batch.size 512 -f cfg -w 4
```

I'll let it run for some hours now.

**Comment by jsvd** [comment]
looking at your logs, you can see a huge performance drop in 1 hours, but my test is showing no slowdown at all:

```[2018-06-05T16:14:11,689][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
2018-06-05T15:15:11.720Z events/s per second: 39.874600093255935
2018-06-05T15:16:14.217Z events/s per second: 16.318708598989446
2018-06-05T15:17:11.876Z events/s per second: 3329.568137485494
2018-06-05T15:18:11.913Z events/s per second: 6161.686967426923
2018-06-05T15:19:11.926Z events/s per second: 8298.606778664796
2018-06-05T15:20:11.964Z events/s per second: 8925.902333863261
2018-06-05T15:21:11.974Z events/s per second: 9011.108713447537
2018-06-05T15:22:12.019Z events/s per second: 8504.3175035708
2018-06-05T15:23:12.073Z events/s per second: 8352.980034323456
2018-06-05T15:24:12.029Z events/s per second: 8906.5336186731
......
......
2018-06-05T16:26:27.334Z events/s per second: 8719.702506104795
2018-06-05T16:27:27.296Z events/s per second: 8739.107148330691
```

**Comment by jsvd** [comment]
@simmel are you seeing this same issue without the java experimental pipeline?

**Comment by jsvd** [comment]
According to your logs in about 10 minutes performance has dropped to half, but I can't seem to replicate this. I've now tried with the java pipeline in the latest build in the 6.3 branch (I had to since 6.2.4 still takes too long to build that pipeline) and also saw now slow down after 10 minutes:

```
[2018-06-05T17:45:44,250][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
2018-06-05T16:46:48.860Z events/s per second: 6293.68907111048
2018-06-05T16:47:48.801Z events/s per second: 8216.03274339416
2018-06-05T16:48:48.783Z events/s per second: 9712.238539539003
2018-06-05T16:49:48.808Z events/s per second: 10227.009908596363
2018-06-05T16:50:48.833Z events/s per second: 9593.310032480136
2018-06-05T16:51:48.794Z events/s per second: 9014.64894770421
2018-06-05T16:52:48.798Z events/s per second: 9929.395571573874
2018-06-05T16:53:48.902Z events/s per second: 9980.594832970744
2018-06-05T16:54:48.795Z events/s per second: 9991.609632997082
2018-06-05T16:55:48.799Z events/s per second: 10019.640136231195
2018-06-05T16:56:48.820Z events/s per second: 9997.315987002634
2018-06-05T16:57:48.795Z events/s per second: 10245.68439431395
2018-06-05T16:58:48.820Z events/s per second: 10420.140486498762
```

**Comment by simmel** [comment]
Very interesting! What's the difference between our environments?

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
# /local/jdk/bin/java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

How does the logs you are sending through it look? I'm trying to get you 
a set of logs which can be used to reproduce this issue.

**Comment by simmel** [comment]
Aha! After iterating over loads of logs I found out what was wrong: logstash-plugins/logstash-filter-drop#14

So output-elasticsearch was never to blame!

Thanks for all help though!

**Comment by jsvd** [comment]
Glad to see you were able to sort it out @simmel :+1+
