### ISSUE TITLE
sniffing is not supported against a 7.x cluster

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-output-elasticsearch#780]
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client/pool.rb#L173

```
case major_version(url_meta[:version])
        when 5, 6
          sniff_5x_and_above(nodes)
        when 2, 1
          sniff_2x_1x(nodes)
        else
          @logger.warn("Could not determine version for nodes in ES cluster!")
          return nil
end
```

Needs to be updated to include 7. 

This should be blocker to the 7.0 release.

**Comment by jsvd** [comment]
fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/ce49ee5a3cc589e56a640b1c952e56859e851f0d
