### ISSUE TITLE
start two logstash and one of them create default template and one not

### ISSUE THREAD

**Issue by liuhuang9492** [logstash-plugins/logstash-output-elasticsearch#781]
- Version: logstash-5.4.1
- Operating System: CentOS 6.9
- Config File (if you have sensitive info, please remove it):
```
input {
    beats {
        port => 5044
    #    codec => multiline {
    #        pattern => "^# User@Host"
    #        negate => true
    #        what => "previous"
    #    }
    }
    #tcp {
    #    port => 1928
    #}
}

filter {

    grok {
        match => [ "message", "(?m)^# User@Host: %{USER:query_user}\[[^\]]+\] @ (?:(?<query_host>\S*) )?\[(?:%{IP:query_ip})?\](?:\s*Id: %{NUMBER:id:int})?\s+# Query_time: %{NUMBER:query_time:float}\s+Lock_time: %{NUMBER:lock_time:float}\s+Rows_sent: %{NUMBER:rows_sent:int}\s+Rows_examined: %{NUMBER:rows_examined:int}\s*(?:use %{DATA:database};\s*)?SET timestamp=%{NUMBER:timestamp};\s*(?<query>(?<action>\w+)\s+.*)" ]
    }

    grok {
        match => { "message" => "# Time: " }
        add_tag => [ "drop" ]
        tag_on_failure => []
    }

    if  "drop" in [tags] {
        drop {}
    }

    date {
        match => ["mysql.slowlog.timestamp", "UNIX", "YYYY-MM-dd HH:mm:ss"]
        target => "@timestamp"
        timezone => "Asia/Chongqing"
    }
    ruby {
        code => "event.set('[@metadata][today]', Time.at(event.get('@timestamp').to_i).localtime.strftime('%Y.%m.%d'))"
    }
    mutate {
        remove_field => [ "message" ]
    }
}

output {
    stdout { codec => rubydebug }
    elasticsearch {
        hosts => ["10.10.10.10:9200"]
        index => "mysql-slow-%{[@metadata][today]}"
        document_type => "mysql-slow"
    }
}
```
- Sample Data:
- Steps to Reproduce:
    I want collect mysql slow log into elasticsearch and start tow logstash . they have the same configuration , but when I restart a logstash it seems create a default template  names  logstash-* and other one fist start and no create a default template. 
    I find the parameter ```manage_template``` , it will control the logstash  whether  or not create default template logstash-* . so I want know it will always create a default template logstash-* when the parameter ```manage_template```  set true or not config in configfile(it seems default value is true) ? but I hava start multiple logstash and not config the ```manage_template``` , why they hava not created default template logstash-* 
    So I want to know which parameter about the generate  of default template logstash-* . maybe the ```manage_tempate``` or ```template_overwriter``` or ```index_name``` ,env if the template director ?

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.

**Comment by liuhuang9492** [comment]
@jsvd  I am sorry about it and I will move it to the https://discuss.elastic.co.
