### ISSUE TITLE
How do I do partial update to existing elasticsearch document using logstash-output-elasticsearch plugin

### ISSUE THREAD

**Issue by SoujanyaRama** [logstash-plugins/logstash-output-elasticsearch#783]
I am looking at updating one field of existing elasticsearch document using logstash-output-elasticsearch plugin 
Here is my scenario : 
I have document A with field 1, 2, 3 with values 1, 2, 3 correspondingly
after few hours, I receive a document B, 
I need to lookup for document A, and update field 2's value say 200.
Here is the code I am having issue with  

<pre>
        if [postedrespdocid] {
                stdout {}
                elasticsearch {
                        id => "updatelitprocessestime"
                        action => "update"
                        doc_as_upsert => true
                        hosts => [  "https://elastichost:port"             ]
                        index => "%{postedrespdocindex}"
                        document_id => "%{postedrespdocid}"
                         cacert => "/opt/logstash/etc/logstash/certs/ca.crt"
                        user => elastic
                        password => "elastic-for-jupiter"
                        upsert => "" 
                }
        }
</pre>

My issue is Document A is completely overwritten with document A. I am looking at only one field update. 

I am able to achieve the same with _bulk REST API from Kibana's DEV Tools : 
<pre>
POST _bulk
{ "update" : {"_id" : "MdY71mMBgHY495JMBjB_", "_type" : "_doc", "_index" : "clesit-2018.06.06"} }
{ "doc" : {"litprocesstimetest" : "100"}, "doc_as_upsert" : true  }
 </pre>
Thanks in advance !!

**Comment by nervouscat** [comment]
+1

**Comment by gumold** [comment]
Typo: You meant "your Document A is completely overwritten by Document B".
+1

**Comment by hsluoyz** [comment]
You can see a lot of questions and answers on Google like this one: https://stackoverflow.com/questions/38323392/logstash-configuration-how-to-call-the-partial-update-api-from-elastcisearch-ou

**Comment by samirvarandas** [comment]
Hi @SoujanyaRama I am having the same issue, did you manage to solve it? My entire document is being replaced after the update too.

**Comment by SoujanyaRama** [comment]
I could not get elasticsearch output plugin to do the task, so I used http output plugin for the update alone. Here is my output block
 
![image](https://user-images.githubusercontent.com/27687036/135317970-7048f983-0cac-418f-85dc-7962b29502cd.png)

**Comment by samirvarandas** [comment]
Thank you for your response, in my case my document is pretty dynamic it would be difficult to map it inside the doc on the http plugin. Wondering if it still not possible to manage to achieve this using the plugin.

**Comment by SoujanyaRama** [comment]
Am not sure if there is any readily available plugin now.
Another alternative I can think of is, using some criteria, lookup the existing document in current index, make your updated to the looked up result, and push that back to index. This is long shot, and could slowdown your ingestion process, but one alternative you can achieve the single field update.
