### ISSUE TITLE
Default document_type is "doc" instead of "_doc" ?

### ISSUE THREAD

**Issue by sherifabdlnaby** [logstash-plugins/logstash-output-elasticsearch#796]
Using Elasticsearch output plugin, the documents indexed have the type "doc" instead of "_doc", isn't the standard type now after deprecating types is "_doc" ?
- Version: 6.4
- Operating System: Ubuntu 18.04

**Comment by Battleroid** [comment]
The entire stack unfortunately uses `doc` instead of `_doc` which is backwards from my point of view. This just makes transitioning later on more effort.

**Comment by AnthonyJClink** [comment]
This bug is also giving me the following error:

Rejecting mapping update to [unregistered-2020] as the final mapping would have more than 1 type: [_doc, doc]

we mapped this index with _doc

so I am not sure how to force logstash to send _doc

**Comment by Battleroid** [comment]
@AnthonyJClink you should be able to set `document_type => "_doc"`

**Comment by kares** [comment]
closing as duplicate of https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/868
