### ISSUE TITLE
[Feature request/enhancement] HTTP compression level in logstash-output-elasticsearch plugin 

### ISSUE THREAD

**Issue by nfsec** [logstash-plugins/logstash-output-elasticsearch#834]
Logstash-output-elasticsearch plugin supports http compression ( https://www.elastic.co/guide/en/logstash/6.1/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-http_compression ) for requests. But only on default level:

> Zlib::DEFAULT_COMPRESSION (6)

For a compromise between CPU and network usage - i think the ability to choose a zlib level (from 0-9) would be nice thing to have.

**Comment by geekpete** [comment]
Logstash now compresses by default and allows configuring the compression level?
https://support.elastic.dev/knowledge/view/37d3f346

https://www.elastic.co/guide/en/logstash/8.11/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-compression_level
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v11.22.2/CHANGELOG.md#11170

**Comment by nfsec** [comment]
Of course. Thank you for the memory. It was worth waiting.
