### ISSUE TITLE
Index action dropped with no response code

### ISSUE THREAD

**Issue by ahmedyossef** [logstash-plugins/logstash-output-elasticsearch#84]
Hi 
I am facing a strange behavior in logstash 1.5.0.RC2 
Every second I get one of these messages                                                                                                                                                               │{:timestamp=>"2015-03-24T16:21:49.644000-0700", :message=>"failed action with response of , dropping action: [\"index\", {:_id=>nil, :_index=>\"logs-2015.03.24.23\", :_type=>\"hourly\"}, #<LogStash::Event:0x6ce115d8 @metadata={\"retry_count\"=>0}, @accessors=#<LogStash::Util::Accessors:0x2ebd1571 @store={\"@timestamp\"

This behavior started with I updated from 1.4. to 1.5 RC2, 

The problem is that I don't get any response code and I don't see any errors in elastic search itself

For more context I am using the following configurations
elasticsearch {
protocol => "http"
host => [ array of hosts]
workers => 3
flush_size => 10
index => "logs-%{+YYYY.MM.dd.HH}"

And I am running elastic search 1.4.4

**Comment by ahmedyossef** [comment]
I found another similar issue, will close this one and follow up on the existing one

**Comment by talevy** [comment]
related to #77
