### ISSUE TITLE
Encountered a retryable error. Will Retry with exponential backoff  {:code=>400, :url=>"http://elasticsearch:9200/_bulk"}  vs es_version 6.5.1

### ISSUE THREAD

**Issue by sunchanglong1991** [logstash-plugins/logstash-output-elasticsearch#847]
- Version: 6.5.1
- Operating System: centos
- Config File ：
logstash.config

```
input {
  udp {
    port => 55144
    type => "log"
  }
}
output {
  stdout { codec => rubydebug }

  elasticsearch {
        hosts => ["******"]
        index => "alarm"
        document_type => "udp"
        manage_template => true
        template => "/etc/template/logstash_***.json"
        template_name => "***_template"
        template_overwrite => true
    } 
}
```

Codec => ruby ​​debug

can output log data, but logstash.outputs.elasticsearch reports an error with

[ERROR][logstash.outputs.elasticsearch] Encountered a retryable error. Will Retry with exponential backoff {:code=>400, : Url=>"http://******:9200/_bulk"}

Elasticsearch does not have any log output

**Comment by jsvd** [comment]
I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
