### ISSUE TITLE
Add host failover support for Transport and HTTP clients

### ISSUE THREAD

**Issue by talevy** [logstash-plugins/logstash-output-elasticsearch#85]
If existing hosts become unresponsive, we should drop unresponsive hosts and attempt to 
search for new valid hosts that later join the cluster.

**Comment by rhoml** [comment]
This could represent a problem if you are running a LB locally on your box because your local LB would be taken out of the pool. I believe that this logic should be done by the LB not by logstash output.

**Comment by andrewvc** [comment]
his has been the case for quite a while now!
