### ISSUE TITLE
Is it possible to support indexing of dynamic variables using rollover?

### ISSUE THREAD

**Issue by zcola** [logstash-plugins/logstash-output-elasticsearch#858]
output {
        elasticsearch {
            hosts => [ 'ccc.om:9200' ]
                ilm_enabled => true
                ilm_rollover_alias => "cbg_%{product}_%{log}_loghub"
        }
}
```
def setup_ilm
      return unless ilm_enabled?
      if default_index?(@index) || !default_rollover_alias?(@ilm_rollover_alias)
        logger.warn("Overwriting supplied index #{@index} with rollover alias #{@ilm_rollover_alias}") unless default_index?(@index)
        @index = @ilm_rollover_alias
        maybe_create_rollover_alias
        maybe_create_ilm_policy
      end
    end
```

Now it is time to determine if rolloverneeds to create rollover when it starts.

@robbavey

**Comment by zcola** [comment]
If ES bulk can determine that the target index is not a rollover index and returns an error to logstash , then should it be able to create it automatically?

**Comment by ppf2** [comment]
This does not appear to work today.

Without ILM, Logstash variable substitution works as expected:

```
index => "mytest-%{[@metadata][index]}-%{+YYYY.MM.dd}" 
```

But the equivalent for ILM does not work.  Both `ilm_rollover_alias` and `ilm_pattern` settings throw errors when attempting to use Logstash substitution syntax:

```
ilm_rollover_alias => "logstash-%{[@metadata][index]}"
ilm_pattern => "{now/d}-000001"
```

```
ilm_rollover_alias => "logstash" 
ilm_pattern => "%{[@metadata][index]}-{now/d}-000001"
```

**Comment by ppf2** [comment]
Until this is addressed, it will be helpful to set expectations in the documentation in these sections:

- Should we tell Beats -> LS users to avoid using LS/ILM integration until the enhancement is made?
  - https://www.elastic.co/guide/en/beats/libbeat/6.8/breaking-changes-6.0.html#breaking-changes-ls-index (we actually state here that it is a requirement to substitute in beat + beat version into the index setting so ILM users will be looking for its equivalent)
  - https://www.elastic.co/guide/en/beats/metricbeat/current/logstash-output.html#logstash-output (same for each beat type)
- Add a note here to indicate that the ILM settings do not support variable substitution notation in Logstash: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-ilm

**Comment by Battleroid** [comment]
This is unfortunate; it's possible to use the substitutions on `ilm_policy`, but nothing else. This makes setting up multiple RO aliases a bit difficult.

**Comment by Battleroid** [comment]
I managed to cobble something terrible together that appears to work (see [here](https://github.com/Battleroid/logstash-output-elasticsearch/tree/ilm_substitution)). It's not great, but it is functional. I still have some things to tinker with but at least this works for now.

Sample run/config as an example here:
https://gist.github.com/Battleroid/beec2b88c9b59fd3665defa08162c4fb

**Comment by Battleroid** [comment]
I've made some additional changes to this to allow it to do the creation of the rollover index with the specified pattern, but without setting the settings, etc. When I tried this initially the cluster came to a complete stop after a few hours, filled with `ilm-set-step-info` tasks.

Letting logstash just create the aliases seems to be a good compromise. We are able to have something external do the process of rollover. We don't have to worry about creating the index patterns or about ILM rollover related tasks clogging things up.

**Comment by jeffrysleddens** [comment]
We also would love to use ILM within logstash but were hit by this issue.  We would like to use dynamic naming in the ilm_rollover_alias setting like we used to in the index setting.

A short search learns that quite a few people run into this limitation with ilm in the elasticsearch output:
https://discuss.elastic.co/t/es-output-using-ilm-settings-malformed-escape-pair-at-index/178117
https://discuss.elastic.co/t/use-of-metadata-in-ilm-configuration/182918

**Comment by AndrewMcQuerry** [comment]
Same here.  We would love to leverage the ilm_* settings within logstash to help manage this but were stopped dead-in-the-water due to this limitation.

**Comment by gekkeharry13** [comment]
Same issue here, +1 for adding this feature

**Comment by astraios** [comment]
+1 here, being able to dynamically set `ilm_rollover_alias`/`ilm_policy` using the same syntax as the `index` field would be huge.

**Comment by spencergilbert** [comment]
I don't see how ilm without dynamic setting like index is even usable if you're not looking to hand curate all of your indices, or wanting to work outside of the cluster to provide the functionality

**Comment by msvechla** [comment]
I've opened an issue about this scenario when ILM initially was introduced. Having the ability to use variables inside these settings is essential for us to make dynamic rollover patterns work.

This feature would be a huge benefit for our large elasticsearch infrastructure.

**Comment by nicolas-123** [comment]
+1, also looking to set ilm_rollover_alias dynamically

**Comment by jianchen2580** [comment]
+1

**Comment by mscam** [comment]
+1, I am also looking for this

**Comment by vogon1** [comment]
+1, same here.

**Comment by cedzz** [comment]
+1, same here.

**Comment by asega** [comment]
+1

**Comment by reighnman** [comment]
Trying to use CPM compounds the issue as CPM currently doesn't support wildcards in xpack.management.pipeline.id so we need to use pipelines with aggregated inputs but cannot dynamically assign ilm policies without being able to use substitutions like we can with index names.

Once CPM can support wildcards for pipeline.id's then we could have a pipeline per output with a static ilm name.

**Comment by msvechla** [comment]
I wrote a Kubernetes controller to solve these current limitations and automates the rollover pattern. This will help if you want to forward Kubernetes Pod logs to Elasticsearch. If you are interested you can take a look here: https://gitlab.com/msvechla/es-rollover-controller

**Comment by iwasnobody** [comment]
+1

**Comment by rpasche** [comment]
+1

**Comment by HitkoDev** [comment]
Any news on this?

**Comment by phobosale** [comment]
+1

**Comment by paulojmdias** [comment]
+1

**Comment by admlko** [comment]
+1

**Comment by epol** [comment]
+1

**Comment by jsvd** [comment]
Hi folks, to those coming here to vote on the issue, please use the +1 on the initial comment, as the "+1" only adds noise to the issue.

The expectations when using ILM are the same when using indices, where if the destination doesn't exist, Elasticsearch automatically creates an index for you that respects the index template if the name matches the pattern.

For write aliases this isn't possible in Elasticsearch as the write alias creation is an [explicit action](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/indices-add-alias.html).
Some discussion has been happening in Elasticsearch to improve this user experience, please subscribe the following related issues:

- https://github.com/elastic/elasticsearch/issues/36627
- https://github.com/elastic/elasticsearch/issues/38454
- https://github.com/elastic/elasticsearch/issues/42245
- https://github.com/elastic/elasticsearch/issues/41699

**Comment by tomrade** [comment]
I use beats and LS , I imported in the beats index template and ILM, however with ILM off (in logstash) there isnt an easy way to create the index dynamic with an alias. I added it to my index mapping but that broke ILM as multiple indexes could have that alias, from this thread is my understanding that with logstash I (or logstash) needs to create the write index first at some point (pipeline startup?)

**Comment by mccarthyp-snet** [comment]
+1

**Comment by nHurD** [comment]
+1

**Comment by jsvd** [comment]
Quick update: a meta issue has been created in elasticsearch to track the work of building the concept of alias templates, which facilitates the support of dynamic parameters in this plugin's ILM setup. For those interested in this feature you can track the progress here: https://github.com/elastic/elasticsearch/issues/51995

**Comment by drenze** [comment]
+1

**Comment by maggieghamry** [comment]
+1

**Comment by tarunpasrija** [comment]
+1 
I really hate to keep manual interactions while setting up indexes.. Need only 1 place which is logstash to push those template changes so that its more manageable. Example config.

input {
  kafka {
    bootstrap_servers => "{{bootstrap_servers}}"
    topics => ["mytopic1", "mytopic2"]
    auto_offset_reset => "earliest"
    client_id => "application-metrics-{{ansible_hostname}}"
    consumer_threads => 2
    group_id => "application-metrics-{{envvar}}"
    
  }
}

output {
		elasticsearch {
				hosts => {{es_master_nodes}}
                user => {{logstash_writer_user}}
                password => {{logstash_writer_password}}
                ilm_rollover_alias => "application-metrics-**%{topic}**-{{envvar}}"
                template => "/etc/logstash/index/application-metrics.json"
                template_name => "application-metrics-{{envvar}}"
                ilm_pattern => "000001"
                ilm_policy => "default"
                manage_template => true
		}
}

As the above example.. I need to insert the Topic Name in ilm_rollover_alias and I can have single configuration for multiple Kafka topics instead of creating a new pipeline for each kafka topic.

**Comment by dunkelbunt1** [comment]
+1

**Comment by Zoom2016** [comment]
+1
This feature will be very helpful to me

**Comment by NanayaLL** [comment]
+1

**Comment by jugggao** [comment]
+1 
This feature will be very helpful to me ☹

**Comment by iainmarshall** [comment]
+1 
This feature is something I am dying for please.

**Comment by flaper87** [comment]
Another thumbs up over here: :+1:

**Comment by obogobo** [comment]
yes +1, we currently use a shell script to bulk create a ton of templates as a workaround lol

**Comment by Jayw77** [comment]
+1, finally got all my indexes generating via labels per app how I wanted it to only realise I can't use the dynamically generated name/index with ILM :(

**Comment by ppf2** [comment]
With version 7.9's new [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/data-streams.html) implementation, we should be able to leverage this new feature to achieve dynamic variable substitution for index names with ILM+rollover.  I have submitted a [doc issue](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/966) with draft for proper documentation, pending review.

**Comment by msvechla** [comment]
> With version 7.9's new [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/data-streams.html) implementation, we should be able to leverage this new feature to achieve dynamic variable substitution for index names with ILM+rollover. I have submitted a [doc issue](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/966) with draft for proper documentation, pending review.

Unfortunately nothing has changed here. This was possible before, by setting up the rollover pattern via index template, ILM policy, rollover index and write alias manually and finally pointing logstash at the write alias with variable substitution.

In your example everything is still setup manually. I thought this issue is about allowing variable substitution, when dynamically creating the required artifacts for rollover / ILM (e.g. ilm rollover alias, see https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/858#issue-429121752).

I think this is still not solved, right?

**Comment by tomrade** [comment]
My thoughts were the user wants to use %{VAR} in the ILM alias (which wouldnt work ) , which they can do now with data streams as a data stream can be created dynamically (via the index name provided in the index request and a matching mapping template).

https://www.elastic.co/guide/en/elasticsearch/reference/7.x/set-up-a-data-stream.html#index-documents-to-create-a-data-stream

**Comment by msvechla** [comment]
> My thoughts were the user wants to use %{VAR} in the ILM alias (which wouldnt work ) , which they can do now with data streams as a data stream can be created dynamically (via the index name provided in the index request and a matching mapping template).
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/7.x/set-up-a-data-stream.html#index-documents-to-create-a-data-stream

Awesome, thanks for clarifying, I totally missed this functionality.

Indeed, we can then setup an index template including a data stream and ILM once with a more generic index pattern such as `my-streams-*` and then instruct logstash to write to `my-streams-%{VAR}`, which will create a new data stream for every unique value of %{VAR}.

That's a big improvement, thanks for the hint!

**Comment by pujithkurunji** [comment]
> +1 here, being able to dynamically set `ilm_rollover_alias`/`ilm_policy` using the same syntax as the `index` field would be huge.

Any updates on this?
```
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][log_index]}"
    ilm_rollover_alias => "%{[@metadata][log_index]}"
    ilm_pattern => "000001"
    ilm_policy => "custom_policy"
  }

```
This is what I'm expecting. I can use a dynamic index, by getting log_index from Filebeat. I want to use the same in  ilm_rollover_alias.

**Comment by aseppala** [comment]
+1

**Comment by konstantin-921** [comment]
+1

**Comment by elihugi89** [comment]
+1

**Comment by Karrade7** [comment]
Logstash does not yet support datastreams. So even if datastreams solves the issue, logstash can't use it.
Therefore the initial problem of dynamic ILM names using logstash is still an issue.
When the logstash datastreams plugin is ready it would need be tested if it solves this issue,
https://github.com/elastic/logstash/issues/12178

**Comment by orjan** [comment]
@Karrade7 we're using data streams with logstash `7.9.x` and it works fine if the `op_type` is changed to create and the `doc_type` is suppressed. ILM and templates should also be inactivated but I don't see a need for them since it's so easy to configure the templates for data streams?

**Comment by jsvd** [comment]
Logstash has started supporting Data Streams since 7.13.0. ILM, when used without Data Streams will not be able to automatically create aliases, this is a known design limitation of the Elasticsearch feature so there is no "fix on the Logstash side".
However, using data streams, any data written to an index that matches the [data stream pattern](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html#create-index-template) will create an alias and apply the lifecycle policy.
Logstash will by default allow you to write to data streams that ship with Elasticsearch (`logs-*`, `metrics-*`, `synthetics-*` and `traces-*`) but if you create your own data stream pattern you can write to it with Logstash as any normal index, by disabling data streams and setting action to create:

```
elasticsearch {
  data_stream => false
  index => "my-data-stream-pattern-%{[event][data]}" # e.g. data stream pattern is "my-data-stream-pattern-*"
  action => create
}
```

Hopefully the Data Streams feature in ES + support for built in Datastreams in Logstash + direct writing to a data stream with create action solves all the needs y'all have.

One last thing we'll likely end up adding is a separate setting to specify a `data_stream_pattern` that will be equivalent to the settings shown in the snippet above (plain write to an index + setting action to create).

**Comment by roaksoax** [comment]
Provided the above explanation, and there hasn't been any further discussion, I'm going to go ahead and close this issue.

If anyone believe this issue still applies to you, please feel free to re-open or create a new issue.

Thanks.
