### ISSUE TITLE
Partial Update

### ISSUE THREAD

**Issue by Onalu** [logstash-plugins/logstash-output-elasticsearch#86]
Hi,

Elasticsearch bulk API has an action called ``update`` to update documents partially. But, Elasticsearch output only support index and delete actions. When I was looking inside the code, I saw another action called ``create_unless_exists``. Is c``reate_unless_exists`` action used for partial update or something else? If it is not for partial update, is there a plan to add ``update`` action as a valid action?

Thanks

**Comment by untergeek** [comment]
Update is a valid action, but currently only if you're using `protocol => "http"`:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/protocol.rb#L81-L94

We do need to add update as a valid action for the node and transport protocols.

**Comment by untergeek** [comment]
This issue is a duplicate. Closing this in favor of #16
