### ISSUE TITLE
Logstash default document_type inconsistent with types removal recommendation

### ISSUE THREAD

**Issue by hackery** [logstash-plugins/logstash-output-elasticsearch#868]
I asked  this previously [on the forum](https://discuss.elastic.co/t/elasticsearch-doc-type-deprecation-doc-vs-doc/139799) but it didn't seem to draw any attention.

The [advice in the doctype deprecation notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types) is to use a document type of `_doc` in 6.x to prepare for type removal. However the Logstash Elasticsearch [output plugin defaults](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-document_type) to `doc`.

At this point we should be able to omit the `document_type` parameter (*which flags a deprecation warning!*) and not require that configuration change between 6.x and 7.x.

**Comment by pemontto** [comment]
Same as #796 

This just stung us going to ES7. It seems this plugin will use `doc` with ES6 and `_doc` with ES7 😞

Cue tonnes of error messages:
```
Rejecting mapping update to [x] as the final mapping would have more than 1 type: [_doc, doc]
```

**Comment by davidhowell-tx** [comment]
Glad to hear this is only an issue when you're on ES6. I was upgrading my index templates and came across this issue. Having to pick between setting my index templates back the way they were and seeing a deprecation warning, or setting all of my Logstash outputs to document_type => "_doc" and seeing a deprecation warning.

**Comment by kares** [comment]
has been resolved in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/994
