### ISSUE TITLE
Add support authentication with API keys

### ISSUE THREAD

**Issue by andrewkroh** [logstash-plugins/logstash-output-elasticsearch#908]
Elasticsearch has support for authentication with [API keys](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/security-api-create-api-key.html). As a user I would like to be able to configure the elasticsearch output with an API key, as opposed to a username and password, for authenticating.

Logstash would add a header like `Authorization: ApiKey base64(<api_key_id>:<key>)` to HTTP requests to Elasticsearch.

**Comment by kcy1019** [comment]
Any update on this?
+ Current workaround is adding `Authorization` header to `custom_headers` field.

**Comment by colinsurprenant** [comment]
In progress in #934

**Comment by kcy1019** [comment]
Great! Thanks :D

**Comment by AMITKHETAN** [comment]
Hi, Its fixed but I still need to pass both API_ID and API_KEY value as "<API_ID>:<API_KEY>". It should work directly with base64 encoded API KEY - "BASE64_API_KEY" value only.

**Comment by colinsurprenant** [comment]
Hello @AMITKHETAN - thanks for your feedback, could you please open a new issue for this and explain your particular use-case? Thanks.
