### ISSUE TITLE
Document that in node protocol the list of hosts must include master nodes

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-output-elasticsearch#92]
"NodeClient can't join to a cluster if unicast hosts contains only client node (client nodes are filtered out in ZenDiscovery#findMaster()). You need to set "discovery.zen.master_election.filter_client" to false to override the behavior. "

Therefore we should document that the list of hosts should include master nodes, and that it will fail if only client nodes are listed.

**Comment by bleskes** [comment]
To be exact - it should not per se include master nodes but point to a couple of the ES non-client nodes. Client nodes are filtered out by default. IMHO the right solution is to expose the  unicast hosts list directly as a setting and call it such. This way people can look up with it means in the ES docs and all the best practives for it.

**Comment by purbon** [comment]
I think is part of the documentation is important: 

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L177

  # The default `protocol` setting under java/jruby is "node". The default
  # `protocol` on non-java rubies is "http"
