### ISSUE TITLE
SSL Settings ignored if when using cloud_id unless explicitly setting `ssl => true`

### ISSUE THREAD

**Issue by yaauie** [logstash-plugins/logstash-output-elasticsearch#935]
When connecting via `cloud_id` and not explicitly setting `ssl => true`, the `params["hosts"]` is unpopulated causing us to fail to apply SSL-related settings:

https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v10.4.1/lib/logstash/outputs/elasticsearch/http_client_builder.rb#L107-L108

Connections established in this way are still made over SSL, since the resulting host protocol is `https`, but we fail to apply the SSL-related settings.

**Comment by richardim** [comment]
A couple of related existing github issues
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/433
https://github.com/elastic/support-dev-help/issues/4186

**Comment by richardim** [comment]
i helped my user try using the hosts array and uname/pw. However, it still did not work. We do see the log messages print out how the combination of using ssl but verification false being insecure. We see that with the cloud_id and the hosts array...

The only thing that made it operate at all was to use the ece ca pem and supply it to logstash.
