### ISSUE TITLE
Deprecated "path": "full" mapping in elasticsearch index template

### ISSUE THREAD

**Issue by tylerjl** [logstash-plugins/logstash-output-elasticsearch#94]
The default index template bundled with the plugin specifies `"path": "full"` for the `geoip` field in `_default_`. This has been [deprecated as of 1.0.0](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-object-type.html#_path_4), but more importantly, it outright breaks new index creation on latest (master) builds of elasticsearch:

```
org.elasticsearch.index.mapper.MapperParsingException: Mapping definition for [geoip] has unsupported parameters:  [path : full]
```

The docs indicate `copy_to` is the successor to `path`. In any case, the current behavior of logstash + latest builds of elasticsearch is a broken `elasticsearch` output, which is an annoyance for now, but will end up being big-blow-up-no-fun-for-anyone when logstash gets paired with a 2.x elasticsearch instance down the road. :boom: :sweat_smile:

**Comment by untergeek** [comment]
Thanks for the update, @tylerjl 

Did you want to do a pull request to fix it, or just let us handle it?  While we're scrambling to get 1.5 out, this will not be as pressing.  But if you were to submit a PR, we'd be able to just merge it.

**Comment by tylerjl** [comment]
Based on some really hacked-together testing on ES 0.90, 1.4, and master, just plain removing the line still allows you to query the full path, aggregate on it, etc.,  so I *think* just nixing the line will solve this.

**Comment by kimchy** [comment]
we should be able to simply remove this "full" path config, and things will work correctly, since this is the default
