### ISSUE TITLE
Change logstash template to use norms.enabled: false

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-output-elasticsearch#95]
Have we considered updating the LS template to replace the deprecated `omit_norms` with `norms.enabled: false` when it comes to disabling norms?http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#norms

**Comment by talevy** [comment]
I can take a look at this maybe later on. I do not think it is critical at the moment.

**Comment by andrewvc** [comment]
Good news, this was merged in quite a while ago!

**Comment by rtoma** [comment]
Have a look at https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/elasticsearch-template.json (tag 2.4.0).

It still contains several 'omit_norms' occurrences.

**Comment by untergeek** [comment]
@rtoma This will be obviated in future releases.  Elasticsearch will auto-replace the older syntax with the newer one, transparently.  We'll update the mapping as we deprecate older versions of Logstash.
