### ISSUE TITLE
Is there any option or way to turn off stdout related options

### ISSUE THREAD

**Issue by chosh31** [logstash-plugins/logstash-output-elasticsearch#979]
When using the `logstash elasticsearch output`, it can be seen that stdout logging is displayed even without additional stdout setting.

Is there any option or way to turn off stdout related options?

**Comment by kares** [comment]
the logging part is managed by LS itself, each plugin will add to LS' logs. you can adjust logging at `config/log4j2.properties`

**Comment by chosh31** [comment]
> the logging part is managed by LS itself, each plugin will add to LS' logs. you can adjust logging at `config/log4j2.properties`

Thank you for answer.
However, regardless of the above setting change(config/log4j2.properties), the JSON object log remains. This log does not occur in other logstash output modules.

Is there a module part that leaves debugging logs in JSON format?
