### ISSUE TITLE
scripted_upsert not working on ES connection failure / retry

### ISSUE THREAD

**Issue by enodr** [logstash-plugins/logstash-output-elasticsearch#986]
Using the latest version of the plugin with latest ELK stack there is a bug when using scripted_upsert or any script params in the output.

Steps to reproduce: 
- Use an output with a scripted_upsert
- When connection to ES is lost, on retry the script related parameters are lot and a normal update is used instead.

This pull request fixes the issue:
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/800

The bug is in file lib/logstash/outputs/elasticsearch/http_client.rb in function update_action_builder https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/47fef224b1c9f1c3e8dd010bc633a0e2e3ae6bf2/lib/logstash/outputs/elasticsearch/http_client.rb#L402

The args elements are deleted. Thus when a retry on failure is issued the params cannot be parsed correctly.
https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/47fef224b1c9f1c3e8dd010bc633a0e2e3ae6bf2/lib/logstash/plugin_mixins/elasticsearch/common.rb#L280

I have tested the above fix and it confirm it works as expected.

**Comment by enodr** [comment]
Regarding my post above, some more investigation is required. With the suggested fix, while it seems to work at first, the output queue is never cleared and Elastic seems stuck in a loop. 

I hope a dev could have a look at the code logic?

**Comment by jsvd** [comment]
closed by #995, released as 10.8.4
