### ISSUE TITLE
Year week pattern failure

### ISSUE THREAD

**Issue by rdrgporto** [logstash-plugins/logstash-output-elasticsearch#987]
- Version: Logstash 7.8.0 & Logstash Output Elasticsearch 10.5.1
- Operating System: Ubuntu 18.04.4

We have set up an **index name** with the following pattern, for example:

`index => "winlogbeat-%{+YYYY.ww}"`

However, after **31th December 2020**, **Logstash** created all index with that pattern with the following **index name**:

`winlogbeat-2021.53`

I expected to have a index **winlogbeat-2020.53** until **3rd of January**:

![january-2021](https://user-images.githubusercontent.com/6654666/104172019-daf42300-5403-11eb-900d-0025190d92c8.png)

Thanks in advance

🆕 Update: We have decided to use **ILM** (**Index Lifecycle Management**) in order to use **index year** and **rollover** (`winlogbeat-2021-0001, winlogbeat-2021-0002`, etc).

**Comment by abdamou** [comment]
Hi,
I encountered the same issue

**Comment by rdrgporto** [comment]
We have decided to use **ILM** (**Index Lifecycle Management**) in order to use **index year** and **rollover** (`winlogbeat-2021-0001, winlogbeat-2021-0002`, etc).
